YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::WetDryEffect_ Class Reference
Tonic::Tonic_::WetDryEffect_ Class Reference
#include <Effect.h>
Public Member Functions
WetDryEffect_ ()
void setDryLevelGen (Generator gen)
void setWetLevelGen (Generator gen)
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
virtual void tickThrough (TonicFrames &inFrames, TonicFrames &outFrames, const SynthesisContext_ &context)
Apply effect directly to passed in frames (output in-place)
Public Member Functions inherited from Tonic::Tonic_::Effect_
Effect_ ()
void setBypassCtrlGen (ControlGenerator gen)
virtual void setInput (Generator input)
virtual void setIsStereoInput (bool stereo)
set stereo/mono - changes number of channels in dryFrames_
bool isStereoInput ()
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Attributes
Generator dryLevelGen_
Generator wetLevelGen_
TonicFrames mixWorkspace_
Protected Attributes inherited from Tonic::Tonic_::Effect_
Generator input_
TonicFrames dryFrames_
ControlGenerator bypassGen_
bool isStereoInput_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Additional Inherited Members
Protected Member Functions inherited from Tonic::Tonic_::Generator_
virtual void computeSynthesisBlock (const SynthesisContext_ &context)
Detailed Description
Definition at line 163 of file Effect.h.
Constructor & Destructor Documentation
WetDryEffect_()
Tonic::Tonic_::WetDryEffect_::WetDryEffect_ ()
Definition at line 26 of file Effect.cpp.
References dryLevelGen_, Tonic::kSynthesisBlockSize, mixWorkspace_, Tonic::TonicFrames::resize(), and wetLevelGen_.
     {
       mixWorkspace_.resize(kSynthesisBlockSize, 1, 0);
       dryLevelGen_ = FixedValue(0.5);
       wetLevelGen_ = FixedValue(0.5);
     }
Member Function Documentation
setDryLevelGen()
void Tonic::Tonic_::WetDryEffect_::setDryLevelGen (Generator gen) inline
Definition at line 175 of file Effect.h.
References dryLevelGen_.
 { dryLevelGen_ = gen; };
setWetLevelGen()
void Tonic::Tonic_::WetDryEffect_::setWetLevelGen (Generator gen) inline
Definition at line 176 of file Effect.h.
References wetLevelGen_.
 { wetLevelGen_ = gen; };
tick()
void Tonic::Tonic_::WetDryEffect_::tick (TonicFrames & frames, const SynthesisContext_ & context) inline virtual
Reimplemented from Tonic::Tonic_::Effect_.
Definition at line 193 of file Effect.h.
References Tonic::Tonic_::Effect_::bypassGen_, Tonic::Tonic_::Generator_::computeSynthesisBlock(), Tonic::TonicFrames::copy(), Tonic::Tonic_::Effect_::dryFrames_, dryLevelGen_, Tonic::Tonic_::SynthesisContext_::elapsedFrames, Tonic::error(), Tonic::Tonic_::Effect_::input_, Tonic::Tonic_::Generator_::lastFrameIndex_, mixWorkspace_, Tonic::Tonic_::Generator_::outputFrames_, Tonic::Generator::tick(), Tonic::ControlGenerator::tick(), Tonic::ControlGeneratorOutput::value, and wetLevelGen_.
{
       // check context to see if we need new frames
       if (context.elapsedFrames == 0 || lastFrameIndex_ != context.elapsedFrames){
         // get dry input frames
         input_.tick(dryFrames_, context);
         computeSynthesisBlock(context);
         // bypass processing - still need to compute block so all generators stay in sync
         bool bypass = bypassGen_.tick(context).value != 0.f;
         if (bypass){
           outputFrames_.copy(dryFrames_);
         }
         else{
           // do not apply dry/wet levels if always wet flag is set
           // offers minor CPU usage optimization
           wetLevelGen_.tick(mixWorkspace_, context);
           outputFrames_ *= mixWorkspace_;
           dryLevelGen_.tick(mixWorkspace_, context);
           dryFrames_ *= mixWorkspace_;
           outputFrames_ += dryFrames_;
         }
         lastFrameIndex_ = context.elapsedFrames;
       }
       // copy synthesis block to frames passed in
       frames.copy(outputFrames_);
 #ifdef TONIC_DEBUG
       if(!isfinite(frames(0,0))){
         Tonic::error("Effect_::tick NaN or inf detected.");
       }
 #endif
     }
tickThrough()
void Tonic::Tonic_::WetDryEffect_::tickThrough (TonicFrames & inFrames, TonicFrames & outFrames, const SynthesisContext_ & context) inline virtual
Apply effect directly to passed in frames (output in-place)
DO NOT mix calls to tick() with calls to tickThrough().
Reimplemented from Tonic::Tonic_::Effect_.
Definition at line 232 of file Effect.h.
References Tonic::Tonic_::Effect_::bypassGen_, Tonic::Tonic_::Generator_::computeSynthesisBlock(), Tonic::TonicFrames::copy(), Tonic::Tonic_::Effect_::dryFrames_, dryLevelGen_, mixWorkspace_, Tonic::Tonic_::Generator_::outputFrames_, Tonic::Generator::tick(), Tonic::ControlGenerator::tick(), Tonic::ControlGeneratorOutput::value, and wetLevelGen_.
{
       // Do not check context here, assume each call should produce new output.
       dryFrames_.copy(inFrames);
       computeSynthesisBlock(context);
       // bypass processing - still need to compute block so all generators stay in sync
       bool bypass = bypassGen_.tick(context).value != 0.f;
       if (bypass){
         outFrames.copy(dryFrames_);
       }
       else {
         wetLevelGen_.tick(mixWorkspace_, context);
         outputFrames_ *= mixWorkspace_;
         dryLevelGen_.tick(mixWorkspace_, context);
         dryFrames_ *= mixWorkspace_;
         outputFrames_ += dryFrames_;
         outFrames.copy(outputFrames_);
       }
     }
Member Data Documentation
dryLevelGen_
Generator Tonic::Tonic_::WetDryEffect_::dryLevelGen_ protected
Definition at line 167 of file Effect.h.
mixWorkspace_
TonicFrames Tonic::Tonic_::WetDryEffect_::mixWorkspace_ protected
Definition at line 169 of file Effect.h.
wetLevelGen_
Generator Tonic::Tonic_::WetDryEffect_::wetLevelGen_ protected
Definition at line 168 of file Effect.h.
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp