YOURPROJECTNAMEGOESHERE: Tonic::Compressor Class Reference
Tonic::Compressor Class Reference
#include <CompressorLimiter.h>
Public Member Functions
Compressor (float threshold=0.5, float ratio=2, float attack=0.001, float release=0.05, float lookahead=0.001)
Compressor & audioInput (Generator input)
Input for audio to be compressed.
Compressor & sidechainInput (Generator input)
Input for audio for compression amplitude envelope.
void setIsStereo (bool isStereo)
TONIC_MAKE_CTRL_GEN_SETTERS (Compressor, attack, setAttack)
TONIC_MAKE_CTRL_GEN_SETTERS (Compressor, release, setRelease)
TONIC_MAKE_CTRL_GEN_SETTERS (Compressor, threshold, setThreshold)
TONIC_MAKE_CTRL_GEN_SETTERS (Compressor, ratio, setRatio)
TONIC_MAKE_CTRL_GEN_SETTERS (Compressor, lookahead, setLookahead)
TONIC_MAKE_CTRL_GEN_SETTERS (Compressor, makeupGain, setMakeupGain)
Public Member Functions inherited from Tonic::TemplatedEffect< Compressor, Tonic_::Compressor_ >
virtual Compressor & input (Generator input)
void tickThrough (TonicFrames &inFrames, const Tonic_::SynthesisContext_ &context)
void tickThrough (TonicFrames &inFrames, TonicFrames &outFrames, const Tonic_::SynthesisContext_ &context)
void setIsStereoInput (bool isStereoInput)
TONIC_MAKE_CTRL_GEN_SETTERS (Compressor, bypass, setBypassCtrlGen)
Public Member Functions inherited from Tonic::TemplatedGenerator< Tonic_::Compressor_ >
TemplatedGenerator ()
Public Member Functions inherited from Tonic::Generator
Generator (Tonic_::Generator_ *gen=new Tonic_::Generator_)
bool isStereoOutput ()
virtual void tick (TonicFrames &frames, const Tonic_::SynthesisContext_ &context)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::Generator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Public Types inherited from Tonic::TemplatedGenerator< Tonic_::Compressor_ >
typedef Tonic_::Compressor_ gen_t
Protected Member Functions inherited from Tonic::TemplatedGenerator< Tonic_::Compressor_ >
Tonic_::Compressor_ * gen ()
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
Tonic_::Generator_ * obj
int * pcount
Detailed Description
Definition at line 191 of file CompressorLimiter.h.
Constructor & Destructor Documentation
Compressor()
Tonic::Compressor::Compressor (float threshold = 0.5, float ratio = 2, float attack = 0.001, float release = 0.05, float lookahead = 0.001)
Definition at line 46 of file CompressorLimiter.cpp.
References Tonic::TemplatedGenerator< Tonic_::Compressor_ >::gen(), Tonic::TonicSmartPointer< Tonic_::Generator_ >::release(), Tonic::Tonic_::Compressor_::setAttack(), Tonic::Tonic_::Compressor_::setLookahead(), Tonic::Tonic_::Compressor_::setRatio(), Tonic::Tonic_::Compressor_::setRelease(), and Tonic::Tonic_::Compressor_::setThreshold().
   {
     gen()->setThreshold(ControlValue(threshold));
     gen()->setRatio(ControlValue(ratio));
     gen()->setAttack(ControlValue(attack));
     gen()->setRelease(ControlValue(release));
     gen()->setLookahead(ControlValue(lookahead));
   }
Member Function Documentation
audioInput()
Compressor& Tonic::Compressor::audioInput (Generator input) inline
Input for audio to be compressed.
Definition at line 198 of file CompressorLimiter.h.
References Tonic::TemplatedGenerator< Tonic_::Compressor_ >::gen(), and Tonic::Tonic_::Compressor_::setInput().
{
       this->gen()->setInput( input );
       return *this;
     }
setIsStereo()
void Tonic::Compressor::setIsStereo (bool isStereo) inline
Definition at line 209 of file CompressorLimiter.h.
References Tonic::TemplatedGenerator< Tonic_::Compressor_ >::gen(), and Tonic::Tonic_::Compressor_::setIsStereo().
{
       this->gen()->setIsStereo(isStereo);
     }
sidechainInput()
Compressor& Tonic::Compressor::sidechainInput (Generator input) inline
Input for audio for compression amplitude envelope.
Definition at line 204 of file CompressorLimiter.h.
References Tonic::TemplatedGenerator< Tonic_::Compressor_ >::gen(), and Tonic::Tonic_::Compressor_::setAmplitudeInput().
{
       this->gen()->setAmplitudeInput(input);
       return *this;
     }
TONIC_MAKE_CTRL_GEN_SETTERS() [1/6]
Tonic::Compressor::TONIC_MAKE_CTRL_GEN_SETTERS (Compressor , attack , setAttack)
TONIC_MAKE_CTRL_GEN_SETTERS() [2/6]
Tonic::Compressor::TONIC_MAKE_CTRL_GEN_SETTERS (Compressor , release , setRelease)
TONIC_MAKE_CTRL_GEN_SETTERS() [3/6]
Tonic::Compressor::TONIC_MAKE_CTRL_GEN_SETTERS (Compressor , threshold , setThreshold)
TONIC_MAKE_CTRL_GEN_SETTERS() [4/6]
Tonic::Compressor::TONIC_MAKE_CTRL_GEN_SETTERS (Compressor , ratio , setRatio)
TONIC_MAKE_CTRL_GEN_SETTERS() [5/6]
Tonic::Compressor::TONIC_MAKE_CTRL_GEN_SETTERS (Compressor , lookahead , setLookahead)
TONIC_MAKE_CTRL_GEN_SETTERS() [6/6]
Tonic::Compressor::TONIC_MAKE_CTRL_GEN_SETTERS (Compressor , makeupGain , setMakeupGain)
The documentation for this class was generated from the following files:
CompressorLimiter.h
CompressorLimiter.cpp