YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::BPF12_ Class Reference
Tonic::Tonic_::BPF12_ Class Reference
Butterworth 2-pole BPF, constant 0dB peak.
#include <Filters.h>
Public Member Functions
virtual void setIsStereoInput (bool isStereoInput)
set stereo/mono - changes number of channels in dryFrames_
Public Member Functions inherited from Tonic::Tonic_::Filter_
Filter_ ()
virtual void setInput (Generator input)
void setNormalizesGain (bool norm)
void setCutoff (Generator cutoff)
void setQ (Generator Q)
void setBypass (ControlGenerator bypass)
Public Member Functions inherited from Tonic::Tonic_::Effect_
Effect_ ()
void setBypassCtrlGen (ControlGenerator gen)
bool isStereoInput ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
virtual void tickThrough (TonicFrames &inFrames, TonicFrames &outFrames, const SynthesisContext_ &context)
Apply effect directly to passed in frames (output in-place)
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
void applyFilter (TonicFloat cutoff, TonicFloat Q, const SynthesisContext_ &context)
Protected Member Functions inherited from Tonic::Tonic_::Filter_
void computeSynthesisBlock (const SynthesisContext_ &context)
Private Attributes
Biquad biquad_
Additional Inherited Members
Protected Attributes inherited from Tonic::Tonic_::Filter_
TonicFrames workspace_
Generator cutoff_
Generator Q_
ControlGenerator bypass_
bool bNormalizeGain_
Protected Attributes inherited from Tonic::Tonic_::Effect_
Generator input_
TonicFrames dryFrames_
ControlGenerator bypassGen_
bool isStereoInput_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Butterworth 2-pole BPF, constant 0dB peak.
Definition at line 329 of file Filters.h.
Member Function Documentation
applyFilter()
void Tonic::Tonic_::BPF12_::applyFilter (TonicFloat cutoff, TonicFloat Q, const SynthesisContext_ & context) inline protected virtual
Implements Tonic::Tonic_::Filter_.
Definition at line 338 of file Filters.h.
References biquad_, Tonic::bltCoef(), Tonic::Tonic_::Filter_::bNormalizeGain_, Tonic::Tonic_::Effect_::dryFrames_, Tonic::Biquad::filter(), Tonic::Tonic_::Generator_::outputFrames_, and Tonic::Biquad::setCoefficients().
{
         // set coefficients
         TonicFloat newCoef[5];
         bltCoef(0, bNormalizeGain_ ? 1.0f/Q : 1.0f, 0, 1.0f/Q, 1, cutoff, newCoef);
         biquad_.setCoefficients(newCoef);
         // compute
         biquad_.filter(dryFrames_, outputFrames_);
       }
setIsStereoInput()
virtual void Tonic::Tonic_::BPF12_::setIsStereoInput (bool stereo) inline virtual
set stereo/mono - changes number of channels in dryFrames_
subclasses should call in constructor to determine input channel layout
Reimplemented from Tonic::Tonic_::Effect_.
Definition at line 351 of file Filters.h.
References biquad_, Tonic::Tonic_::Effect_::isStereoInput(), Tonic::Biquad::setIsStereo(), and Tonic::Tonic_::Effect_::setIsStereoInput().
       {
         Filter_::setIsStereoInput(isStereoInput);
         biquad_.setIsStereo(isStereoInput);
       }
Member Data Documentation
biquad_
Biquad Tonic::Tonic_::BPF12_::biquad_ private
Definition at line 333 of file Filters.h.
The documentation for this class was generated from the following file:
Filters.h