YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::Adder_ Class Reference
Tonic::Tonic_::Adder_ Class Reference
#include <Arithmetic.h>
Public Member Functions
Adder_ ()
void input (Generator generator)
void setIsStereoOutput (bool stereo)
Generator getInput (unsigned int index)
unsigned int numInputs ()
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
bool isStereoOutput ()
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
vector< Generator > inputs_
TonicFrames workSpace_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 25 of file Arithmetic.h.
Constructor & Destructor Documentation
Adder_()
Tonic::Tonic_::Adder_::Adder_ ()
Definition at line 20 of file Arithmetic.cpp.
References Tonic::kSynthesisBlockSize, Tonic::TonicFrames::resize(), and workSpace_.
                 {
     workSpace_.resize(kSynthesisBlockSize, 1, 0);
   }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::Adder_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 45 of file Arithmetic.h.
References inputs_, Tonic::Tonic_::Generator_::outputFrames_, Tonic::TonicFrames::size(), and workSpace_.
{
       TonicFloat *framesData =  &outputFrames_[0];
       memset(framesData, 0, sizeof(TonicFloat) * outputFrames_.size());
       for (int j =0; j < inputs_.size(); j++) {
         inputs_[j].tick(workSpace_, context);
         outputFrames_ += workSpace_; // add each sample in frames to each sample in workspace
       }
     }
getInput()
Generator Tonic::Tonic_::Adder_::getInput (unsigned int index) inline
Definition at line 40 of file Arithmetic.h.
References inputs_.
 { return inputs_[index]; };
input()
void Tonic::Tonic_::Adder_::input (Generator generator)
Definition at line 24 of file Arithmetic.cpp.
References inputs_, Tonic::Tonic_::Generator_::isStereoOutput(), Tonic::Generator::isStereoOutput(), and setIsStereoOutput().
{
     inputs_.push_back( generator );
     if ( generator.isStereoOutput() && !this->isStereoOutput() ){
       setIsStereoOutput(true);
     }
   }
numInputs()
unsigned int Tonic::Tonic_::Adder_::numInputs () inline
Definition at line 41 of file Arithmetic.h.
References inputs_.
 { return (unsigned int)inputs_.size(); };
setIsStereoOutput()
void Tonic::Tonic_::Adder_::setIsStereoOutput (bool stereo) virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 31 of file Arithmetic.cpp.
References Tonic::kSynthesisBlockSize, Tonic::TonicFrames::resize(), Tonic::Tonic_::Generator_::setIsStereoOutput(), and workSpace_.
   {
     Generator_::setIsStereoOutput(stereo);
     workSpace_.resize(kSynthesisBlockSize, stereo ? 2 : 1, 0);
   }
Member Data Documentation
inputs_
vector<Generator> Tonic::Tonic_::Adder_::inputs_ protected
Definition at line 28 of file Arithmetic.h.
workSpace_
TonicFrames Tonic::Tonic_::Adder_::workSpace_ protected
Definition at line 29 of file Arithmetic.h.
The documentation for this class was generated from the following files:
Arithmetic.h
Arithmetic.cpp