YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::BasicDelay_ Class Reference
Tonic::Tonic_::BasicDelay_ Class Reference
#include <BasicDelay.h>
Public Member Functions
BasicDelay_ ()
~BasicDelay_ ()
void setInput (Generator input)
void initialize (float delayTime, float maxDelayTime)
void setDelayTimeGen (Generator gen)
void setFeedbackGen (Generator gen)
Public Member Functions inherited from Tonic::Tonic_::WetDryEffect_
WetDryEffect_ ()
void setDryLevelGen (Generator gen)
void setWetLevelGen (Generator gen)
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
virtual void tickThrough (TonicFrames &inFrames, TonicFrames &outFrames, const SynthesisContext_ &context)
Apply effect directly to passed in frames (output in-place)
Public Member Functions inherited from Tonic::Tonic_::Effect_
Effect_ ()
void setBypassCtrlGen (ControlGenerator gen)
virtual void setIsStereoInput (bool stereo)
set stereo/mono - changes number of channels in dryFrames_
bool isStereoInput ()
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
Generator delayTimeGen_
TonicFrames delayTimeFrames_
Generator fbkGen_
TonicFrames fbkFrames_
DelayLine delayLine_
Protected Attributes inherited from Tonic::Tonic_::WetDryEffect_
Generator dryLevelGen_
Generator wetLevelGen_
TonicFrames mixWorkspace_
Protected Attributes inherited from Tonic::Tonic_::Effect_
Generator input_
TonicFrames dryFrames_
ControlGenerator bypassGen_
bool isStereoInput_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 22 of file BasicDelay.h.
Constructor & Destructor Documentation
BasicDelay_()
Tonic::Tonic_::BasicDelay_::BasicDelay_ ()
Definition at line 13 of file BasicDelay.cpp.
References delayTimeFrames_, delayTimeGen_, fbkFrames_, fbkGen_, Tonic::kSynthesisBlockSize, Tonic::TonicFrames::resize(), Tonic::Tonic_::WetDryEffect_::setDryLevelGen(), and Tonic::Tonic_::WetDryEffect_::setWetLevelGen().
{
     delayTimeFrames_.resize(kSynthesisBlockSize, 1, 0);
     fbkFrames_.resize(kSynthesisBlockSize, 1, 0);
     delayTimeGen_ = FixedValue(0);
     fbkGen_ = FixedValue(0);
     setDryLevelGen(FixedValue(0.5));
     setWetLevelGen(FixedValue(0.5));
   }
~BasicDelay_()
Tonic::Tonic_::BasicDelay_::~BasicDelay_ ()
Definition at line 22 of file BasicDelay.cpp.
{
   }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::BasicDelay_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 52 of file BasicDelay.h.
References Tonic::DelayLine::advance(), delayLine_, delayTimeFrames_, delayTimeGen_, Tonic::Tonic_::Effect_::dryFrames_, fbkFrames_, fbkGen_, Tonic::Tonic_::Effect_::isStereoInput(), Tonic::kSynthesisBlockSize, Tonic::Tonic_::Generator_::outputFrames_, Tonic::Generator::tick(), Tonic::DelayLine::tickIn(), and Tonic::DelayLine::tickOut().
{
       delayTimeGen_.tick(delayTimeFrames_, context);
       fbkGen_.tick(fbkFrames_, context);
       // input->output always has same channel layout
       unsigned int nChannels = isStereoInput() ? 2 : 1;
       TonicFloat fbk, outSamp;
       TonicFloat *dryptr = &dryFrames_[0];
       TonicFloat *outptr = &outputFrames_[0];
       TonicFloat *fbkptr = &fbkFrames_[0];
       TonicFloat *delptr = &delayTimeFrames_[0];
       for (unsigned int i=0; i<kSynthesisBlockSize; i++){
         // Don't clamp feeback - be careful! Negative feedback could be interesting.
         fbk = *fbkptr++;
         for (unsigned int c=0; c<nChannels; c++){
           outSamp = delayLine_.tickOut(*delptr, c);
           delayLine_.tickIn(*dryptr++ + outSamp * fbk, c);
           *outptr++ = outSamp;
         }
         delptr++;
         delayLine_.advance();
       }
     }
initialize()
void Tonic::Tonic_::BasicDelay_::initialize (float delayTime, float maxDelayTime)
Definition at line 35 of file BasicDelay.cpp.
References delayLine_, delayTimeGen_, and Tonic::DelayLine::initialize().
   {
     if (maxDelayTime <= 0) maxDelayTime = delayTime * 1.5;
     delayLine_.initialize(maxDelayTime, 1);
     delayTimeGen_ = FixedValue(delayTime);
   }
setDelayTimeGen()
void Tonic::Tonic_::BasicDelay_::setDelayTimeGen (Generator gen) inline
Definition at line 46 of file BasicDelay.h.
References delayTimeGen_.
 { delayTimeGen_ = gen; };
setFeedbackGen()
void Tonic::Tonic_::BasicDelay_::setFeedbackGen (Generator gen) inline
Definition at line 48 of file BasicDelay.h.
References fbkGen_.
 { fbkGen_ = gen; };
setInput()
void Tonic::Tonic_::BasicDelay_::setInput (Generator input) virtual
Reimplemented from Tonic::Tonic_::Effect_.
Definition at line 26 of file BasicDelay.cpp.
References delayLine_, Tonic::TonicFrames::frames(), Tonic::Generator::isStereoOutput(), Tonic::TonicFrames::resize(), Tonic::Tonic_::Effect_::setInput(), Tonic::Tonic_::Effect_::setIsStereoInput(), and Tonic::Tonic_::Generator_::setIsStereoOutput().
{
     Effect_::setInput(input);
     setIsStereoInput(input.isStereoOutput());
     setIsStereoOutput(input.isStereoOutput());
     // can safely resize as TonicFrames subclass - calling functions account for channel offset
     delayLine_.resize(delayLine_.frames(), input.isStereoOutput() ? 2 : 1, 0);
   }
Member Data Documentation
delayLine_
DelayLine Tonic::Tonic_::BasicDelay_::delayLine_ protected
Definition at line 32 of file BasicDelay.h.
delayTimeFrames_
TonicFrames Tonic::Tonic_::BasicDelay_::delayTimeFrames_ protected
Definition at line 27 of file BasicDelay.h.
delayTimeGen_
Generator Tonic::Tonic_::BasicDelay_::delayTimeGen_ protected
Definition at line 26 of file BasicDelay.h.
fbkFrames_
TonicFrames Tonic::Tonic_::BasicDelay_::fbkFrames_ protected
Definition at line 30 of file BasicDelay.h.
fbkGen_
Generator Tonic::Tonic_::BasicDelay_::fbkGen_ protected
Definition at line 29 of file BasicDelay.h.
The documentation for this class was generated from the following files:
BasicDelay.h
BasicDelay.cpp