YOURPROJECTNAMEGOESHERE: Tonic::DelayLine Class Reference
Tonic::DelayLine Class Reference
Tonicframes subclass with ability to tick in and out. Allows random-access/multi-tap/etc.
#include <DelayUtils.h>
Public Member Functions
DelayLine ()
Allocation parameters are binding. No post-allocation resizing or modifying channel layout (for now anyway).
void initialize (float maxDelay=1.0f, unsigned int channels=1)
MUST be called prior to usage.
void setInterpolates (bool doesInterpolate)
Set whether interpolates or not.
void clear ()
Zero delay line.
TonicFloat tickOut (float delayTime, unsigned int channel=0)
Return one interpolated, delayed sample. Does not advance read/write head.
void tickIn (TonicFloat sample, unsigned int channel=0)
Tick one sample in (write at write head). Does not advance read/write head.
void advance ()
Advance read/write heads.
Public Member Functions inherited from Tonic::TonicFrames
TonicFrames (unsigned int nFrames=0, unsigned int nChannels=0)
The default constructor initializes the frame data structure to size zero.
TonicFrames (const TonicFloat &value, unsigned int nFrames, unsigned int nChannels)
Overloaded constructor that initializes the frame data to the specified size with value.
virtual ~TonicFrames ()
The destructor.
TonicFrames (const TonicFrames &f)
TonicFrames & operator= (const TonicFrames &f)
TonicFloat & operator[] (size_t n)
Subscript operator that returns a reference to element n of self.
TonicFloat operator[] (size_t n) const
Subscript operator that returns the value at element n of self.
void operator+= (TonicFrames &f)
Assignment by sum operator into self.
void operator-= (TonicFrames &f)
void operator*= (TonicFrames &f)
Assignment by product operator into self.
void operator/= (TonicFrames &f)
TonicFloat & operator() (size_t frame, unsigned int channel)
Channel / frame subscript operator that returns a reference.
TonicFloat operator() (size_t frame, unsigned int channel) const
Channel / frame subscript operator that returns a value.
void copyChannel (unsigned int src, unsigned int dst)
Copy one channel to another.
void fillChannels ()
Fill all channels with contents of channel 0.
void clear ()
clear the frames data
void copy (TonicFrames &f)
Fill frames from other source.
TonicFloat interpolate (TonicFloat frame, unsigned int channel=0) const
Return an interpolated value at the fractional frame index and channel.
size_t size () const
Returns the total number of audio samples represented by the object.
bool empty () const
Returns true if the object size is zero and false otherwise.
void resize (size_t nFrames, unsigned int nChannels=1)
Resize self to represent the specified number of channels and frames.
void resize (size_t nFrames, unsigned int nChannels, TonicFloat value)
Resize self to represent the specified number of channels and frames and perform element initialization.
void resample (size_t nFrames, unsigned int nChannels)
Resize and stretch/shrink existing data to fit new size.
unsigned int channels (void) const
Return the number of channels represented by the data.
unsigned long frames (void) const
Return the number of sample frames represented by the data.
void setDataRate (TonicFloat rate)
Set the sample rate associated with the TonicFrames data.
TonicFloat dataRate (void) const
Return the sample rate associated with the TonicFrames data.
Private Attributes
bool isInitialized_
bool interpolates_
long writeHead_
float readHead_
float lastDelayTime_
Additional Inherited Members
Protected Attributes inherited from Tonic::TonicFrames
TonicFloat * data_
TonicFloat dataRate_
size_t nFrames_
unsigned int nChannels_
size_t size_
size_t bufferSize_
Detailed Description
Tonicframes subclass with ability to tick in and out. Allows random-access/multi-tap/etc.
Definition at line 19 of file DelayUtils.h.
Constructor & Destructor Documentation
DelayLine()
Tonic::DelayLine::DelayLine ()
Allocation parameters are binding. No post-allocation resizing or modifying channel layout (for now anyway).
Samples are interleaved if allocated with multiple channels.
Definition at line 13 of file DelayUtils.cpp.
References Tonic::kSynthesisBlockSize, and Tonic::TonicFrames::resize().
                        :
     lastDelayTime_(0),
     readHead_(0),
     writeHead_(0),
     isInitialized_(false),
     interpolates_(true)
   {
     resize(kSynthesisBlockSize, 1, 0);
   }
Member Function Documentation
advance()
void Tonic::DelayLine::advance () inline
Advance read/write heads.
Definition at line 96 of file DelayUtils.h.
References Tonic::TonicFrames::nFrames_, readHead_, and writeHead_.
{
       if (++writeHead_ >= nFrames_)
         writeHead_ = 0;
       // assume read head advances by 1 for efficiency in constant-delay lines
       readHead_ += 1.0f;
       if (readHead_ >= nFrames_){
         readHead_ -= (float)nFrames_;
       }
     }
clear()
void Tonic::DelayLine::clear ()
Zero delay line.
Definition at line 30 of file DelayUtils.cpp.
References Tonic::TonicFrames::data_, isInitialized_, and Tonic::TonicFrames::size_.
   {
     if (isInitialized_){
       memset(data_, 0, size_ * sizeof(TonicFloat));
     }
   }
initialize()
void Tonic::DelayLine::initialize (float maxDelay = 1.0f, unsigned int channels = 1)
MUST be called prior to usage.
Definition at line 23 of file DelayUtils.cpp.
References Tonic::TonicFrames::channels(), isInitialized_, Tonic::max(), Tonic::TonicFrames::resize(), and Tonic::sampleRate().
   {
     unsigned int nFrames = max(2, maxDelay * Tonic::sampleRate());
     resize(nFrames, channels, 0);
     isInitialized_ = true;
   }
setInterpolates()
void Tonic::DelayLine::setInterpolates (bool doesInterpolate) inline
Set whether interpolates or not.
Definition at line 42 of file DelayUtils.h.
References interpolates_.
 { interpolates_ = doesInterpolate; };
tickIn()
void Tonic::DelayLine::tickIn (TonicFloat sample, unsigned int channel = 0) inline
Tick one sample in (write at write head). Does not advance read/write head.
NOTE: No bounds checking on channel index. Improper use will result in access outside array bounds.
Definition at line 90 of file DelayUtils.h.
References Tonic::TonicFrames::data_, Tonic::TonicFrames::nChannels_, and writeHead_.
{
       data_[writeHead_*nChannels_+channel] = sample;
     }
tickOut()
TonicFloat Tonic::DelayLine::tickOut (float delayTime, unsigned int channel = 0) inline
Return one interpolated, delayed sample. Does not advance read/write head.
NOTE: No bounds checking on channel index. Improper use will result in access outside array bounds.
Definition at line 57 of file DelayUtils.h.
References Tonic::clamp(), Tonic::TonicFrames::data_, interpolates_, lastDelayTime_, Tonic::TonicFrames::nChannels_, Tonic::TonicFrames::nFrames_, readHead_, Tonic::sampleRate(), Tonic::TonicFrames::size_, and writeHead_.
{
       if (delayTime != lastDelayTime_){
         float dSamp = clamp(delayTime * Tonic::sampleRate(), 0, nFrames_);
         readHead_ = (float)writeHead_ - dSamp;
         if (readHead_ < 0) {
           readHead_ += (float)nFrames_;
         }
         lastDelayTime_ = delayTime;
       }
       if (interpolates_){
         // Fractional and integral part of read head
         float fidx;
         float frac = modff(readHead_, &fidx);
         int idx_a = ((int)fidx * nChannels_ + channel);
         if (idx_a >= size_) idx_a -= size_; // this happens occasionally due to floating point rounding
         int idx_b = idx_a + nChannels_;
         if (idx_b >= size_) idx_b -= size_;
         // Linear interpolation
         return (data_[idx_a] + frac * (data_[idx_b] - data_[idx_a]));
       }
       else{
         return (data_[((int)(readHead_))*nChannels_ + channel]);
       }
     }
Member Data Documentation
interpolates_
bool Tonic::DelayLine::interpolates_ private
Definition at line 24 of file DelayUtils.h.
isInitialized_
bool Tonic::DelayLine::isInitialized_ private
Definition at line 23 of file DelayUtils.h.
lastDelayTime_
float Tonic::DelayLine::lastDelayTime_ private
Definition at line 28 of file DelayUtils.h.
readHead_
float Tonic::DelayLine::readHead_ private
Definition at line 27 of file DelayUtils.h.
writeHead_
long Tonic::DelayLine::writeHead_ private
Definition at line 26 of file DelayUtils.h.
The documentation for this class was generated from the following files:
DelayUtils.h
DelayUtils.cpp