YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::Multiplier_ Class Reference
Tonic::Tonic_::Multiplier_ Class Reference
#include <Arithmetic.h>
Public Member Functions
Multiplier_ ()
void input (Generator generator)
void setIsStereoOutput (bool stereo)
Generator getInput (unsigned int index)
unsigned int numInputs ()
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
bool isStereoOutput ()
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
vector< Generator > inputs_
TonicFrames workSpace_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 205 of file Arithmetic.h.
Constructor & Destructor Documentation
Multiplier_()
Tonic::Tonic_::Multiplier_::Multiplier_ ()
Definition at line 73 of file Arithmetic.cpp.
References Tonic::kSynthesisBlockSize, Tonic::TonicFrames::resize(), and workSpace_.
{
     workSpace_.resize(kSynthesisBlockSize, 1, 0);
   }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::Multiplier_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 226 of file Arithmetic.h.
References inputs_, Tonic::Tonic_::Generator_::outputFrames_, Tonic::TonicFrames::size(), and workSpace_.
{
       memset(&outputFrames_[0], 0, sizeof(TonicFloat) * outputFrames_.size());
       // for the first generator, store the value in the block
       inputs_[0].tick(outputFrames_, context);
       // for additional generators, use the workspace stkframes for tick, and multiply it into the frames argument
       for(int i = 1; i < inputs_.size(); i++) {
         inputs_[i].tick(workSpace_, context);
         outputFrames_ *= workSpace_;
       }
     }
getInput()
Generator Tonic::Tonic_::Multiplier_::getInput (unsigned int index) inline
Definition at line 220 of file Arithmetic.h.
References inputs_.
 { return inputs_[index]; };
input()
void Tonic::Tonic_::Multiplier_::input (Generator generator)
Definition at line 77 of file Arithmetic.cpp.
References inputs_, Tonic::Tonic_::Generator_::isStereoOutput(), Tonic::Generator::isStereoOutput(), and setIsStereoOutput().
{
     inputs_.push_back(generator);
     if ( generator.isStereoOutput() && !isStereoOutput() ){
       setIsStereoOutput(true);
     }
   }
numInputs()
unsigned int Tonic::Tonic_::Multiplier_::numInputs () inline
Definition at line 221 of file Arithmetic.h.
References inputs_.
 { return (unsigned int)inputs_.size(); };
setIsStereoOutput()
void Tonic::Tonic_::Multiplier_::setIsStereoOutput (bool stereo) virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 84 of file Arithmetic.cpp.
References Tonic::kSynthesisBlockSize, Tonic::TonicFrames::resize(), Tonic::Tonic_::Generator_::setIsStereoOutput(), and workSpace_.
   {
     Generator_::setIsStereoOutput(stereo);
     workSpace_.resize(kSynthesisBlockSize, stereo ? 2 : 1, 0);
   }
Member Data Documentation
inputs_
vector<Generator> Tonic::Tonic_::Multiplier_::inputs_ protected
Definition at line 208 of file Arithmetic.h.
workSpace_
TonicFrames Tonic::Tonic_::Multiplier_::workSpace_ protected
Definition at line 209 of file Arithmetic.h.
The documentation for this class was generated from the following files:
Arithmetic.h
Arithmetic.cpp