YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::AngularWave_ Class Reference
Tonic::Tonic_::AngularWave_ Class Reference
#include <SawtoothWave.h>
Public Member Functions
AngularWave_ ()
void setFrequencyGenerator (Generator gen)
void setSlopeGenerator (Generator gen)
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
Generator freqGen_
Generator slopeGen_
TonicFrames freqFrames_
TonicFrames slopeFrames_
double phaseAccum_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 26 of file SawtoothWave.h.
Constructor & Destructor Documentation
AngularWave_()
Tonic::Tonic_::AngularWave_::AngularWave_ ()
Definition at line 13 of file SawtoothWave.cpp.
References freqFrames_, freqGen_, Tonic::kSynthesisBlockSize, Tonic::TonicFrames::resize(), slopeFrames_, and slopeGen_.
                              : phaseAccum_(0) {
     freqFrames_.resize(kSynthesisBlockSize, 1, 0);
     slopeFrames_.resize(kSynthesisBlockSize, 1, 0);
     slopeGen_ = FixedValue(0);
     freqGen_ = FixedValue(440);
   }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::AngularWave_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 54 of file SawtoothWave.h.
References BIT32DECPT, Tonic::clamp(), Tonic::FastPhasor::d, Tonic::TonicFrames::frames(), freqFrames_, freqGen_, Tonic::FastPhasor::i, Tonic::kSynthesisBlockSize, Tonic::Tonic_::Generator_::outputFrames_, phaseAccum_, Tonic::sampleRate(), slopeFrames_, slopeGen_, Tonic::Generator::tick(), and TONIC_SAW_RES.
{
       // tick freq and slope inputs
       freqGen_.tick(freqFrames_, context);
       slopeGen_.tick(slopeFrames_, context);
       // calculate the output wave
       TonicFloat const rateConstant = TONIC_SAW_RES/Tonic::sampleRate();
       TonicFloat slope, frac, phase;
       TonicFloat *outptr = &outputFrames_[0];
       TonicFloat *freqptr = &freqFrames_[0];
       TonicFloat *slopeptr = &slopeFrames_[0];
       FastPhasor sd;
       // pre-multiply rate constant for speed
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vsmul(freqptr, 1, &rateConstant, freqptr, 1, kSynthesisBlockSize);
 #else
       for (unsigned int i=0; i<kSynthesisBlockSize; i++){
         *freqptr++ *= rateConstant;
       }
       freqptr = &freqFrames_[0];
 #endif
       sd.d = BIT32DECPT;
       TonicInt32 offs, msbi = sd.i[1];
       double ps = phaseAccum_ + BIT32DECPT;
       for ( unsigned int i=0; i<outputFrames_.frames(); i++ ) {
         // update the slope
         slope = clamp(*slopeptr++, 0.0f, 1.0f) * TONIC_SAW_RES;
         sd.d = ps;
         ps += *freqptr++;
         offs = sd.i[1] & (TONIC_SAW_RES-1);
         sd.i[1] = msbi;
         frac = sd.d - BIT32DECPT;
         phase = offs + frac;
         // TODO: this is still a bit slow. Maybe find a way to do it with a real table lookup
         // on the rising edge
         if (phase < slope){
           *outptr++ = (phase/slope)*2.0f - 1.0f;
         }
         // on the falling edge
         else{
           *outptr++ = (1.0f - ((phase - slope)/(TONIC_SAW_RES - slope))) * 2.0f - 1.0f;
         }
       }
       sd.d = BIT32DECPT * TONIC_SAW_RES;
       msbi = sd.i[1];
       sd.d = ps + (BIT32DECPT * TONIC_SAW_RES - BIT32DECPT);
       sd.i[1] = msbi;
       phaseAccum_ = sd.d - BIT32DECPT * TONIC_SAW_RES;
     }
setFrequencyGenerator()
void Tonic::Tonic_::AngularWave_::setFrequencyGenerator (Generator gen) inline
Definition at line 43 of file SawtoothWave.h.
References freqGen_.
{
         freqGen_ = gen;
       }
setSlopeGenerator()
void Tonic::Tonic_::AngularWave_::setSlopeGenerator (Generator gen) inline
Definition at line 47 of file SawtoothWave.h.
References slopeGen_.
{
         slopeGen_ = gen;
       }
Member Data Documentation
freqFrames_
TonicFrames Tonic::Tonic_::AngularWave_::freqFrames_ protected
Definition at line 33 of file SawtoothWave.h.
freqGen_
Generator Tonic::Tonic_::AngularWave_::freqGen_ protected
Definition at line 30 of file SawtoothWave.h.
phaseAccum_
double Tonic::Tonic_::AngularWave_::phaseAccum_ protected
Definition at line 36 of file SawtoothWave.h.
slopeFrames_
TonicFrames Tonic::Tonic_::AngularWave_::slopeFrames_ protected
Definition at line 34 of file SawtoothWave.h.
slopeGen_
Generator Tonic::Tonic_::AngularWave_::slopeGen_ protected
Definition at line 31 of file SawtoothWave.h.
The documentation for this class was generated from the following files:
SawtoothWave.h
SawtoothWave.cpp