YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::SampleTable_ Class Reference
Tonic::Tonic_::SampleTable_ Class Reference
#include <SampleTable.h>
Public Member Functions
SampleTable_ (unsigned int frames, unsigned int channels)
unsigned int channels () const
unsigned long frames () const
size_t size () const
TonicFloat * dataPointer ()
void resize (unsigned int frames, unsigned int channels)
void resample (unsigned int frames, unsigned int channels)
Protected Attributes
TonicFrames frames_
Detailed Description
Definition at line 25 of file SampleTable.h.
Constructor & Destructor Documentation
SampleTable_()
Tonic::Tonic_::SampleTable_::SampleTable_ (unsigned int frames, unsigned int channels)
Definition at line 14 of file SampleTable.cpp.
References channels(), frames(), frames_, Tonic::min(), and Tonic::TonicFrames::resize().
{
       frames_.resize(frames, min(channels, 2)); // limited to 2 channels
     }
Member Function Documentation
channels()
unsigned int Tonic::Tonic_::SampleTable_::channels () const inline
Definition at line 35 of file SampleTable.h.
References Tonic::TonicFrames::channels(), and frames_.
{
         return frames_.channels();
       }
dataPointer()
TonicFloat* Tonic::Tonic_::SampleTable_::dataPointer () inline
Definition at line 48 of file SampleTable.h.
References frames_.
{
         return &frames_[0];
       }
frames()
unsigned long Tonic::Tonic_::SampleTable_::frames () const inline
Definition at line 39 of file SampleTable.h.
References Tonic::TonicFrames::frames(), and frames_.
{
         return frames_.frames();
       }
resample()
void Tonic::Tonic_::SampleTable_::resample (unsigned int frames, unsigned int channels) inline
Definition at line 58 of file SampleTable.h.
References channels(), frames(), frames_, and Tonic::TonicFrames::resample().
{
         frames_.resample(frames, channels);
       }
resize()
void Tonic::Tonic_::SampleTable_::resize (unsigned int frames, unsigned int channels) inline
Definition at line 53 of file SampleTable.h.
References channels(), frames(), frames_, and Tonic::TonicFrames::resize().
{
         frames_.resize(frames, channels);
       }
size()
size_t Tonic::Tonic_::SampleTable_::size () const inline
Definition at line 43 of file SampleTable.h.
References frames_, and Tonic::TonicFrames::size().
{
         return frames_.size();
       }
Member Data Documentation
frames_
TonicFrames Tonic::Tonic_::SampleTable_::frames_ protected
Definition at line 28 of file SampleTable.h.
The documentation for this class was generated from the following files:
SampleTable.h
SampleTable.cpp