YOURPROJECTNAMEGOESHERE: Tonic::Limiter Class Reference
Tonic::Limiter Class Reference
Special case of compressor where ratio is fixed to infinite and attack time is fixed to 0.1 ms.
#include <CompressorLimiter.h>
Public Member Functions
Limiter ()
void setIsStereo (bool isStereo)
TONIC_MAKE_CTRL_GEN_SETTERS (Limiter, release, setRelease)
TONIC_MAKE_CTRL_GEN_SETTERS (Limiter, threshold, setThreshold)
TONIC_MAKE_CTRL_GEN_SETTERS (Limiter, lookahead, setLookahead)
TONIC_MAKE_CTRL_GEN_SETTERS (Limiter, makeupGain, setMakeupGain)
Public Member Functions inherited from Tonic::TemplatedEffect< Limiter, Tonic_::Compressor_ >
virtual Limiter & input (Generator input)
void tickThrough (TonicFrames &inFrames, const Tonic_::SynthesisContext_ &context)
void tickThrough (TonicFrames &inFrames, TonicFrames &outFrames, const Tonic_::SynthesisContext_ &context)
void setIsStereoInput (bool isStereoInput)
TONIC_MAKE_CTRL_GEN_SETTERS (Limiter, bypass, setBypassCtrlGen)
Public Member Functions inherited from Tonic::TemplatedGenerator< Tonic_::Compressor_ >
TemplatedGenerator ()
Public Member Functions inherited from Tonic::Generator
Generator (Tonic_::Generator_ *gen=new Tonic_::Generator_)
bool isStereoOutput ()
virtual void tick (TonicFrames &frames, const Tonic_::SynthesisContext_ &context)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::Generator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Public Types inherited from Tonic::TemplatedGenerator< Tonic_::Compressor_ >
typedef Tonic_::Compressor_ gen_t
Protected Member Functions inherited from Tonic::TemplatedGenerator< Tonic_::Compressor_ >
Tonic_::Compressor_ * gen ()
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
Tonic_::Generator_ * obj
int * pcount
Detailed Description
Special case of compressor where ratio is fixed to infinite and attack time is fixed to 0.1 ms.
Definition at line 227 of file CompressorLimiter.h.
Constructor & Destructor Documentation
Limiter()
Tonic::Limiter::Limiter ()
Definition at line 58 of file CompressorLimiter.cpp.
References Tonic::dBToLin(), Tonic::TemplatedGenerator< Tonic_::Compressor_ >::gen(), Tonic::Tonic_::Compressor_::setAttack(), Tonic::Tonic_::Compressor_::setIsLimiter(), Tonic::Tonic_::Compressor_::setLookahead(), Tonic::Tonic_::Compressor_::setRatio(), Tonic::Tonic_::Compressor_::setRelease(), and Tonic::Tonic_::Compressor_::setThreshold().
                   {
     gen()->setIsLimiter(true);
     gen()->setAttack(ControlValue(0.0001));
     gen()->setLookahead(ControlValue(0.003));
     gen()->setRelease(ControlValue(0.080));
     gen()->setThreshold(ControlValue(dBToLin(-0.1)));
     gen()->setRatio(ControlValue(std::numeric_limits<float>::infinity()));
   }
Member Function Documentation
setIsStereo()
void Tonic::Limiter::setIsStereo (bool isStereo) inline
Definition at line 233 of file CompressorLimiter.h.
References Tonic::TemplatedGenerator< Tonic_::Compressor_ >::gen(), and Tonic::Tonic_::Compressor_::setIsStereo().
{
       this->gen()->setIsStereo(isStereo);
     }
TONIC_MAKE_CTRL_GEN_SETTERS() [1/4]
Tonic::Limiter::TONIC_MAKE_CTRL_GEN_SETTERS (Limiter , release , setRelease)
TONIC_MAKE_CTRL_GEN_SETTERS() [2/4]
Tonic::Limiter::TONIC_MAKE_CTRL_GEN_SETTERS (Limiter , threshold , setThreshold)
TONIC_MAKE_CTRL_GEN_SETTERS() [3/4]
Tonic::Limiter::TONIC_MAKE_CTRL_GEN_SETTERS (Limiter , lookahead , setLookahead)
TONIC_MAKE_CTRL_GEN_SETTERS() [4/4]
Tonic::Limiter::TONIC_MAKE_CTRL_GEN_SETTERS (Limiter , makeupGain , setMakeupGain)
The documentation for this class was generated from the following files:
CompressorLimiter.h
CompressorLimiter.cpp