YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::RingBuffer_ Class Reference
Tonic::Tonic_::RingBuffer_ Class Reference
#include <RingBuffer.h>
Public Member Functions
RingBuffer_ (unsigned int frames, unsigned int channels)
void write (float *data, unsigned int nFrames, unsigned int nChannels)
void read (TonicFrames &outFrames)
void reset ()
Public Member Functions inherited from Tonic::Tonic_::SampleTable_
SampleTable_ (unsigned int frames, unsigned int channels)
unsigned int channels () const
unsigned long frames () const
size_t size () const
TonicFloat * dataPointer ()
void resize (unsigned int frames, unsigned int channels)
void resample (unsigned int frames, unsigned int channels)
Private Attributes
unsigned long readHead_
unsigned long writeHead_
Additional Inherited Members
Protected Attributes inherited from Tonic::Tonic_::SampleTable_
TonicFrames frames_
Detailed Description
Definition at line 21 of file RingBuffer.h.
Constructor & Destructor Documentation
RingBuffer_()
Tonic::Tonic_::RingBuffer_::RingBuffer_ (unsigned int frames, unsigned int channels)
Definition at line 17 of file RingBuffer.cpp.
                                                                        :
       SampleTable_(frames, channels),
       writeHead_(0),
       readHead_(0)
     {}
Member Function Documentation
read()
void Tonic::Tonic_::RingBuffer_::read (TonicFrames & outFrames) inline
Definition at line 93 of file RingBuffer.h.
References Tonic::Tonic_::SampleTable_::channels(), Tonic::TonicFrames::channels(), Tonic::Tonic_::SampleTable_::frames(), Tonic::TonicFrames::frames(), Tonic::Tonic_::SampleTable_::frames_, readHead_, Tonic::warning(), and writeHead_.
{
 #ifdef TONIC_DEBUG
       // Detect underrun
       unsigned long finalReadHead = (readHead_ + outFrames.frames()) % frames();
       if (finalReadHead > writeHead_ && (readHead_ < writeHead_ || finalReadHead < readHead_)){
         warning("RingBuffer underrun detected");
       }
 #endif
       TonicFloat *readptr = &frames_(readHead_, 0);
       TonicFloat *outptr = &outFrames[0];
       unsigned long nFrames = outFrames.frames();
       unsigned int nChannels = outFrames.channels();
       unsigned long bufFrames = frames();
       unsigned int bufChannels = channels();
       if (bufChannels == nChannels){
         for (unsigned int i=0; i<nFrames; i++){
           for (unsigned int c=0; c<nChannels; c++){
             *outptr++ = *readptr++;
           }
           if (++readHead_ >= bufFrames){
             readHead_ = 0;
             readptr = &frames_[0];
           }
         }
       }
       else if (bufChannels > nChannels){
         for (unsigned int i=0; i<nFrames; i++){
           *outptr = 0;
           for (unsigned int c=0; c<bufChannels; c++){
             *outptr += *readptr++;
           }
           *outptr /= (float)bufChannels;
           outptr++;
           if (++readHead_ >= bufFrames){
             readHead_ = 0;
             readptr = &frames_[0];
           }
         }
       }
       else {
         for (unsigned int i=0; i<nFrames; i++){
           for (unsigned int c=0; c<nChannels; c++){
             *outptr++ = *readptr;
           }
           readptr++;
           if (++readHead_ >= bufFrames){
             readHead_ = 0;
             readptr = &frames_[0];
           }
         }
       }
     }
reset()
void Tonic::Tonic_::RingBuffer_::reset () inline
Definition at line 154 of file RingBuffer.h.
References readHead_, and writeHead_.
{
       readHead_ = 0;
       writeHead_ = 0;
     }
write()
void Tonic::Tonic_::RingBuffer_::write (float * data, unsigned int nFrames, unsigned int nChannels) inline
Definition at line 37 of file RingBuffer.h.
References Tonic::Tonic_::SampleTable_::channels(), Tonic::Tonic_::SampleTable_::frames(), Tonic::Tonic_::SampleTable_::frames_, readHead_, Tonic::warning(), and writeHead_.
{
 #ifdef TONIC_DEBUG
       // Detect overrun
       unsigned long finalWriteHead = (writeHead_ + nFrames) % frames();
       if (finalWriteHead >= readHead_ && (writeHead_ < readHead_ || finalWriteHead < writeHead_)){
         warning("RingBuffer overrun detected");
       }
 #endif
       TonicFloat *writeptr = &frames_(writeHead_, 0);
       unsigned int bufChannels = channels();
       unsigned long bufFrames = frames();
       if (bufChannels == nChannels){
         for (unsigned int i=0; i<nFrames; i++){
           for (unsigned int c=0; c<nChannels; c++){
             *writeptr++ = *data++;
           }
           if (++writeHead_ >= bufFrames){
             writeHead_ = 0;
             writeptr = &frames_[0];
           }
         }
       }
       else if (bufChannels > nChannels){
         for (unsigned int i=0; i<nFrames; i++){
           for (unsigned int c=0; c<bufChannels; c++){
             *writeptr++ = *data;
           }
           data++;
           if (++writeHead_ >= bufFrames){
             writeHead_ = 0;
             writeptr = &frames_[0];
           }
         }
       }
       else {
         for (unsigned int i=0; i<nFrames; i++){
           *writeptr = 0;
           for (unsigned int c=0; c<nChannels; c++){
             *writeptr += *data++;
           }
           *writeptr++ /= (float)nChannels;
           if (++writeHead_ >= bufFrames){
             writeHead_ = 0;
             writeptr = &frames_[0];
           }
         }
       }
     }
Member Data Documentation
readHead_
unsigned long Tonic::Tonic_::RingBuffer_::readHead_ private
Definition at line 25 of file RingBuffer.h.
writeHead_
unsigned long Tonic::Tonic_::RingBuffer_::writeHead_ private
Definition at line 26 of file RingBuffer.h.
The documentation for this class was generated from the following files:
RingBuffer.h
RingBuffer.cpp