YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::Reverb_ Class Reference
Tonic::Tonic_::Reverb_ Class Reference
Moorer-Schroeder style Artificial Reverb effect.
#include <Reverb.h>
Public Member Functions
Reverb_ ()
void setPreDelayTimeCtrlGen (ControlGenerator gen)
void setInputFiltBypassCtrlGen (ControlGenerator gen)
void setInputLPFCutoffCtrlGen (ControlGenerator gen)
void setInputHPFCutoffCtrlGen (ControlGenerator gen)
void setRoomSizeCtrlGen (ControlGenerator gen)
void setRoomShapeCtrlGen (ControlGenerator gen)
void setDensityCtrlGen (ControlGenerator gen)
void setDecayTimeCtrlGen (ControlGenerator gen)
void setStereoWidthCtrlGen (ControlGenerator gen)
void setDecayLPFCtrlGen (ControlGenerator gen)
void setDecayHPFCtrlGen (ControlGenerator gen)
Public Member Functions inherited from Tonic::Tonic_::WetDryEffect_
WetDryEffect_ ()
void setDryLevelGen (Generator gen)
void setWetLevelGen (Generator gen)
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
virtual void tickThrough (TonicFrames &inFrames, TonicFrames &outFrames, const SynthesisContext_ &context)
Apply effect directly to passed in frames (output in-place)
Public Member Functions inherited from Tonic::Tonic_::Effect_
Effect_ ()
void setBypassCtrlGen (ControlGenerator gen)
virtual void setInput (Generator input)
virtual void setIsStereoInput (bool stereo)
set stereo/mono - changes number of channels in dryFrames_
bool isStereoInput ()
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
void updateDelayTimes (const SynthesisContext_ &context)
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
DelayLine preDelayLine_
DelayLine reflectDelayLine_
LPF12 inputLPF_
HPF12 inputHPF_
vector< TonicFloat > reflectTapTimes_
vector< TonicFloat > reflectTapScale_
vector< FilteredFBCombFilter6 > combFilters_ [2]
vector< ControlValue > combFilterDelayTimes_ [2]
vector< ControlValue > combFilterScaleFactors_ [2]
vector< ImpulseDiffuserAllpass > allpassFilters_ [2]
TonicFrames workspaceFrames_ [2]
TonicFrames preOutputFrames_ [2]
ControlGenerator preDelayTimeCtrlGen_
ControlGenerator inputFiltBypasCtrlGen_
ControlGenerator roomSizeCtrlGen_
ControlGenerator roomShapeCtrlGen_
ControlGenerator densityCtrlGen_
ControlGenerator decayTimeCtrlGen_
ControlGenerator stereoWidthCtrlGen_
Protected Attributes inherited from Tonic::Tonic_::WetDryEffect_
Generator dryLevelGen_
Generator wetLevelGen_
TonicFrames mixWorkspace_
Protected Attributes inherited from Tonic::Tonic_::Effect_
Generator input_
TonicFrames dryFrames_
ControlGenerator bypassGen_
bool isStereoInput_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Moorer-Schroeder style Artificial Reverb effect.
Pre-delay
Input filter
Early reflection taps
Decay time and decay filtering
Variable "Room size"
Variable stereo width
TODO:
Reverb fb comb cutoff setting parameters should be normalized value, not Hz. Not a "true" cutoff.
Highpass portion of fb comb filter is too wide. Should be LPF24.
More deterministic early reflection time scattering.
Definition at line 80 of file Reverb.h.
Constructor & Destructor Documentation
Reverb_()
Tonic::Tonic_::Reverb_::Reverb_ ()
Definition at line 59 of file Reverb.cpp.
References allpassFilters_, Tonic::Tonic_::allpassTimes_, combFilterDelayTimes_, combFilters_, combFilterScaleFactors_, decayTimeCtrlGen_, densityCtrlGen_, Tonic::DelayLine::initialize(), inputFiltBypasCtrlGen_, inputHPF_, inputLPF_, Tonic::kSynthesisBlockSize, preDelayLine_, preDelayTimeCtrlGen_, preOutputFrames_, reflectDelayLine_, Tonic::TonicFrames::resize(), roomShapeCtrlGen_, roomSizeCtrlGen_, setDecayHPFCtrlGen(), setDecayLPFCtrlGen(), Tonic::Tonic_::WetDryEffect_::setDryLevelGen(), setInputHPFCutoffCtrlGen(), setInputLPFCutoffCtrlGen(), Tonic::TemplatedEffect< EffectType, EffectType_ >::setIsStereoInput(), Tonic::Tonic_::Generator_::setIsStereoOutput(), Tonic::Tonic_::WetDryEffect_::setWetLevelGen(), stereoWidthCtrlGen_, TONIC_LEFT, TONIC_REVERB_ALLPASS_COEF, TONIC_REVERB_N_ALLPASS, TONIC_REVERB_N_COMBS, TONIC_REVERB_STEREO_SPREAD, TONIC_RIGHT, and workspaceFrames_.
                   {
     setIsStereoOutput(true);
     // Default to 50% wet
     setDryLevelGen(FixedValue(0.5f));
     setWetLevelGen(FixedValue(0.5f));
     workspaceFrames_[0].resize(kSynthesisBlockSize, 1, 0);
     workspaceFrames_[1].resize(kSynthesisBlockSize, 1, 0);
     preOutputFrames_[0].resize(kSynthesisBlockSize, 1, 0);
     preOutputFrames_[1].resize(kSynthesisBlockSize, 1, 0);
     preDelayLine_.initialize(0.1f, 1);
     reflectDelayLine_.initialize(0.1f, 1);
     inputLPF_.setIsStereoInput(false);
     inputLPF_.setIsStereoInput(false);
     inputLPF_.Q(0.707);
     inputHPF_.Q(0.707);
     preDelayTimeCtrlGen_ = ControlValue(0.01f);
     inputFiltBypasCtrlGen_ = ControlValue(false);
     densityCtrlGen_ = ControlValue(0.5);
     roomShapeCtrlGen_ = ControlValue(0.5);
     roomSizeCtrlGen_ = ControlValue(0.5);
     decayTimeCtrlGen_ = ControlValue(1.0f);
     stereoWidthCtrlGen_ = ControlValue(0.5f);
     setInputLPFCutoffCtrlGen(ControlValue(10000.0f));
     setInputHPFCutoffCtrlGen(ControlValue(20.f));
     for (unsigned int i=0; i<TONIC_REVERB_N_COMBS; i++){
       ControlValue delayL = ControlValue(0.01f);
       ControlValue delayR = ControlValue(0.01f);
       ControlValue scaleL = ControlValue(0.5);
       ControlValue scaleR = ControlValue(0.5);
       combFilterDelayTimes_[TONIC_LEFT].push_back(delayL);
       combFilterDelayTimes_[TONIC_RIGHT].push_back(delayR);
       combFilterScaleFactors_[TONIC_LEFT].push_back(scaleL);
       combFilterScaleFactors_[TONIC_RIGHT].push_back(scaleR);
       combFilters_[TONIC_LEFT].push_back(FilteredFBCombFilter6(0.01f, 0.125f).delayTime(delayL).scaleFactor(scaleL));
       combFilters_[TONIC_RIGHT].push_back(FilteredFBCombFilter6(0.01f, 0.125f).delayTime(delayR).scaleFactor(scaleR));
     }
     for (unsigned int i=0; i<TONIC_REVERB_N_ALLPASS; i++){
       allpassFilters_[TONIC_LEFT].push_back(ImpulseDiffuserAllpass(allpassTimes_[i], TONIC_REVERB_ALLPASS_COEF));
       allpassFilters_[TONIC_RIGHT].push_back(ImpulseDiffuserAllpass(allpassTimes_[i] + TONIC_REVERB_STEREO_SPREAD, TONIC_REVERB_ALLPASS_COEF));
     }
     setDecayLPFCtrlGen(ControlValue(12000.f));
     setDecayHPFCtrlGen(ControlValue(60.f));
   }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::Reverb_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 140 of file Reverb.h.
References Tonic::DelayLine::advance(), allpassFilters_, Tonic::clamp(), Tonic::TonicFrames::clear(), combFilters_, Tonic::TonicFrames::copy(), Tonic::Tonic_::Effect_::dryFrames_, inputFiltBypasCtrlGen_, inputHPF_, inputLPF_, Tonic::kSynthesisBlockSize, Tonic::Tonic_::Generator_::outputFrames_, preDelayLine_, preDelayTimeCtrlGen_, preOutputFrames_, reflectDelayLine_, reflectTapScale_, reflectTapTimes_, stereoWidthCtrlGen_, Tonic::ControlGenerator::tick(), Tonic::DelayLine::tickIn(), Tonic::DelayLine::tickOut(), Tonic::TemplatedEffect< EffectType, EffectType_ >::tickThrough(), TONIC_LEFT, TONIC_RIGHT, updateDelayTimes(), Tonic::ControlGeneratorOutput::value, and workspaceFrames_.
{
       updateDelayTimes(context);
       // pass thru input filters
       if (inputFiltBypasCtrlGen_.tick(context).value == 0.f){
         inputLPF_.tickThrough(dryFrames_, workspaceFrames_[0], context);
         inputHPF_.tickThrough(workspaceFrames_[0], workspaceFrames_[0], context);
       }
       else{
         workspaceFrames_[0].copy(dryFrames_);
       }
       TonicFloat *wkptr0 = &(workspaceFrames_[0])[0];
       TonicFloat *wkptr1 = &(workspaceFrames_[1])[0];
       // pass thru pre-delay, input filters, and sum the early reflections
       TonicFloat preDelayTime = preDelayTimeCtrlGen_.tick(context).value;
       for (unsigned int i=0; i<kSynthesisBlockSize; i++){
         // filtered input is in w0
         // predelay output is in w1
         // pre-delay
         preDelayLine_.tickIn(*wkptr0);
         *wkptr1 = preDelayLine_.tickOut(preDelayTime);
         preDelayLine_.advance();
         // taps - write back to w0
         reflectDelayLine_.tickIn(*wkptr1++);
         *wkptr0 = 0;
         for (unsigned int t=0; t<reflectTapTimes_.size(); t++){
           *wkptr0 += reflectDelayLine_.tickOut(reflectTapTimes_[t]) * reflectTapScale_[t];
         }
         reflectDelayLine_.advance();
         wkptr0++;
       }
       // Comb filers
       preOutputFrames_[TONIC_LEFT].clear();
       preOutputFrames_[TONIC_RIGHT].clear();
       for (unsigned int i=0; i<combFilters_[TONIC_LEFT].size(); i++){
         combFilters_[TONIC_LEFT][i].tickThrough(workspaceFrames_[0], workspaceFrames_[1], context);
         preOutputFrames_[TONIC_LEFT] += workspaceFrames_[1];
         combFilters_[TONIC_RIGHT][i].tickThrough(workspaceFrames_[0], workspaceFrames_[1], context);
         preOutputFrames_[TONIC_RIGHT] += workspaceFrames_[1];
       }
       // Allpass filters
       for (unsigned int i=0; i<allpassFilters_[TONIC_LEFT].size(); i++){
         allpassFilters_[TONIC_LEFT][i].tickThrough(preOutputFrames_[TONIC_LEFT]);
         allpassFilters_[TONIC_RIGHT][i].tickThrough(preOutputFrames_[TONIC_RIGHT]);
       }
       // interleave pre-output frames into output frames
       TonicFloat *outptr = &outputFrames_[0];
       TonicFloat *preoutptrL = &preOutputFrames_[TONIC_LEFT][0];
       TonicFloat *preoutptrR = &preOutputFrames_[TONIC_RIGHT][0];
       TonicFloat spreadValue = clamp(1.0f - stereoWidthCtrlGen_.tick(context).value, 0.f, 1.f);
       TonicFloat normValue = (1.0f/(1.0f+spreadValue))*0.04f; // scale back levels quite a bit
       for (unsigned int i=0; i<kSynthesisBlockSize; i++){
         *outptr++ = (*preoutptrL + (spreadValue * (*preoutptrR)))*normValue;
         *outptr++ = (*preoutptrR++ + (spreadValue * (*preoutptrL++)))*normValue;
       }
     }
setDecayHPFCtrlGen()
void Tonic::Tonic_::Reverb_::setDecayHPFCtrlGen (ControlGenerator gen)
Definition at line 178 of file Reverb.cpp.
References combFilters_, TONIC_LEFT, TONIC_REVERB_N_COMBS, and TONIC_RIGHT.
   {
     for (unsigned int i=0; i<TONIC_REVERB_N_COMBS; i++){
       combFilters_[TONIC_LEFT][i].highpassCutoff(gen);
       combFilters_[TONIC_RIGHT][i].highpassCutoff(gen);
     }
   }
setDecayLPFCtrlGen()
void Tonic::Tonic_::Reverb_::setDecayLPFCtrlGen (ControlGenerator gen)
Definition at line 170 of file Reverb.cpp.
References combFilters_, TONIC_LEFT, TONIC_REVERB_N_COMBS, and TONIC_RIGHT.
   {
     for (unsigned int i=0; i<TONIC_REVERB_N_COMBS; i++){
       combFilters_[TONIC_LEFT][i].lowpassCutoff(gen);
       combFilters_[TONIC_RIGHT][i].lowpassCutoff(gen);
     }
   }
setDecayTimeCtrlGen()
void Tonic::Tonic_::Reverb_::setDecayTimeCtrlGen (ControlGenerator gen) inline
Definition at line 131 of file Reverb.h.
References decayTimeCtrlGen_.
 { decayTimeCtrlGen_ = gen; }
setDensityCtrlGen()
void Tonic::Tonic_::Reverb_::setDensityCtrlGen (ControlGenerator gen) inline
Definition at line 130 of file Reverb.h.
References densityCtrlGen_.
 { densityCtrlGen_ = gen; }
setInputFiltBypassCtrlGen()
void Tonic::Tonic_::Reverb_::setInputFiltBypassCtrlGen (ControlGenerator gen) inline
Definition at line 125 of file Reverb.h.
References inputFiltBypasCtrlGen_.
 { inputFiltBypasCtrlGen_ = gen; }
setInputHPFCutoffCtrlGen()
void Tonic::Tonic_::Reverb_::setInputHPFCutoffCtrlGen (ControlGenerator gen) inline
Definition at line 127 of file Reverb.h.
References inputHPF_.
 { inputHPF_.cutoff(gen); }
setInputLPFCutoffCtrlGen()
void Tonic::Tonic_::Reverb_::setInputLPFCutoffCtrlGen (ControlGenerator gen) inline
Definition at line 126 of file Reverb.h.
References inputLPF_.
 { inputLPF_.cutoff(gen); }
setPreDelayTimeCtrlGen()
void Tonic::Tonic_::Reverb_::setPreDelayTimeCtrlGen (ControlGenerator gen) inline
Definition at line 124 of file Reverb.h.
References preDelayTimeCtrlGen_.
 { preDelayTimeCtrlGen_ = gen; }
setRoomShapeCtrlGen()
void Tonic::Tonic_::Reverb_::setRoomShapeCtrlGen (ControlGenerator gen) inline
Definition at line 129 of file Reverb.h.
References roomShapeCtrlGen_.
 { roomShapeCtrlGen_ = gen; }
setRoomSizeCtrlGen()
void Tonic::Tonic_::Reverb_::setRoomSizeCtrlGen (ControlGenerator gen) inline
Definition at line 128 of file Reverb.h.
References roomSizeCtrlGen_.
 { roomSizeCtrlGen_ = gen; }
setStereoWidthCtrlGen()
void Tonic::Tonic_::Reverb_::setStereoWidthCtrlGen (ControlGenerator gen) inline
Definition at line 132 of file Reverb.h.
References stereoWidthCtrlGen_.
 { stereoWidthCtrlGen_ = gen; }
updateDelayTimes()
void Tonic::Tonic_::Reverb_::updateDelayTimes (const SynthesisContext_ & context) protected
Definition at line 115 of file Reverb.cpp.
References Tonic::clamp(), combFilterDelayTimes_, combFilterScaleFactors_, Tonic::Tonic_::combTimeScales_, Tonic::dBToLin(), decayTimeCtrlGen_, densityCtrlGen_, Tonic::map(), Tonic::max(), Tonic::randomFloat(), reflectTapScale_, reflectTapTimes_, roomShapeCtrlGen_, roomSizeCtrlGen_, Tonic::ControlGenerator::tick(), TONIC_LEFT, TONIC_REVERB_AIRDECAY, TONIC_REVERB_FUDGE_AMT, TONIC_REVERB_MAX_COMB_TIME, TONIC_REVERB_MAX_TAPS, TONIC_REVERB_MAX_WALL_DIST, TONIC_REVERB_MIN_COMB_TIME, TONIC_REVERB_MIN_TAPS, TONIC_REVERB_MIN_WALL_DIST, TONIC_REVERB_N_COMBS, TONIC_REVERB_SOS, TONIC_REVERB_STEREO_SPREAD, TONIC_RIGHT, Tonic::ControlGeneratorOutput::triggered, and Tonic::ControlGeneratorOutput::value.
   {
     ControlGeneratorOutput densityOutput = densityCtrlGen_.tick(context);
     ControlGeneratorOutput shapeOutput = roomShapeCtrlGen_.tick(context);
     ControlGeneratorOutput sizeOutput = roomSizeCtrlGen_.tick(context);
     ControlGeneratorOutput decayOutput = decayTimeCtrlGen_.tick(context);
     if (densityOutput.triggered ||
         shapeOutput.triggered ||
         sizeOutput.triggered)
     {
       reflectTapTimes_.clear();
       reflectTapScale_.clear();
       // compute base round-trip times from listener to wall, based on shape and size values
       TonicFloat shape = clamp(shapeOutput.value, 0.f, 1.f);
       TonicFloat size = clamp(sizeOutput.value, 0.f, 1.f);
       TonicFloat wDist1 = map(size, 0.f, 1.f, TONIC_REVERB_MIN_WALL_DIST, TONIC_REVERB_MAX_WALL_DIST, true);
       TonicFloat wDist2 = map(size * (1.1f - shape), 0.f, 1.f, TONIC_REVERB_MIN_WALL_DIST, TONIC_REVERB_MAX_WALL_DIST, true);
       unsigned int nTaps = (unsigned int)map(densityOutput.value, 0.f, 1.f, TONIC_REVERB_MIN_TAPS, TONIC_REVERB_MAX_TAPS, true);
       TonicFloat tapScale = 1.0f/max(2.f, sqrtf(nTaps));
       for (unsigned int i=0; i<nTaps; i++){
         TonicFloat dist = (i % 2 == 0 ? wDist1 : wDist2) * (1.0f + randomFloat(-TONIC_REVERB_FUDGE_AMT, TONIC_REVERB_FUDGE_AMT));
         reflectTapTimes_.push_back( dist/TONIC_REVERB_SOS );
         reflectTapScale_.push_back( dBToLin(dist * TONIC_REVERB_AIRDECAY)*tapScale );
       }
     }
     // if decay or room size have changed, need to update comb times/scales
     if (sizeOutput.triggered ||
         decayOutput.triggered)
     {
       TonicFloat decayTime = decayOutput.value;
       TonicFloat baseCombDelayTime = map(sizeOutput.value, 0.f, 1.f, TONIC_REVERB_MIN_COMB_TIME, TONIC_REVERB_MAX_COMB_TIME, true);
       for (unsigned int i=0; i<TONIC_REVERB_N_COMBS; i++){
         TonicFloat scaledDelayTime = combTimeScales_[i % TONIC_REVERB_N_COMBS] * baseCombDelayTime;
         combFilterDelayTimes_[TONIC_LEFT][i].value(scaledDelayTime);
         combFilterDelayTimes_[TONIC_RIGHT][i].value(scaledDelayTime+TONIC_REVERB_STEREO_SPREAD);
         combFilterScaleFactors_[TONIC_LEFT][i].value( powf(10.f, (-3.0f * scaledDelayTime / decayTime)) );
         combFilterScaleFactors_[TONIC_RIGHT][i].value( powf(10.f, (-3.0f * (scaledDelayTime+TONIC_REVERB_STEREO_SPREAD) / decayTime)) );
       }
     }
   }
Member Data Documentation
allpassFilters_
vector<ImpulseDiffuserAllpass> Tonic::Tonic_::Reverb_::allpassFilters_[2] protected
Definition at line 100 of file Reverb.h.
combFilterDelayTimes_
vector<ControlValue> Tonic::Tonic_::Reverb_::combFilterDelayTimes_[2] protected
Definition at line 96 of file Reverb.h.
combFilters_
vector<FilteredFBCombFilter6> Tonic::Tonic_::Reverb_::combFilters_[2] protected
Definition at line 95 of file Reverb.h.
combFilterScaleFactors_
vector<ControlValue> Tonic::Tonic_::Reverb_::combFilterScaleFactors_[2] protected
Definition at line 97 of file Reverb.h.
decayTimeCtrlGen_
ControlGenerator Tonic::Tonic_::Reverb_::decayTimeCtrlGen_ protected
Definition at line 113 of file Reverb.h.
densityCtrlGen_
ControlGenerator Tonic::Tonic_::Reverb_::densityCtrlGen_ protected
Definition at line 111 of file Reverb.h.
inputFiltBypasCtrlGen_
ControlGenerator Tonic::Tonic_::Reverb_::inputFiltBypasCtrlGen_ protected
Definition at line 108 of file Reverb.h.
inputHPF_
HPF12 Tonic::Tonic_::Reverb_::inputHPF_ protected
Definition at line 89 of file Reverb.h.
inputLPF_
LPF12 Tonic::Tonic_::Reverb_::inputLPF_ protected
Definition at line 88 of file Reverb.h.
preDelayLine_
DelayLine Tonic::Tonic_::Reverb_::preDelayLine_ protected
Definition at line 85 of file Reverb.h.
preDelayTimeCtrlGen_
ControlGenerator Tonic::Tonic_::Reverb_::preDelayTimeCtrlGen_ protected
Definition at line 107 of file Reverb.h.
preOutputFrames_
TonicFrames Tonic::Tonic_::Reverb_::preOutputFrames_[2] protected
Definition at line 104 of file Reverb.h.
reflectDelayLine_
DelayLine Tonic::Tonic_::Reverb_::reflectDelayLine_ protected
Definition at line 86 of file Reverb.h.
reflectTapScale_
vector<TonicFloat> Tonic::Tonic_::Reverb_::reflectTapScale_ protected
Definition at line 92 of file Reverb.h.
reflectTapTimes_
vector<TonicFloat> Tonic::Tonic_::Reverb_::reflectTapTimes_ protected
Definition at line 91 of file Reverb.h.
roomShapeCtrlGen_
ControlGenerator Tonic::Tonic_::Reverb_::roomShapeCtrlGen_ protected
Definition at line 110 of file Reverb.h.
roomSizeCtrlGen_
ControlGenerator Tonic::Tonic_::Reverb_::roomSizeCtrlGen_ protected
Definition at line 109 of file Reverb.h.
stereoWidthCtrlGen_
ControlGenerator Tonic::Tonic_::Reverb_::stereoWidthCtrlGen_ protected
Definition at line 114 of file Reverb.h.
workspaceFrames_
TonicFrames Tonic::Tonic_::Reverb_::workspaceFrames_[2] protected
Definition at line 103 of file Reverb.h.
The documentation for this class was generated from the following files:
Reverb.h
Reverb.cpp