YOURPROJECTNAMEGOESHERE: Tonic::ControlMultiplier Class Reference
Tonic::ControlMultiplier Class Reference
#include <ControlArithmetic.h>
Public Member Functions
void input (ControlGenerator input)
ControlGenerator operator[] (unsigned int index)
unsigned long numInputs ()
Public Member Functions inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlMultiplier_ >
TemplatedControlGenerator ()
Public Member Functions inherited from Tonic::ControlGenerator
ControlGenerator (Tonic_::ControlGenerator_ *cGen=new Tonic_::ControlGenerator_)
ControlGeneratorOutput tick (const Tonic_::SynthesisContext_ &context)
RampedValue smoothed (float length=0.05)
ControlAdder operator+ (ControlGenerator b)
ControlAdder operator+ (float b)
ControlSubtractor operator- (ControlGenerator b)
ControlSubtractor operator- (float b)
ControlMultiplier operator* (ControlGenerator b)
ControlMultiplier operator* (float b)
ControlDivider operator/ (ControlGenerator b)
ControlDivider operator/ (float b)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::ControlGenerator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Public Types inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlMultiplier_ >
typedef Tonic_::ControlMultiplier_ gen_t
Protected Member Functions inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlMultiplier_ >
Tonic_::ControlMultiplier_ * gen ()
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >
Tonic_::ControlGenerator_ * obj
int * pcount
Detailed Description
Definition at line 213 of file ControlArithmetic.h.
Member Function Documentation
input()
void Tonic::ControlMultiplier::input (ControlGenerator input) inline
Definition at line 217 of file ControlArithmetic.h.
References Tonic::TemplatedControlGenerator< Tonic_::ControlMultiplier_ >::gen(), and Tonic::Tonic_::ControlMultiplier_::input().
{
       gen()->input( input );
     }
numInputs()
unsigned long Tonic::ControlMultiplier::numInputs () inline
Definition at line 225 of file ControlArithmetic.h.
References Tonic::TemplatedControlGenerator< Tonic_::ControlMultiplier_ >::gen(), and Tonic::Tonic_::ControlMultiplier_::numInputs().
{
       return gen()->numInputs();
     }
operator[]()
ControlGenerator Tonic::ControlMultiplier::operator[] (unsigned int index) inline
Definition at line 221 of file ControlArithmetic.h.
References Tonic::TemplatedControlGenerator< Tonic_::ControlMultiplier_ >::gen(), and Tonic::Tonic_::ControlMultiplier_::getInput().
{
       return gen()->getInput(index);
     }
The documentation for this class was generated from the following file:
ControlArithmetic.h