YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::Filter_ Class Reference
Tonic::Tonic_::Filter_ Class Reference abstract
Basic filter Effect_ subclass with inputs for cutoff and Q.
#include <Filters.h>
Public Member Functions
Filter_ ()
virtual void setInput (Generator input)
void setNormalizesGain (bool norm)
void setCutoff (Generator cutoff)
void setQ (Generator Q)
void setBypass (ControlGenerator bypass)
Public Member Functions inherited from Tonic::Tonic_::Effect_
Effect_ ()
void setBypassCtrlGen (ControlGenerator gen)
virtual void setIsStereoInput (bool stereo)
set stereo/mono - changes number of channels in dryFrames_
bool isStereoInput ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
virtual void tickThrough (TonicFrames &inFrames, TonicFrames &outFrames, const SynthesisContext_ &context)
Apply effect directly to passed in frames (output in-place)
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
virtual void applyFilter (TonicFloat cutoff, TonicFloat Q, const SynthesisContext_ &context)=0
Protected Attributes
TonicFrames workspace_
Generator cutoff_
Generator Q_
ControlGenerator bypass_
bool bNormalizeGain_
Protected Attributes inherited from Tonic::Tonic_::Effect_
Generator input_
TonicFrames dryFrames_
ControlGenerator bypassGen_
bool isStereoInput_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Basic filter Effect_ subclass with inputs for cutoff and Q.
Definition at line 44 of file Filters.h.
Constructor & Destructor Documentation
Filter_()
Tonic::Tonic_::Filter_::Filter_ ()
Definition at line 17 of file Filters.cpp.
References Tonic::kSynthesisBlockSize, Tonic::TonicFrames::resize(), and workspace_.
                    :
     cutoff_(FixedValue(20000)),
     Q_(FixedValue(0.7071)),
     bypass_(ControlValue(0)),
     bNormalizeGain_(true)
   {
     workspace_.resize(kSynthesisBlockSize, 1, 0);
   }
Member Function Documentation
applyFilter()
virtual void Tonic::Tonic_::Filter_::applyFilter (TonicFloat cutoff, TonicFloat Q, const SynthesisContext_ & context) protected pure virtual
Implemented in Tonic::Tonic_::BPF24_, Tonic::Tonic_::BPF12_, Tonic::Tonic_::HPF24_, Tonic::Tonic_::HPF12_, Tonic::Tonic_::LPF24_, Tonic::Tonic_::LPF12_, Tonic::Tonic_::HPF6_, and Tonic::Tonic_::LPF6_.
computeSynthesisBlock()
void Tonic::Tonic_::Filter_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 76 of file Filters.h.
References applyFilter(), Tonic::clamp(), cutoff_, Tonic::max(), Q_, Tonic::sampleRate(), Tonic::Generator::tick(), and workspace_.
{
       TonicFloat cCutoff;
       TonicFloat cQ;
       // get cutoff and Q inputs
       // For now only using first frame of output. Setting coefficients each frame is very inefficient.
       // Updating cutoff every 64-samples is typically fast enough to avoid audible artifacts when sweeping filters.
       cutoff_.tick(workspace_, context);
       cCutoff = clamp(workspace_(0,0), 20, sampleRate()/2); // clamp to reasonable range
       Q_.tick(workspace_, context);
       cQ = max(workspace_(0,0), 0.7071); // clamp to reasonable range
       applyFilter(cCutoff, cQ, context);
     }
setBypass()
void Tonic::Tonic_::Filter_::setBypass (ControlGenerator bypass) inline
Definition at line 71 of file Filters.h.
References bypass_.
 { bypass_ = bypass; };
setCutoff()
void Tonic::Tonic_::Filter_::setCutoff (Generator cutoff) inline
Definition at line 69 of file Filters.h.
References cutoff_.
 { cutoff_ = cutoff; };
setInput()
void Tonic::Tonic_::Filter_::setInput (Generator input) virtual
Reimplemented from Tonic::Tonic_::Effect_.
Definition at line 26 of file Filters.cpp.
References Tonic::Generator::isStereoOutput(), Tonic::Tonic_::Effect_::setInput(), Tonic::Tonic_::Effect_::setIsStereoInput(), and Tonic::Tonic_::Generator_::setIsStereoOutput().
{
     Effect_::setInput(input);
     setIsStereoInput(input.isStereoOutput());
     setIsStereoOutput(input.isStereoOutput());
   }
setNormalizesGain()
void Tonic::Tonic_::Filter_::setNormalizesGain (bool norm) inline
Definition at line 68 of file Filters.h.
References bNormalizeGain_.
 { bNormalizeGain_ = norm; };
setQ()
void Tonic::Tonic_::Filter_::setQ (Generator Q) inline
Definition at line 70 of file Filters.h.
References Q_.
 { Q_ = Q; }
Member Data Documentation
bNormalizeGain_
bool Tonic::Tonic_::Filter_::bNormalizeGain_ protected
Definition at line 54 of file Filters.h.
bypass_
ControlGenerator Tonic::Tonic_::Filter_::bypass_ protected
Definition at line 52 of file Filters.h.
cutoff_
Generator Tonic::Tonic_::Filter_::cutoff_ protected
Definition at line 50 of file Filters.h.
Q_
Generator Tonic::Tonic_::Filter_::Q_ protected
Definition at line 51 of file Filters.h.
workspace_
TonicFrames Tonic::Tonic_::Filter_::workspace_ protected
Definition at line 48 of file Filters.h.
The documentation for this class was generated from the following files:
Filters.h
Filters.cpp