YOURPROJECTNAMEGOESHERE: Tonic::ControlGenerator Class Reference
Tonic::ControlGenerator Class Reference
#include <ControlGenerator.h>
Public Member Functions
ControlGenerator (Tonic_::ControlGenerator_ *cGen=new Tonic_::ControlGenerator_)
ControlGeneratorOutput tick (const Tonic_::SynthesisContext_ &context)
RampedValue smoothed (float length=0.05)
ControlAdder operator+ (ControlGenerator b)
ControlAdder operator+ (float b)
ControlSubtractor operator- (ControlGenerator b)
ControlSubtractor operator- (float b)
ControlMultiplier operator* (ControlGenerator b)
ControlMultiplier operator* (float b)
ControlDivider operator/ (ControlGenerator b)
ControlDivider operator/ (float b)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::ControlGenerator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >
Tonic_::ControlGenerator_ * obj
int * pcount
Detailed Description
Definition at line 84 of file ControlGenerator.h.
Constructor & Destructor Documentation
ControlGenerator()
Tonic::ControlGenerator::ControlGenerator (Tonic_::ControlGenerator_ * cGen = new Tonic_::ControlGenerator_) inline
Definition at line 88 of file ControlGenerator.h.
 : TonicSmartPointer<Tonic_::ControlGenerator_>(cGen) {}
Member Function Documentation
operator*() [1/2]
ControlMultiplier Tonic::ControlGenerator::operator* (ControlGenerator b)
Definition at line 68 of file ControlGenerator.cpp.
References Tonic::ControlMultiplier::input().
{
      ControlMultiplier mult;
      mult.input(*this);
      mult.input(b);
      return mult;
    }
operator*() [2/2]
ControlMultiplier Tonic::ControlGenerator::operator* (float b)
Definition at line 75 of file ControlGenerator.cpp.
References Tonic::ControlMultiplier::input().
{
      ControlMultiplier mult;
      mult.input(*this);
      mult.input(ControlValue(b));
      return mult;
    }
operator+() [1/2]
ControlAdder Tonic::ControlGenerator::operator+ (ControlGenerator b)
Definition at line 40 of file ControlGenerator.cpp.
References Tonic::ControlAdder::input().
{
      ControlAdder adder;
      adder.input(*this);
      adder.input(b);
      return adder;
    }
operator+() [2/2]
ControlAdder Tonic::ControlGenerator::operator+ (float b)
Definition at line 47 of file ControlGenerator.cpp.
References Tonic::ControlAdder::input().
{
      ControlAdder adder;
      adder.input(*this);
      adder.input(ControlValue(b));
      return adder;
    }
operator-() [1/2]
ControlSubtractor Tonic::ControlGenerator::operator- (ControlGenerator b)
Definition at line 54 of file ControlGenerator.cpp.
{
      ControlSubtractor subtractor;
      subtractor.left(*this);
      subtractor.right(b);
      return subtractor;
    }
operator-() [2/2]
ControlSubtractor Tonic::ControlGenerator::operator- (float b)
Definition at line 61 of file ControlGenerator.cpp.
{
      ControlSubtractor subtractor;
      subtractor.left(*this);
      subtractor.right(ControlValue(b));
      return subtractor;
    }
operator/() [1/2]
ControlDivider Tonic::ControlGenerator::operator/ (ControlGenerator b)
Definition at line 83 of file ControlGenerator.cpp.
{
      ControlDivider divider;
      divider.left(*this);
      divider.right(b);
      return divider;
    }
operator/() [2/2]
ControlDivider Tonic::ControlGenerator::operator/ (float b)
Definition at line 90 of file ControlGenerator.cpp.
{
      ControlDivider divider;
      divider.left(*this);
      divider.right(ControlValue(b));
      return divider;
    }
smoothed()
RampedValue Tonic::ControlGenerator::smoothed (float length = 0.05)
Definition at line 36 of file ControlGenerator.cpp.
References Tonic::Tonic_::ControlGenerator_::initialOutput(), Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >::obj, and Tonic::ControlGeneratorOutput::value.
{
     return RampedValue( obj->initialOutput().value, length ).target(*this);
   }
tick()
ControlGeneratorOutput Tonic::ControlGenerator::tick (const Tonic_::SynthesisContext_ & context) inline
Definition at line 90 of file ControlGenerator.h.
References Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >::obj, and Tonic::Tonic_::ControlGenerator_::tick().
{
       return obj->tick(context);
     }
The documentation for this class was generated from the following files:
ControlGenerator.h
ControlGenerator.cpp