YOURPROJECTNAMEGOESHERE: Tonic::ControlChangeNotifier Class Reference
Tonic::ControlChangeNotifier Class Reference
#include <ControlChangeNotifier.h>
Public Member Functions
void sendControlChangesToSubscribers ()
void addValueChangedSubscriber (ControlChangeSubscriber *resp)
void removeValueChangedSubscriber (ControlChangeSubscriber *sub)
void setName (string name)
Public Member Functions inherited from Tonic::TemplatedControlConditioner< Tonic::ControlChangeNotifier, Tonic_::ControlChangeNotifier_ >
Tonic::ControlChangeNotifier input (ControlGenerator input)
Tonic::ControlChangeNotifier input (float inputVal)
Public Member Functions inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlChangeNotifier_ >
TemplatedControlGenerator ()
Public Member Functions inherited from Tonic::ControlGenerator
ControlGenerator (Tonic_::ControlGenerator_ *cGen=new Tonic_::ControlGenerator_)
ControlGeneratorOutput tick (const Tonic_::SynthesisContext_ &context)
RampedValue smoothed (float length=0.05)
ControlAdder operator+ (ControlGenerator b)
ControlAdder operator+ (float b)
ControlSubtractor operator- (ControlGenerator b)
ControlSubtractor operator- (float b)
ControlMultiplier operator* (ControlGenerator b)
ControlMultiplier operator* (float b)
ControlDivider operator/ (ControlGenerator b)
ControlDivider operator/ (float b)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::ControlGenerator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Public Types inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlChangeNotifier_ >
typedef Tonic_::ControlChangeNotifier_ gen_t
Protected Member Functions inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlChangeNotifier_ >
Tonic_::ControlChangeNotifier_ * gen ()
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >
Tonic_::ControlGenerator_ * obj
int * pcount
Detailed Description
A ControlChangeNotifier observes a ControlGenerator and notifies its subscribers when its value changes, or when the value of its outputs "triggered" flag is true. Generally you don't instantiate this object directly, rather you "publish" a controlGenerator using Synth::publishChanges(myControlGen, "nameOfMyControlGen");
Definition at line 52 of file ControlChangeNotifier.h.
Member Function Documentation
addValueChangedSubscriber()
void Tonic::ControlChangeNotifier::addValueChangedSubscriber (ControlChangeSubscriber * resp) inline
Definition at line 57 of file ControlChangeNotifier.h.
References Tonic::Tonic_::ControlChangeNotifier_::addValueChangedSubscriber(), and Tonic::TemplatedControlGenerator< Tonic_::ControlChangeNotifier_ >::gen().
 {gen()->addValueChangedSubscriber(resp);};
removeValueChangedSubscriber()
void Tonic::ControlChangeNotifier::removeValueChangedSubscriber (ControlChangeSubscriber * sub) inline
Definition at line 58 of file ControlChangeNotifier.h.
References Tonic::TemplatedControlGenerator< Tonic_::ControlChangeNotifier_ >::gen(), and Tonic::Tonic_::ControlChangeNotifier_::removeValueChangedSubscriber().
 {gen()->removeValueChangedSubscriber(sub);};
sendControlChangesToSubscribers()
void Tonic::ControlChangeNotifier::sendControlChangesToSubscribers ()
Definition at line 50 of file ControlChangeNotifier.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlChangeNotifier_ >::gen(), and Tonic::Tonic_::ControlChangeNotifier_::sendControlChangesToSubscribers().
{
     gen()->sendControlChangesToSubscribers();
   }
setName()
void Tonic::ControlChangeNotifier::setName (string name) inline
Definition at line 59 of file ControlChangeNotifier.h.
References Tonic::TemplatedControlGenerator< Tonic_::ControlChangeNotifier_ >::gen(), and Tonic::Tonic_::ControlChangeNotifier_::name.
 {gen()->name = name;}
The documentation for this class was generated from the following files:
ControlChangeNotifier.h
ControlChangeNotifier.cpp