YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::StereoDelay_ Class Reference
Tonic::Tonic_::StereoDelay_ Class Reference
#include <StereoDelay.h>
Public Member Functions
StereoDelay_ ()
void initialize (float leftDelayArg, float rightDelayArg, float maxDelayLeft, float maxDelayRight)
void setFeedback (Generator arg)
void setDelayTimeLeft (Generator arg)
void setDelayTimeRight (Generator arg)
Public Member Functions inherited from Tonic::Tonic_::WetDryEffect_
WetDryEffect_ ()
void setDryLevelGen (Generator gen)
void setWetLevelGen (Generator gen)
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
virtual void tickThrough (TonicFrames &inFrames, TonicFrames &outFrames, const SynthesisContext_ &context)
Apply effect directly to passed in frames (output in-place)
Public Member Functions inherited from Tonic::Tonic_::Effect_
Effect_ ()
void setBypassCtrlGen (ControlGenerator gen)
virtual void setInput (Generator input)
virtual void setIsStereoInput (bool stereo)
set stereo/mono - changes number of channels in dryFrames_
bool isStereoInput ()
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
Generator delayTimeGen_ [2]
TonicFrames delayTimeFrames_ [2]
Generator fbkGen_
TonicFrames fbkFrames_
DelayLine delayLine_ [2]
Protected Attributes inherited from Tonic::Tonic_::WetDryEffect_
Generator dryLevelGen_
Generator wetLevelGen_
TonicFrames mixWorkspace_
Protected Attributes inherited from Tonic::Tonic_::Effect_
Generator input_
TonicFrames dryFrames_
ControlGenerator bypassGen_
bool isStereoInput_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 22 of file StereoDelay.h.
Constructor & Destructor Documentation
StereoDelay_()
Tonic::Tonic_::StereoDelay_::StereoDelay_ ()
Definition at line 13 of file StereoDelay.cpp.
References delayTimeFrames_, fbkFrames_, Tonic::kSynthesisBlockSize, Tonic::TonicFrames::resize(), Tonic::Tonic_::WetDryEffect_::setDryLevelGen(), setFeedback(), Tonic::Tonic_::Effect_::setIsStereoInput(), Tonic::Tonic_::Generator_::setIsStereoOutput(), Tonic::Tonic_::WetDryEffect_::setWetLevelGen(), TONIC_LEFT, and TONIC_RIGHT.
{
     setIsStereoOutput(true);
     setIsStereoInput(true);
     delayTimeFrames_[TONIC_LEFT].resize(kSynthesisBlockSize, 1, 0);
     delayTimeFrames_[TONIC_RIGHT].resize(kSynthesisBlockSize, 1, 0);
     fbkFrames_.resize(kSynthesisBlockSize, 1, 0);
     setFeedback(FixedValue(0.0));
     setDryLevelGen(FixedValue(0.5));
     setWetLevelGen(FixedValue(0.5));
   }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::StereoDelay_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 57 of file StereoDelay.h.
References Tonic::DelayLine::advance(), delayLine_, delayTimeFrames_, delayTimeGen_, Tonic::Tonic_::Effect_::dryFrames_, fbkFrames_, fbkGen_, Tonic::kSynthesisBlockSize, Tonic::Tonic_::Generator_::outputFrames_, Tonic::Generator::tick(), Tonic::DelayLine::tickIn(), Tonic::DelayLine::tickOut(), TONIC_LEFT, and TONIC_RIGHT.
{
       delayTimeGen_[0].tick(delayTimeFrames_[TONIC_LEFT], context);
       delayTimeGen_[1].tick(delayTimeFrames_[TONIC_RIGHT], context);
       fbkGen_.tick(fbkFrames_, context);
       TonicFloat outSamp[2], fbk;
       TonicFloat *dryptr = &dryFrames_[0];
       TonicFloat *outptr = &outputFrames_[0];
       TonicFloat *fbkptr = &fbkFrames_[0];
       TonicFloat *delptr_l = &(delayTimeFrames_[TONIC_LEFT])[0];
       TonicFloat *delptr_r = &(delayTimeFrames_[TONIC_RIGHT])[0];
       for (unsigned int i=0; i<kSynthesisBlockSize; i++){
         // Don't clamp feeback - be careful! Negative feedback could be interesting.
         fbk = *fbkptr++;
         outSamp[TONIC_LEFT] = delayLine_[TONIC_LEFT].tickOut(*delptr_l++);
         outSamp[TONIC_RIGHT] = delayLine_[TONIC_RIGHT].tickOut(*delptr_r++);
         // output left sample
         *outptr++ = outSamp[TONIC_LEFT];
         delayLine_[TONIC_LEFT].tickIn(*dryptr++ + outSamp[TONIC_LEFT] * fbk);
         // output right sample
         *outptr++ = outSamp[TONIC_RIGHT];
         delayLine_[TONIC_RIGHT].tickIn(*dryptr++ + outSamp[TONIC_RIGHT] * fbk);
         // advance delay lines
         delayLine_[TONIC_LEFT].advance();
         delayLine_[TONIC_RIGHT].advance();
       }
     }
initialize()
void Tonic::Tonic_::StereoDelay_::initialize (float leftDelayArg, float rightDelayArg, float maxDelayLeft, float maxDelayRight)
Definition at line 25 of file StereoDelay.cpp.
References delayLine_, Tonic::DelayLine::initialize(), TONIC_LEFT, and TONIC_RIGHT.
{
     if (maxDelayLeft <= 0) maxDelayLeft = leftDelayArg * 1.5;
     if (maxDelayRight <= 0) maxDelayRight = rightDelayArg * 1.5;
     delayLine_[TONIC_LEFT].initialize(maxDelayLeft, 1);
     delayLine_[TONIC_RIGHT].initialize(maxDelayRight, 1);
   }
setDelayTimeLeft()
void Tonic::Tonic_::StereoDelay_::setDelayTimeLeft (Generator arg) inline
Definition at line 46 of file StereoDelay.h.
References delayTimeGen_.
{
         delayTimeGen_[0] = arg;
       };
setDelayTimeRight()
void Tonic::Tonic_::StereoDelay_::setDelayTimeRight (Generator arg) inline
Definition at line 50 of file StereoDelay.h.
References delayTimeGen_.
{
         delayTimeGen_[1] = arg;
       };
setFeedback()
void Tonic::Tonic_::StereoDelay_::setFeedback (Generator arg) inline
Definition at line 42 of file StereoDelay.h.
References fbkGen_.
{
         fbkGen_ = arg;
       };
Member Data Documentation
delayLine_
DelayLine Tonic::Tonic_::StereoDelay_::delayLine_[2] protected
Definition at line 32 of file StereoDelay.h.
delayTimeFrames_
TonicFrames Tonic::Tonic_::StereoDelay_::delayTimeFrames_[2] protected
Definition at line 27 of file StereoDelay.h.
delayTimeGen_
Generator Tonic::Tonic_::StereoDelay_::delayTimeGen_[2] protected
Definition at line 26 of file StereoDelay.h.
fbkFrames_
TonicFrames Tonic::Tonic_::StereoDelay_::fbkFrames_ protected
Definition at line 30 of file StereoDelay.h.
fbkGen_
Generator Tonic::Tonic_::StereoDelay_::fbkGen_ protected
Definition at line 29 of file StereoDelay.h.
The documentation for this class was generated from the following files:
StereoDelay.h
StereoDelay.cpp