YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::Synth_ Class Reference
Tonic::Tonic_::Synth_ Class Reference
#include <Synth.h>
Public Member Functions
Synth_ ()
void setOutputGen (Generator gen)
Set the output gen that produces audio for the Synth.
const Generator getOutputGen ()
void setLimitOutput (bool shouldLimit)
ControlParameter addParameter (string name, TonicFloat initialValue)
void addParameter (ControlParameter parameter)
void addParametersFromSynth (Synth synth)
void setParameter (string name, float value, bool normalized=false)
vector< ControlParameter > getParameters ()
ControlChangeNotifier publishChanges (ControlGenerator input, string name)
void addAuxControlGenerator (ControlGenerator generator)
void forceNewOutput ()
void sendControlChangesToSubscribers ()
void addControlChangeSubscriber (string name, ControlChangeSubscriber *resp)
void addControlChangeSubscriber (ControlChangeSubscriber *resp)
void removeControlChangeSubscriber (ControlChangeSubscriber *sub)
Public Member Functions inherited from Tonic::Tonic_::BufferFiller_
BufferFiller_ ()
~BufferFiller_ ()
void lockMutex ()
void unlockMutex ()
void tick (TonicFrames &frames)
Process a single synthesis vector, output to frames.
void fillBufferOfFloats (float *outData, unsigned int numFrames, unsigned int numChannels)
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
void computeSynthesisBlock (const Tonic::Tonic_::SynthesisContext_ &context)
Protected Attributes
Generator outputGen_
Limiter limiter_
bool limitOutput_
std::map< string, ControlParameter > parameters_
std::vector< string > orderedParameterNames_
std::map< string, ControlChangeNotifier > controlChangeNotifiers_
vector< ControlChangeNotifier > controlChangeNotifiersList_
vector< ControlGenerator > auxControlGenerators_
Protected Attributes inherited from Tonic::Tonic_::BufferFiller_
Tonic_::SynthesisContext_ synthContext_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 28 of file Synth.h.
Constructor & Destructor Documentation
Synth_()
Tonic::Tonic_::Synth_::Synth_ ()
Definition at line 22 of file Synth.cpp.
References limiter_, and Tonic::Limiter::setIsStereo().
                    : limitOutput_(true) {
       limiter_.setIsStereo(true);
     }
Member Function Documentation
addAuxControlGenerator()
void Tonic::Tonic_::Synth_::addAuxControlGenerator (ControlGenerator generator) inline
Definition at line 68 of file Synth.h.
References auxControlGenerators_.
{
         auxControlGenerators_.push_back(generator);
       }
addControlChangeSubscriber() [1/2]
void Tonic::Tonic_::Synth_::addControlChangeSubscriber (string name, ControlChangeSubscriber * resp)
Definition at line 87 of file Synth.cpp.
References controlChangeNotifiers_, and Tonic::error().
{
       if(controlChangeNotifiers_.find(name) != controlChangeNotifiers_.end()){
         controlChangeNotifiers_[name].addValueChangedSubscriber(resp);
       }else{
         error("No value called " + name + " was exposed to the UI.");
       }
     }
addControlChangeSubscriber() [2/2]
void Tonic::Tonic_::Synth_::addControlChangeSubscriber (ControlChangeSubscriber * resp)
Definition at line 95 of file Synth.cpp.
References controlChangeNotifiersList_.
{
       for(vector<ControlChangeNotifier>::iterator it = controlChangeNotifiersList_.begin(); it != controlChangeNotifiersList_.end(); it++){
         it->addValueChangedSubscriber(sub);
       }
     }
addParameter() [1/2]
ControlParameter Tonic::Tonic_::Synth_::addParameter (string name, TonicFloat initialValue)
Definition at line 46 of file Synth.cpp.
References Tonic::ControlParameter::displayName(), Tonic::ControlParameter::name(), orderedParameterNames_, parameters_, and Tonic::ControlParameter::value().
     {
       if (parameters_.find(name) == parameters_.end())
       {
         ControlParameter param = ControlParameter().name(name).value(initialValue).displayName(name);
         parameters_[name] = param;
         orderedParameterNames_.push_back(name);
       }
       return parameters_[name];
     }
addParameter() [2/2]
void Tonic::Tonic_::Synth_::addParameter (ControlParameter parameter)
Definition at line 57 of file Synth.cpp.
References Tonic::ControlParameter::getName(), orderedParameterNames_, and parameters_.
{
       string name = parameter.getName();
       parameters_[name] = parameter;
       orderedParameterNames_.push_back(name);
     }
addParametersFromSynth()
void Tonic::Tonic_::Synth_::addParametersFromSynth (Synth synth)
Definition at line 63 of file Synth.cpp.
References addParameter(), and Tonic::Synth::getParameters().
{
       vector<ControlParameter> params = synth.getParameters();
       for (unsigned int i=0; i<params.size(); i++)
         addParameter(params[i]);
     }
computeSynthesisBlock()
void Tonic::Tonic_::Synth_::computeSynthesisBlock (const Tonic::Tonic_::SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 84 of file Synth.h.
References auxControlGenerators_, limiter_, limitOutput_, Tonic::Tonic_::Generator_::outputFrames_, outputGen_, Tonic::Generator::tick(), and Tonic::TemplatedEffect< EffectType, EffectType_ >::tickThrough().
{
       outputGen_.tick(outputFrames_, context);
       for (vector<ControlGenerator>::iterator it = auxControlGenerators_.begin(); it != auxControlGenerators_.end(); it++) {
         it->tick(context);
       }
       if (limitOutput_){
         limiter_.tickThrough(outputFrames_, context);
       }
     }
forceNewOutput()
void Tonic::Tonic_::Synth_::forceNewOutput () inline
Definition at line 72 of file Synth.h.
References Tonic::Tonic_::SynthesisContext_::forceNewOutput, and Tonic::Tonic_::BufferFiller_::synthContext_.
{
         synthContext_.forceNewOutput = true;
       }
getOutputGen()
const Generator Tonic::Tonic_::Synth_::getOutputGen () inline
Definition at line 52 of file Synth.h.
References outputGen_.
 { return outputGen_; };
getParameters()
vector< ControlParameter > Tonic::Tonic_::Synth_::getParameters ()
Definition at line 69 of file Synth.cpp.
References orderedParameterNames_, and parameters_.
{
       vector<ControlParameter> returnParams;
       for (std::vector<string>::iterator it = orderedParameterNames_.begin(); it != orderedParameterNames_.end(); it++){
         std::map<string, ControlParameter>::iterator paramIt = parameters_.find(*it);
         if (paramIt != parameters_.end()){
           returnParams.push_back(paramIt->second);
         }
       }
       return returnParams;
     }
publishChanges()
ControlChangeNotifier Tonic::Tonic_::Synth_::publishChanges (ControlGenerator input, string name)
Definition at line 108 of file Synth.cpp.
References addAuxControlGenerator(), controlChangeNotifiers_, controlChangeNotifiersList_, Tonic::TemplatedControlConditioner< ControlConditionerType, ControlConditionerType_ >::input(), and Tonic::ControlChangeNotifier::setName().
{
       ControlChangeNotifier messenger;
       messenger.setName(name);
       messenger.input(input);
       controlChangeNotifiersList_.push_back(messenger);
       if(name != ""){
         controlChangeNotifiers_[name] = messenger;
       }
       addAuxControlGenerator(messenger);
       return messenger;
     }
removeControlChangeSubscriber()
void Tonic::Tonic_::Synth_::removeControlChangeSubscriber (ControlChangeSubscriber * sub)
Definition at line 101 of file Synth.cpp.
References controlChangeNotifiersList_.
{
       vector<ControlChangeNotifier>::iterator it = controlChangeNotifiersList_.begin();
       for (; it != controlChangeNotifiersList_.end(); it++) {
         it->removeValueChangedSubscriber(sub);
       }
     }
sendControlChangesToSubscribers()
void Tonic::Tonic_::Synth_::sendControlChangesToSubscribers ()
Definition at line 80 of file Synth.cpp.
References controlChangeNotifiersList_.
{
       vector<ControlChangeNotifier>::iterator it = controlChangeNotifiersList_.begin();
       for (; it != controlChangeNotifiersList_.end(); it++) {
         it->sendControlChangesToSubscribers();
       }
     }
setLimitOutput()
void Tonic::Tonic_::Synth_::setLimitOutput (bool shouldLimit) inline
Definition at line 54 of file Synth.h.
References limitOutput_.
 { limitOutput_ = shouldLimit; };
setOutputGen()
void Tonic::Tonic_::Synth_::setOutputGen (Generator gen) inline
Set the output gen that produces audio for the Synth.
Definition at line 51 of file Synth.h.
References outputGen_.
 { outputGen_ = gen; }
setParameter()
void Tonic::Tonic_::Synth_::setParameter (string name, float value, bool normalized = false)
Definition at line 26 of file Synth.cpp.
References Tonic::error(), parameters_, Tonic::ControlParameter::setNormalizedValue(), and Tonic::ControlParameter::value().
{
       if (parameters_.find(name)!=parameters_.end()) {
         ControlParameter & param = parameters_[name];
         if (normalized){
           param.setNormalizedValue(value);
         }
         else{
           param.value(value);
         }
       }
       else{
         error("message: " + name + " was not registered. You can register a message using Synth::addParameter.");
       }
     }
Member Data Documentation
auxControlGenerators_
vector<ControlGenerator> Tonic::Tonic_::Synth_::auxControlGenerators_ protected
Definition at line 42 of file Synth.h.
controlChangeNotifiers_
std::map<string, ControlChangeNotifier> Tonic::Tonic_::Synth_::controlChangeNotifiers_ protected
Definition at line 39 of file Synth.h.
controlChangeNotifiersList_
vector<ControlChangeNotifier> Tonic::Tonic_::Synth_::controlChangeNotifiersList_ protected
Definition at line 40 of file Synth.h.
limiter_
Limiter Tonic::Tonic_::Synth_::limiter_ protected
Definition at line 34 of file Synth.h.
limitOutput_
bool Tonic::Tonic_::Synth_::limitOutput_ protected
Definition at line 35 of file Synth.h.
orderedParameterNames_
std::vector<string> Tonic::Tonic_::Synth_::orderedParameterNames_ protected
Definition at line 38 of file Synth.h.
outputGen_
Generator Tonic::Tonic_::Synth_::outputGen_ protected
Definition at line 32 of file Synth.h.
parameters_
std::map<string, ControlParameter> Tonic::Tonic_::Synth_::parameters_ protected
Definition at line 37 of file Synth.h.
The documentation for this class was generated from the following files:
Synth.h
Synth.cpp