YOURPROJECTNAMEGOESHERE: Tonic::SampleTable Class Reference
Tonic::SampleTable Class Reference
Access to a persistent TonicFrames instance, so the same audio data can be read from multiple places.
#include <SampleTable.h>
Public Member Functions
SampleTable (unsigned int nFrames=64, unsigned int nChannels=2)
unsigned int channels () const
unsigned long frames () const
size_t size () const
TonicFloat * dataPointer ()
void resize (unsigned int frames, unsigned int channels)
void resample (unsigned int frames, unsigned int channels)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::SampleTable_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::SampleTable_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::SampleTable_ >
Tonic_::SampleTable_ * obj
int * pcount
Detailed Description
Access to a persistent TonicFrames instance, so the same audio data can be read from multiple places.
Definition at line 67 of file SampleTable.h.
Constructor & Destructor Documentation
SampleTable()
Tonic::SampleTable::SampleTable (unsigned int nFrames = 64, unsigned int nChannels = 2) inline
Definition at line 72 of file SampleTable.h.
 : TonicSmartPointer<Tonic_::SampleTable_>( new Tonic_::SampleTable_(nFrames, nChannels) ) {}
Member Function Documentation
channels()
unsigned int Tonic::SampleTable::channels () const inline
Definition at line 75 of file SampleTable.h.
References Tonic::Tonic_::SampleTable_::channels(), and Tonic::TonicSmartPointer< Tonic_::SampleTable_ >::obj.
{
       return obj->channels();
     }
dataPointer()
TonicFloat* Tonic::SampleTable::dataPointer () inline
Definition at line 88 of file SampleTable.h.
References Tonic::Tonic_::SampleTable_::dataPointer(), and Tonic::TonicSmartPointer< Tonic_::SampleTable_ >::obj.
{
       return obj->dataPointer();
     }
frames()
unsigned long Tonic::SampleTable::frames () const inline
Definition at line 79 of file SampleTable.h.
References Tonic::Tonic_::SampleTable_::frames(), and Tonic::TonicSmartPointer< Tonic_::SampleTable_ >::obj.
{
       return obj->frames();
     }
resample()
void Tonic::SampleTable::resample (unsigned int frames, unsigned int channels) inline
Definition at line 98 of file SampleTable.h.
References channels(), frames(), Tonic::TonicSmartPointer< Tonic_::SampleTable_ >::obj, and Tonic::Tonic_::SampleTable_::resample().
{
       obj->resample(frames, channels);
     }
resize()
void Tonic::SampleTable::resize (unsigned int frames, unsigned int channels) inline
Definition at line 93 of file SampleTable.h.
References channels(), frames(), Tonic::TonicSmartPointer< Tonic_::SampleTable_ >::obj, and Tonic::Tonic_::SampleTable_::resize().
{
       obj->resize(frames, channels);
     }
size()
size_t Tonic::SampleTable::size () const inline
Definition at line 83 of file SampleTable.h.
References Tonic::TonicSmartPointer< Tonic_::SampleTable_ >::obj, and Tonic::Tonic_::SampleTable_::size().
{
       return obj->size();
     }
The documentation for this class was generated from the following file:
SampleTable.h