YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::TableLookupOsc_ Class Reference
Tonic::Tonic_::TableLookupOsc_ Class Reference
#include <TableLookupOsc.h>
Public Member Functions
TableLookupOsc_ ()
void reset (void)
Clear output and reset time pointer to zero.
void setFrequency (Generator genArg)
Set frequency generator input.
void setLookupTable (SampleTable table)
set sample table for lookup. MUST BE POWER OF 2 IN LENGTH
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
SampleTable lookupTable_
double phase_
Generator frequencyGenerator_
TonicFrames modFrames_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 25 of file TableLookupOsc.h.
Constructor & Destructor Documentation
TableLookupOsc_()
Tonic::Tonic_::TableLookupOsc_::TableLookupOsc_ ()
Definition at line 21 of file TableLookupOsc.cpp.
References Tonic::kSynthesisBlockSize, lookupTable_, modFrames_, and Tonic::TonicFrames::resize().
                                      :
       phase_(0.0)
     {
       modFrames_.resize(kSynthesisBlockSize, 1);
       lookupTable_ = SampleTable(kSynthesisBlockSize,1);
     }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::TableLookupOsc_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 64 of file TableLookupOsc.h.
References BIT32DECPT, Tonic::FastPhasor::d, Tonic::SampleTable::dataPointer(), frequencyGenerator_, Tonic::FastPhasor::i, Tonic::kSynthesisBlockSize, lookupTable_, modFrames_, Tonic::Tonic_::Generator_::outputFrames_, phase_, Tonic::sampleRate(), Tonic::SampleTable::size(), and Tonic::Generator::tick().
{
       // Update the frequency data
       frequencyGenerator_.tick(modFrames_, context);
       unsigned long tableSize = lookupTable_.size()-1;
       const TonicFloat rateConstant = (TonicFloat)tableSize / Tonic::sampleRate();
       TonicFloat *samples = &outputFrames_[0];
       TonicFloat *rateBuffer = &modFrames_[0];
       TonicFloat *tableData = lookupTable_.dataPointer();
       // R. Hoelderich style fast phasor.
       FastPhasor sd;
       // pre-multiply rate constant for speed
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vsmul(rateBuffer, 1, &rateConstant, rateBuffer, 1, kSynthesisBlockSize);
 #else
       for (unsigned int i=0; i<kSynthesisBlockSize; i++){
         *rateBuffer++ *= rateConstant;
       }
       rateBuffer = &modFrames_[0];
 #endif
       sd.d = BIT32DECPT;
       TonicInt32 offs;
       TonicInt32 msbi = sd.i[1];
       double frac;
       double ps = phase_ + BIT32DECPT;
       TonicFloat *tAddr, f1, f2;
       for ( unsigned int i=0; i<kSynthesisBlockSize; i++ ) {
         sd.d = ps;
         ps += *rateBuffer++;
         offs = sd.i[1] & (tableSize-1);
         tAddr = tableData + offs;
         sd.i[1] = msbi;
         frac = sd.d - BIT32DECPT;
         f1 = tAddr[0];
         f2 = tAddr[1];
         *samples++ = f1 + frac * (f2 - f1);
       }
       sd.d = BIT32DECPT * tableSize;
       msbi = sd.i[1];
       sd.d = ps + (BIT32DECPT * tableSize - BIT32DECPT);
       sd.i[1] = msbi;
       phase_ = sd.d - BIT32DECPT * tableSize;
     }
reset()
void Tonic::Tonic_::TableLookupOsc_::reset (void)
Clear output and reset time pointer to zero.
Definition at line 28 of file TableLookupOsc.cpp.
References phase_.
{
       phase_ = 0.0f;
     }
setFrequency()
void Tonic::Tonic_::TableLookupOsc_::setFrequency (Generator genArg) inline
Set frequency generator input.
Definition at line 55 of file TableLookupOsc.h.
References frequencyGenerator_.
{
         frequencyGenerator_ = genArg;
       }
setLookupTable()
void Tonic::Tonic_::TableLookupOsc_::setLookupTable (SampleTable table)
set sample table for lookup. MUST BE POWER OF 2 IN LENGTH
Definition at line 32 of file TableLookupOsc.cpp.
References Tonic::SampleTable::channels(), Tonic::SampleTable::dataPointer(), Tonic::error(), Tonic::isPowerOf2(), lookupTable_, Tonic::SampleTable::resample(), Tonic::SampleTable::resize(), Tonic::SampleTable::size(), and Tonic::warning().
{
       if (table.channels() != 1){
         error("TableLookupOsc expects lookup table with 1 channel only");
         return;
       }
       unsigned int nearestPo2;
       if (!isPowerOf2((unsigned int)table.size() - 1, &nearestPo2)){
         warning("TableLookUpOsc lookup tables must have a (power-of-two + 1) number of samples (example 2049 or 4097). Resizing to nearest power-of-two + 1");
         table.resample(nearestPo2, 1);
         table.resize(nearestPo2+1, 1);
         table.dataPointer()[nearestPo2] = table.dataPointer()[0]; // copy first sample to last
       }
       lookupTable_ = table;
     }
Member Data Documentation
frequencyGenerator_
Generator Tonic::Tonic_::TableLookupOsc_::frequencyGenerator_ protected
Definition at line 42 of file TableLookupOsc.h.
lookupTable_
SampleTable Tonic::Tonic_::TableLookupOsc_::lookupTable_ protected
Definition at line 38 of file TableLookupOsc.h.
modFrames_
TonicFrames Tonic::Tonic_::TableLookupOsc_::modFrames_ protected
Definition at line 43 of file TableLookupOsc.h.
phase_
double Tonic::Tonic_::TableLookupOsc_::phase_ protected
Definition at line 40 of file TableLookupOsc.h.
The documentation for this class was generated from the following files:
TableLookupOsc.h
TableLookupOsc.cpp