YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::FilteredFBCombFilter6_ Class Reference
Tonic::Tonic_::FilteredFBCombFilter6_ Class Reference
Feedback comb filter with 6dB/oct (one-pole) lpf and hpf, optimized for reverb.
#include <CombFilter.h>
Public Member Functions
FilteredFBCombFilter6_ ()
void setLowCutoff (ControlGenerator gen)
void setHighCutoff (ControlGenerator gen)
Public Member Functions inherited from Tonic::Tonic_::CombFilter_
CombFilter_ ()
void initialize (float initialDelayTime, float maxDelayTime)
void setDelayTimeGen (Generator gen)
void setScaleFactorGen (ControlGenerator gen)
Public Member Functions inherited from Tonic::Tonic_::Effect_
Effect_ ()
void setBypassCtrlGen (ControlGenerator gen)
virtual void setInput (Generator input)
virtual void setIsStereoInput (bool stereo)
set stereo/mono - changes number of channels in dryFrames_
bool isStereoInput ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
virtual void tickThrough (TonicFrames &inFrames, TonicFrames &outFrames, const SynthesisContext_ &context)
Apply effect directly to passed in frames (output in-place)
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
TonicFloat lastOutLow_
TonicFloat lastOutHigh_
ControlGenerator lowCutoffGen_
ControlGenerator highCutoffGen_
ControlGenerator scaleFactorGen_
Protected Attributes inherited from Tonic::Tonic_::CombFilter_
DelayLine delayLine_
Generator delayTimeGen_
ControlGenerator scaleFactorCtrlGen_
TonicFrames delayTimeFrames_
Protected Attributes inherited from Tonic::Tonic_::Effect_
Generator input_
TonicFrames dryFrames_
ControlGenerator bypassGen_
bool isStereoInput_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Feedback comb filter with 6dB/oct (one-pole) lpf and hpf, optimized for reverb.
Definition at line 103 of file CombFilter.h.
Constructor & Destructor Documentation
FilteredFBCombFilter6_()
Tonic::Tonic_::FilteredFBCombFilter6_::FilteredFBCombFilter6_ ()
Definition at line 25 of file CombFilter.cpp.
References Tonic::Tonic_::CombFilter_::delayLine_, and Tonic::DelayLine::setInterpolates().
                                                  : lastOutLow_(0), lastOutHigh_(0)
   {
     // don't care about interpolation here, since this is optimized for reverb (faster)
     delayLine_.setInterpolates(false);
   }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::FilteredFBCombFilter6_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 127 of file CombFilter.h.
References Tonic::DelayLine::advance(), Tonic::cutoffToOnePoleCoef(), Tonic::Tonic_::CombFilter_::delayLine_, Tonic::Tonic_::CombFilter_::delayTimeFrames_, Tonic::Tonic_::CombFilter_::delayTimeGen_, Tonic::Tonic_::Effect_::dryFrames_, highCutoffGen_, Tonic::kSynthesisBlockSize, lastOutHigh_, lastOutLow_, lowCutoffGen_, Tonic::onePoleHPFTick(), Tonic::onePoleLPFTick(), Tonic::Tonic_::Generator_::outputFrames_, Tonic::Tonic_::CombFilter_::scaleFactorCtrlGen_, Tonic::Generator::tick(), Tonic::ControlGenerator::tick(), Tonic::DelayLine::tickIn(), Tonic::DelayLine::tickOut(), and Tonic::ControlGeneratorOutput::value.
{
       // tick modulations
       delayTimeGen_.tick(delayTimeFrames_, context);
       TonicFloat y = 0;
       TonicFloat * inptr = &dryFrames_[0];
       TonicFloat * outptr = &outputFrames_[0];
       TonicFloat * dtptr = &delayTimeFrames_[0];
       TonicFloat sf = scaleFactorCtrlGen_.tick(context).value;
       TonicFloat lowCoef = cutoffToOnePoleCoef(lowCutoffGen_.tick(context).value);
       TonicFloat hiCoef = 1.0f - cutoffToOnePoleCoef(highCutoffGen_.tick(context).value);
       for (unsigned int i=0; i<kSynthesisBlockSize; i++){
         onePoleLPFTick(delayLine_.tickOut(*dtptr++), lastOutLow_, lowCoef);
         onePoleHPFTick(lastOutLow_, lastOutHigh_, hiCoef);
         y = ((lastOutHigh_ * sf) + *inptr++); // no normalization on purpose
         delayLine_.tickIn(y);
         *outptr++ = y;
         delayLine_.advance();
       }
     }
setHighCutoff()
void Tonic::Tonic_::FilteredFBCombFilter6_::setHighCutoff (ControlGenerator gen) inline
Definition at line 123 of file CombFilter.h.
References highCutoffGen_.
 { highCutoffGen_ = gen; };
setLowCutoff()
void Tonic::Tonic_::FilteredFBCombFilter6_::setLowCutoff (ControlGenerator gen) inline
Definition at line 122 of file CombFilter.h.
References lowCutoffGen_.
 { lowCutoffGen_ = gen; };
Member Data Documentation
highCutoffGen_
ControlGenerator Tonic::Tonic_::FilteredFBCombFilter6_::highCutoffGen_ protected
Definition at line 111 of file CombFilter.h.
lastOutHigh_
TonicFloat Tonic::Tonic_::FilteredFBCombFilter6_::lastOutHigh_ protected
Definition at line 108 of file CombFilter.h.
lastOutLow_
TonicFloat Tonic::Tonic_::FilteredFBCombFilter6_::lastOutLow_ protected
Definition at line 107 of file CombFilter.h.
lowCutoffGen_
ControlGenerator Tonic::Tonic_::FilteredFBCombFilter6_::lowCutoffGen_ protected
Definition at line 110 of file CombFilter.h.
scaleFactorGen_
ControlGenerator Tonic::Tonic_::FilteredFBCombFilter6_::scaleFactorGen_ protected
Definition at line 113 of file CombFilter.h.
The documentation for this class was generated from the following files:
CombFilter.h
CombFilter.cpp