YOURPROJECTNAMEGOESHERE: Tonic::TonicFrames Class Reference
Tonic::TonicFrames Class Reference
#include <TonicFrames.h>
Public Member Functions
TonicFrames (unsigned int nFrames=0, unsigned int nChannels=0)
The default constructor initializes the frame data structure to size zero.
TonicFrames (const TonicFloat &value, unsigned int nFrames, unsigned int nChannels)
Overloaded constructor that initializes the frame data to the specified size with value.
virtual ~TonicFrames ()
The destructor.
TonicFrames (const TonicFrames &f)
TonicFrames & operator= (const TonicFrames &f)
TonicFloat & operator[] (size_t n)
Subscript operator that returns a reference to element n of self.
TonicFloat operator[] (size_t n) const
Subscript operator that returns the value at element n of self.
void operator+= (TonicFrames &f)
Assignment by sum operator into self.
void operator-= (TonicFrames &f)
void operator*= (TonicFrames &f)
Assignment by product operator into self.
void operator/= (TonicFrames &f)
TonicFloat & operator() (size_t frame, unsigned int channel)
Channel / frame subscript operator that returns a reference.
TonicFloat operator() (size_t frame, unsigned int channel) const
Channel / frame subscript operator that returns a value.
void copyChannel (unsigned int src, unsigned int dst)
Copy one channel to another.
void fillChannels ()
Fill all channels with contents of channel 0.
void clear ()
clear the frames data
void copy (TonicFrames &f)
Fill frames from other source.
TonicFloat interpolate (TonicFloat frame, unsigned int channel=0) const
Return an interpolated value at the fractional frame index and channel.
size_t size () const
Returns the total number of audio samples represented by the object.
bool empty () const
Returns true if the object size is zero and false otherwise.
void resize (size_t nFrames, unsigned int nChannels=1)
Resize self to represent the specified number of channels and frames.
void resize (size_t nFrames, unsigned int nChannels, TonicFloat value)
Resize self to represent the specified number of channels and frames and perform element initialization.
void resample (size_t nFrames, unsigned int nChannels)
Resize and stretch/shrink existing data to fit new size.
unsigned int channels (void) const
Return the number of channels represented by the data.
unsigned long frames (void) const
Return the number of sample frames represented by the data.
void setDataRate (TonicFloat rate)
Set the sample rate associated with the TonicFrames data.
TonicFloat dataRate (void) const
Return the sample rate associated with the TonicFrames data.
Protected Attributes
TonicFloat * data_
TonicFloat dataRate_
size_t nFrames_
unsigned int nChannels_
size_t size_
size_t bufferSize_
Detailed Description
Definition at line 26 of file TonicFrames.h.
Constructor & Destructor Documentation
TonicFrames() [1/3]
Tonic::TonicFrames::TonicFrames (unsigned int nFrames = 0, unsigned int nChannels = 0)
The default constructor initializes the frame data structure to size zero.
Definition at line 17 of file TonicFrames.cpp.
References bufferSize_, data_, dataRate_, Tonic::error(), nChannels_, nFrames_, Tonic::sampleRate(), and size_.
   : nFrames_( nFrames ), nChannels_( nChannels )
 {
   if (nChannels_ > 2){
     error("Invalid number of channels. TonicFrames is limited to mono or stereo only (1 or 2 channels)", true);
   }
   size_ = nFrames_ * nChannels_;
   bufferSize_ = size_;
   if ( size_ > 0 ) {
     data_ = (TonicFloat *) calloc( size_, sizeof( TonicFloat ) );
 #if defined(TONIC_DEBUG)
     if ( data_ == NULL ) {
       std::string error = "TonicFrames: memory allocation error in constructor!";
       Tonic::error(error, true);
     }
 #endif
   }
   else data_ = 0;
   dataRate_ = Tonic::sampleRate();
 }
TonicFrames() [2/3]
Tonic::TonicFrames::TonicFrames (const TonicFloat & value, unsigned int nFrames, unsigned int nChannels)
Overloaded constructor that initializes the frame data to the specified size with value.
Definition at line 41 of file TonicFrames.cpp.
References bufferSize_, data_, dataRate_, Tonic::error(), nChannels_, nFrames_, Tonic::sampleRate(), and size_.
   : nFrames_( nFrames ), nChannels_( nChannels )
 {
   if (nChannels_ > 2){
     error("Invalid number of channels. TonicFrames is limited to mono or stereo only (1 or 2 channels)", true);
   }
   size_ = nFrames_ * nChannels_;
   bufferSize_ = size_;
   if ( size_ > 0 ) {
     data_ = (TonicFloat *) malloc( size_ * sizeof( TonicFloat ) );
 #if defined(TONIC_DEBUG)
     if ( data_ == NULL ) {
       std::string error = "TonicFrames: memory allocation error in constructor!";
       Tonic::error(error, true);
     }
 #endif
     for ( long i=0; i<(long)size_; i++ ) data_[i] = value;
   }
   else data_ = 0;
   dataRate_ = Tonic::sampleRate();
 }
~TonicFrames()
Tonic::TonicFrames::~TonicFrames () virtual
The destructor.
Definition at line 65 of file TonicFrames.cpp.
References data_.
 {
   if ( data_ ) free( data_ );
 }
TonicFrames() [3/3]
Tonic::TonicFrames::TonicFrames (const TonicFrames & f)
Definition at line 70 of file TonicFrames.cpp.
References channels(), data_, dataRate_, frames(), resize(), Tonic::sampleRate(), and size_.
   : size_(0), bufferSize_(0)
 {
   resize( f.frames(), f.channels() );
   dataRate_ = Tonic::sampleRate();
   for ( unsigned int i=0; i<size_; i++ ) data_[i] = f[i];
 }
Member Function Documentation
channels()
unsigned int Tonic::TonicFrames::channels (void) const inline
Return the number of channels represented by the data.
Definition at line 163 of file TonicFrames.h.
References nChannels_.
 { return nChannels_; };
clear()
void Tonic::TonicFrames::clear () inline
clear the frames data
Definition at line 269 of file TonicFrames.h.
References data_, and size_.
{
     memset(data_, 0, size_ * sizeof(TonicFloat));
   }
copy()
void Tonic::TonicFrames::copy (TonicFrames & f) inline
Fill frames from other source.
Copies channels from one object to another. Frame count must match. If source has more channels than destination, they will be averaged. If destination has more channels than source, they will be copied to all channels.
Definition at line 273 of file TonicFrames.h.
References channels(), data_, Tonic::error(), fillChannels(), frames(), nChannels_, nFrames_, size_, and Tonic::vcopy().
{
 #if defined(TONIC_DEBUG)
     if ( f.frames() != nFrames_) {
       std::ostringstream error;
       error << "TonicFrames::operator+=: frames argument must be of equal dimensions!";
       Tonic::error(error.str(), true);
     }
 #endif
     unsigned int fChannels = f.channels();
     TonicFloat *dptr = data_;
     TonicFloat *fptr = &f[0];
     if (nChannels_ == fChannels){
       memcpy(dptr, fptr, size_ * sizeof(TonicFloat));
     }
     else if (nChannels_ < fChannels){
       // sum channels
       memset(dptr, 0, size_ * sizeof(TonicFloat));
       for (unsigned int c=0; c<fChannels; c++){
         dptr = data_;
         fptr = &f(0,c);
         for (unsigned int i=0; i<nFrames_; i++, dptr+=nChannels_, fptr+=fChannels){
           *dptr += *fptr;
         }
       }
       // apply scaling (average of channels)
       TonicFloat s = 1.0f/fChannels;
       dptr = data_;
       for (unsigned int i=0; i<nFrames_; i++, dptr+=nChannels_){
         *dptr *= s;
       }
     }
     else{
       // just copy one channel, then fill
       vcopy(dptr, nChannels_, fptr, fChannels, (unsigned int)nFrames_);
       // fill all channels if necessary
       fillChannels();
     }
   }
copyChannel()
void Tonic::TonicFrames::copyChannel (unsigned int src, unsigned int dst) inline
Copy one channel to another.
The src and dst indices must be between 0 and channels() - 1, and should not be the same number. No range checking is performed (yet)
Definition at line 251 of file TonicFrames.h.
References data_, nChannels_, nFrames_, and Tonic::vcopy().
   {
     TonicFloat *sptr = data_ + src;
     TonicFloat *dptr = data_ + dst;
     unsigned int stride = nChannels_;
     vcopy(dptr, stride, sptr, stride, (unsigned int)nFrames_);
   }
dataRate()
TonicFloat Tonic::TonicFrames::dataRate (void) const inline
Return the sample rate associated with the TonicFrames data.
By default, this value is set equal to the current STK sample rate at the time of instantiation.
Definition at line 180 of file TonicFrames.h.
References dataRate_.
 { return dataRate_; };
empty()
bool Tonic::TonicFrames::empty () const inline
Returns true if the object size is zero and false otherwise.
Definition at line 193 of file TonicFrames.h.
References size_.
   {
     if ( size_ > 0 ) return false;
     else return true;
   }
fillChannels()
void Tonic::TonicFrames::fillChannels () inline
Fill all channels with contents of channel 0.
Definition at line 262 of file TonicFrames.h.
References copyChannel(), and nChannels_.
   {
     for (unsigned int i=1; i<nChannels_; i++){
       this->copyChannel(0, i);
     }
   }
frames()
unsigned long Tonic::TonicFrames::frames (void) const inline
Return the number of sample frames represented by the data.
Definition at line 166 of file TonicFrames.h.
References nFrames_.
 { return nFrames_; };
interpolate()
TonicFloat Tonic::TonicFrames::interpolate (TonicFloat frame, unsigned int channel = 0) const
Return an interpolated value at the fractional frame index and channel.
This function performs linear interpolation. The frame index must be between 0.0 and frames() - 1. The channel index must be between 0 and channels() - 1. No range checking is performed unless TONIC_DEBUG is defined.
Definition at line 219 of file TonicFrames.cpp.
References data_, Tonic::error(), nChannels_, and nFrames_.
 {
 #if defined(TONIC_DEBUG)
   if ( frame < 0.0 || frame > (TonicFloat) ( nFrames_ - 1 ) || channel >= nChannels_ ) {
     std::ostringstream error;
     error << "TonicFrames::interpolate: invalid frame (" << frame << ") or channel (" << channel << ") value!";
     Tonic::error(error.str(), true);
   }
 #endif
   size_t iIndex = ( size_t ) frame;                    // integer part of index
   TonicFloat output, alpha = frame - (TonicFloat) iIndex;  // fractional part of index
   iIndex = iIndex * nChannels_ + channel;
   output = data_[ iIndex ];
   if ( alpha > 0.0 )
     output += ( alpha * ( data_[ iIndex + nChannels_ ] - output ) );
   return output;
 }
operator()() [1/2]
TonicFloat & Tonic::TonicFrames::operator() (size_t frame, unsigned int channel) inline
Channel / frame subscript operator that returns a reference.
The result can be used as an lvalue. This reference is valid until the resize function is called or the array is destroyed. The frame index must be between 0 and frames() - 1. The channel index must be between 0 and channels() - 1. No range checking is performed unless TONIC_DEBUG is defined.
Definition at line 225 of file TonicFrames.h.
References data_, Tonic::error(), nChannels_, and nFrames_.
   {
   #if defined(TONIC_DEBUG)
     if ( frame >= nFrames_ || channel >= nChannels_ ) {
       std::ostringstream error;
       error << "TonicFrames::operator(): invalid frame (" << frame << ") or channel (" << channel << ") value!";
       Tonic::error(error.str(), true);
     }
   #endif
     return data_[ frame * nChannels_ + channel ];
   }
operator()() [2/2]
TonicFloat Tonic::TonicFrames::operator() (size_t frame, unsigned int channel) const inline
Channel / frame subscript operator that returns a value.
The frame index must be between 0 and frames() - 1. The channel index must be between 0 and channels() - 1. No range checking is performed unless TONIC_DEBUG is defined.
Definition at line 238 of file TonicFrames.h.
References data_, Tonic::error(), nChannels_, and nFrames_.
   {
   #if defined(TONIC_DEBUG)
     if ( frame >= nFrames_ || channel >= nChannels_ ) {
       std::ostringstream error;
       error << "TonicFrames::operator(): invalid frame (" << frame << ") or channel (" << channel << ") value!";
       Tonic::error(error.str(), true);
     }
   #endif
     return data_[ frame * nChannels_ + channel ];
   }
operator*=()
void Tonic::TonicFrames::operator*= (TonicFrames & f) inline
Assignment by product operator into self.
The dimensions of the argument are expected to be the same as self. No range checking is performed unless TONIC_DEBUG is defined.
Definition at line 428 of file TonicFrames.h.
References channels(), data_, Tonic::error(), frames(), nChannels_, nFrames_, and size_.
   {
 #if defined(TONIC_DEBUG)
     if ( f.frames() != nFrames_) {
       std::ostringstream error;
       error << "TonicFrames::operator+=: frames argument must be of equal dimensions!";
       Tonic::error(error.str(), true);
     }
 #endif
     TonicFloat *fptr = &f[0];
     TonicFloat *dptr = data_;
     unsigned int fChannels = f.channels();
     if (nChannels_ == fChannels){
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vmul(dptr, 1, fptr, 1, dptr, 1, size_);
 #else
       for ( unsigned int i=0; i<size_; i++ ){
         *dptr++ *= *fptr++;
       }
 #endif
     }
     else if (nChannels_ < fChannels){
       //  just multiply by first channel of rhs
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vmul(dptr, 1, fptr, fChannels, dptr, 1, nFrames_);
 #else
       for ( unsigned int i=0; i<nFrames_; i++ ){
         *dptr++ *= *fptr++;
         fptr++;
       }
 #endif
     }
     else{
       //  multiply both channels by rhs
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vmul(dptr, 2, fptr, 1, dptr, 2, nFrames_);
       vDSP_vmul(dptr+1, 2, fptr, 1, dptr+1, 2, nFrames_);
 #else
       for ( unsigned int i=0; i<nFrames_; i++ ){
         *dptr++ *= *fptr;
         *dptr++ *= *fptr++;
       }
 #endif
     }
   }
operator+=()
void Tonic::TonicFrames::operator+= (TonicFrames & f) inline
Assignment by sum operator into self.
The dimensions of the argument are expected to be the same as self. No range checking is performed unless TONIC_DEBUG is defined.
Definition at line 319 of file TonicFrames.h.
References channels(), data_, Tonic::error(), frames(), nChannels_, nFrames_, and size_.
   {
   #if defined(TONIC_DEBUG)
     if ( f.frames() != nFrames_ ) {
       std::ostringstream error;
       error << "TonicFrames::operator+=: frames argument must be of equal dimensions!";
       Tonic::error(error.str(), true);
     }
   #endif
     TonicFloat *fptr = &f[0];
     TonicFloat *dptr = data_;
     unsigned int fChannels = f.channels();
     if (nChannels_ == fChannels){
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vadd(dptr, 1, fptr, 1, dptr, 1, size_);
 #else
       for ( unsigned int i=0; i<size_; i++ )
         *dptr++ += *fptr++;
 #endif
     }
     else if (nChannels_ < fChannels){
       //  just add first channel of rhs
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vadd(dptr, 1, fptr, fChannels, dptr, 1, nFrames_);
 #else
       for ( unsigned int i=0; i<nFrames_; i++ ){
         *dptr++ -= *fptr++;
         fptr++;
       }
 #endif
     }
     else{
       //  add rhs to both channels
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vadd(dptr, 2, fptr, 1, dptr, 2, nFrames_);
       vDSP_vadd(dptr+1, 2, fptr, 1, dptr+1, 2, nFrames_);
 #else
       for ( unsigned int i=0; i<nFrames_; i++ ){
         *dptr++ += *fptr;
         *dptr++ += *fptr++;
       }
 #endif
     }
   }
operator-=()
void Tonic::TonicFrames::operator-= (TonicFrames & f) inline
Definition at line 373 of file TonicFrames.h.
References channels(), data_, Tonic::error(), frames(), nChannels_, nFrames_, and size_.
   {
   #if defined(TONIC_DEBUG)
     if ( f.frames() != nFrames_ ) {
       std::ostringstream error;
       error << "TonicFrames::operator+=: frames argument must be of equal dimensions!";
       Tonic::error(error.str(), true);
     }
   #endif
     TonicFloat *fptr = &f[0];
     TonicFloat *dptr = data_;
     unsigned int fChannels = f.channels();
     if (nChannels_ == fChannels){
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vsub(fptr, 1, dptr, 1, dptr, 1, size_);
 #else
       for ( unsigned int i=0; i<size_; i++ )
         *dptr++ -= *fptr++;
 #endif
     }
     else if (nChannels_ < fChannels){
       //  just subtract first channel of rhs
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vsub(dptr, 1, fptr, fChannels, dptr, 1, nFrames_);
 #else
       for ( unsigned int i=0; i<nFrames_; i++ ){
         *dptr++ -= *fptr++;
         fptr++;
       }
 #endif
     }
     else{
       //  subtract both channels by rhs
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vsub(dptr, 2, fptr, 1, dptr, 2, nFrames_);
       vDSP_vsub(dptr+1, 2, fptr, 1, dptr+1, 2, nFrames_);
 #else
       for ( unsigned int i=0; i<nFrames_; i++ ){
         *dptr++ -= *fptr;
         *dptr++ -= *fptr++;
       }
 #endif
     }
   }
operator/=()
void Tonic::TonicFrames::operator/= (TonicFrames & f) inline
Definition at line 483 of file TonicFrames.h.
References channels(), data_, Tonic::error(), frames(), nChannels_, nFrames_, and size_.
   {
   #if defined(TONIC_DEBUG)
     if ( f.frames() != nFrames_ ) {
       std::ostringstream error;
       error << "TonicFrames::operator*=: frames argument must be of equal dimensions!";
       Tonic::error(error.str(), true);
     }
   #endif
     TonicFloat *fptr = &f[0];
     TonicFloat *dptr = data_;
     unsigned int fChannels = f.channels();
     if (nChannels_ == fChannels){
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vdiv(fptr, 1, dptr, 1, dptr, 1, size_);
 #else
       for ( unsigned int i=0; i<size_; i++ ){
         *dptr++ /= *fptr++;
       }
 #endif
     }
     else if (nChannels_ < fChannels){
       //  just multiply by first channel of rhs
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vdiv(fptr, fChannels, dptr, 1, dptr, 1, nFrames_);
 #else
       for ( unsigned int i=0; i<nFrames_; i++ ){
         *dptr++ /= *fptr++;
         fptr++;
       }
 #endif
     }
     else{
       //  multiply both channels by rhs
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vdiv(fptr, 2, dptr, 1, dptr, 2, nFrames_);
       vDSP_vdiv(fptr, 2, dptr+1, 1, dptr+1, 2, nFrames_);
 #else
       for ( unsigned int i=0; i<nFrames_; i++ ){
         *dptr++ /= *fptr;
         *dptr++ /= *fptr++;
       }
 #endif
     }
   }
operator=()
TonicFrames & Tonic::TonicFrames::operator= (const TonicFrames & f)
Definition at line 78 of file TonicFrames.cpp.
References bufferSize_, channels(), data_, dataRate_, frames(), resize(), Tonic::sampleRate(), and size_.
 {
   size_ = 0;
   bufferSize_ = 0;
   resize( f.frames(), f.channels() );
   dataRate_ = Tonic::sampleRate();
   for ( unsigned int i=0; i<size_; i++ ) data_[i] = f[i];
   return *this;
 }
operator[]() [1/2]
TonicFloat & Tonic::TonicFrames::operator[] (size_t n) inline
Subscript operator that returns a reference to element n of self.
The result can be used as an lvalue. This reference is valid until the resize function is called or the array is destroyed. The index n must be between 0 and size less one. No range checking is performed unless TONIC_DEBUG is defined.
Definition at line 199 of file TonicFrames.h.
References data_, Tonic::error(), and size_.
   {
   #if defined(TONIC_DEBUG)
     if ( n >= size_ ) {
       std::ostringstream error;
       error << "TonicFrames::operator[]: invalid index (" << n << ") value!";
       Tonic::error(error.str(), true);
     }
   #endif
     return data_[n];
   }
operator[]() [2/2]
TonicFloat Tonic::TonicFrames::operator[] (size_t n) const inline
Subscript operator that returns the value at element n of self.
The index n must be between 0 and size less one. No range checking is performed unless TONIC_DEBUG is defined.
Definition at line 212 of file TonicFrames.h.
References data_, Tonic::error(), and size_.
   {
   #if defined(TONIC_DEBUG)
     if ( n >= size_ ) {
       std::ostringstream error;
       error << "TonicFrames::operator[]: invalid index (" << n << ") value!";
       Tonic::error(error.str(), true);
     }
   #endif
     return data_[n];
   }
resample()
void Tonic::TonicFrames::resample (size_t nFrames, unsigned int nChannels)
Resize and stretch/shrink existing data to fit new size.
Definition at line 143 of file TonicFrames.cpp.
References bufferSize_, data_, Tonic::error(), nChannels_, nFrames_, and size_.
   {
     if (nChannels > 2){
       error("Invalid number of channels. TonicFrames is limited to mono or stereo only (1 or 2 channels)", true);
     }
     if (nFrames != nFrames_ || nChannels != nChannels_){
       // preserve as much of old data as we can
       TonicFloat * oldData = data_;
       unsigned long oldFrames = nFrames_;
       unsigned int oldchannels = nChannels_;
       nFrames_ = nFrames;
       nChannels_ = nChannels;
       size_ = nFrames_ * nChannels_;
       data_ = (TonicFloat *) malloc( size_ * sizeof( TonicFloat ) );
 #if defined(TONIC_DEBUG)
       if ( data_ == NULL ) {
         std::string error = "TonicFrames::resize: memory allocation error!";
         Tonic::error(error, true);
       }
 #endif
       // resample the content (brute-force, no AA applied)
       if (oldData){
         float inc = (float)oldFrames/nFrames_;
         for (unsigned int c=0; c<nChannels_; c++){
           float fIdx = 0.f;
           for (unsigned int i=0; i<nFrames_; i++){
             float fi, y1, y2;
             float frac = modff(fIdx, &fi);
             unsigned int idx = (unsigned int)fi;
             unsigned int ocIdx = oldchannels > 1 ? c : 0;
             if (idx == oldFrames-1){
               data_[i*nChannels_ + c] = oldData[idx * oldchannels + ocIdx];
             }
             else{
               y1 = oldData[idx * oldchannels + ocIdx];
               y2 = oldData[(idx+1) * oldchannels + ocIdx];
               data_[i*nChannels + c] = y1 + frac * (y2 - y1);
             }
             // handle different channel mapping
             if (oldchannels > nChannels_){
               // add and average
               y1 = oldData[idx * oldchannels + ocIdx + 1];
               y2 = oldData[(idx+1) * oldchannels + ocIdx + 1];
               data_[i*nChannels + c] += (y1 + frac * (y2 - y1));
               data_[i*nChannels + c] *= 0.5f;
             }
             fIdx += inc;
           }
         }
       }
       bufferSize_ = size_;
       if (oldData) free(oldData);
     }
   }
resize() [1/2]
void Tonic::TonicFrames::resize (size_t nFrames, unsigned int nChannels = 1)
Resize self to represent the specified number of channels and frames.
Changes the size of self based on the number of frames and channels. No element assignment is performed. No memory deallocation occurs if the new size is smaller than the previous size. Further, no new memory is allocated when the new size is smaller or equal to a previously allocated size.
Definition at line 88 of file TonicFrames.cpp.
References bufferSize_, data_, Tonic::error(), nChannels_, nFrames_, and size_.
 {
   if (nChannels > 2){
     error("Invalid number of channels. TonicFrames is limited to mono or stereo only (1 or 2 channels)", true);
   }
   if (nFrames != nFrames_ || nChannels != nChannels_){
     nFrames_ = nFrames;
     nChannels_ = nChannels;
     // preserve as much of old data as we can
     TonicFloat * oldData = data_;
     unsigned long oldSize = size_;
     size_ = nFrames_ * nChannels_;
     if ( size_ > bufferSize_ ) {
       data_ = (TonicFloat *) malloc( size_ * sizeof( TonicFloat ) );
       if (oldData){
         for (unsigned int i=0; i<oldSize; i++){
           data_[i] = oldData[i];
         }
       }
 #if defined(TONIC_DEBUG)
       if ( data_ == NULL ) {
         std::string error = "TonicFrames::resize: memory allocation error!";
         Tonic::error(error, true);
       }
 #endif
       bufferSize_ = size_;
       if (oldData) free(oldData);
     }
   }
 }
resize() [2/2]
void Tonic::TonicFrames::resize (size_t nFrames, unsigned int nChannels, TonicFloat value)
Resize self to represent the specified number of channels and frames and perform element initialization.
Changes the size of self based on the number of frames and channels, and assigns value to every element. No memory deallocation occurs if the new size is smaller than the previous size. Further, no new memory is allocated when the new size is smaller or equal to a previously allocated size.
Definition at line 131 of file TonicFrames.cpp.
References data_, resize(), and size_.
 {
   this->resize( nFrames, nChannels );
 #ifdef USE_APPLE_ACCELERATE
   vDSP_vfill(&value, data_, 1, size_);
 #else
   for ( size_t i=0; i<size_; i++ ) data_[i] = value;
 #endif
 }
setDataRate()
void Tonic::TonicFrames::setDataRate (TonicFloat rate) inline
Set the sample rate associated with the TonicFrames data.
By default, this value is set equal to the current STK sample rate at the time of instantiation.
Definition at line 173 of file TonicFrames.h.
References dataRate_.
 { dataRate_ = rate; };
size()
size_t Tonic::TonicFrames::size () const inline
Returns the total number of audio samples represented by the object.
Definition at line 133 of file TonicFrames.h.
References size_.
 { return size_; };
Member Data Documentation
bufferSize_
size_t Tonic::TonicFrames::bufferSize_ protected
Definition at line 189 of file TonicFrames.h.
data_
TonicFloat* Tonic::TonicFrames::data_ protected
Definition at line 180 of file TonicFrames.h.
dataRate_
TonicFloat Tonic::TonicFrames::dataRate_ protected
Definition at line 185 of file TonicFrames.h.
nChannels_
unsigned int Tonic::TonicFrames::nChannels_ protected
Definition at line 187 of file TonicFrames.h.
nFrames_
size_t Tonic::TonicFrames::nFrames_ protected
Definition at line 186 of file TonicFrames.h.
size_
size_t Tonic::TonicFrames::size_ protected
Definition at line 188 of file TonicFrames.h.
The documentation for this class was generated from the following files:
TonicFrames.h
TonicFrames.cpp