YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::RingBufferWriter_ Class Reference
Tonic::Tonic_::RingBufferWriter_ Class Reference
#include <RingBuffer.h>
Public Member Functions
~RingBufferWriter_ ()
void initRingBuffer (string name, unsigned int nFrames, unsigned int nChannels)
void write (float *data, unsigned int nFrames, unsigned int nChannels)
void reset ()
Protected Attributes
RingBuffer ringBuffer_
string tableName_
Detailed Description
Definition at line 216 of file RingBuffer.h.
Constructor & Destructor Documentation
~RingBufferWriter_()
Tonic::Tonic_::RingBufferWriter_::~RingBufferWriter_ ()
Definition at line 23 of file RingBuffer.cpp.
References Tonic::s_RingBuffers_, and tableName_.
{
       s_RingBuffers_.removeObjectNamed(tableName_);
     }
Member Function Documentation
initRingBuffer()
void Tonic::Tonic_::RingBufferWriter_::initRingBuffer (string name, unsigned int nFrames, unsigned int nChannels)
Definition at line 27 of file RingBuffer.cpp.
References ringBuffer_, Tonic::s_RingBuffers_, and Tonic::warning().
{
       RingBuffer table = RingBuffer(nFrames, nChannels);
       // overwrite existing entry if there is one
 #ifdef TONIC_DEBUG
       if (s_RingBuffers_.containsObjectNamed(name)){
         warning("There is already a ring buffer named " + name + " open for writing. It will be replaced with this one.");
       }
 #endif
       s_RingBuffers_.insertObject(name, table);
       ringBuffer_ = table;
     }
reset()
void Tonic::Tonic_::RingBufferWriter_::reset ()
Definition at line 42 of file RingBuffer.cpp.
References Tonic::RingBuffer::reset(), and ringBuffer_.
     {
       ringBuffer_.reset();
     }
write()
void Tonic::Tonic_::RingBufferWriter_::write (float * data, unsigned int nFrames, unsigned int nChannels) inline
Definition at line 233 of file RingBuffer.h.
References ringBuffer_, and Tonic::RingBuffer::write().
     {
       ringBuffer_.write(data, nFrames, nChannels);
     }
Member Data Documentation
ringBuffer_
RingBuffer Tonic::Tonic_::RingBufferWriter_::ringBuffer_ protected
Definition at line 220 of file RingBuffer.h.
tableName_
string Tonic::Tonic_::RingBufferWriter_::tableName_ protected
Definition at line 221 of file RingBuffer.h.
The documentation for this class was generated from the following files:
RingBuffer.h
RingBuffer.cpp