YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::Compressor_ Class Reference
Tonic::Tonic_::Compressor_ Class Reference
#include <CompressorLimiter.h>
Public Member Functions
Compressor_ ()
void setInput (Generator input)
void tick (TonicFrames &frames, const SynthesisContext_ &context)
void tickThrough (TonicFrames &inFrames, TonicFrames &outFrames, const SynthesisContext_ &context)
Apply effect directly to passed in frames (output in-place)
void setAudioInput (Generator gen)
void setAmplitudeInput (Generator gen)
void setMakeupGain (ControlGenerator gen)
void setAttack (ControlGenerator gen)
void setRelease (ControlGenerator gen)
void setThreshold (ControlGenerator gen)
void setRatio (ControlGenerator gen)
void setLookahead (ControlGenerator gen)
void setIsLimiter (bool isLimiter)
Set whether is a limiter - limiters will hard clip to threshold in worst case.
void setIsStereo (bool isStereo)
Externally set whether operates on one or two channels.
Public Member Functions inherited from Tonic::Tonic_::Effect_
Effect_ ()
void setBypassCtrlGen (ControlGenerator gen)
virtual void setIsStereoInput (bool stereo)
set stereo/mono - changes number of channels in dryFrames_
bool isStereoInput ()
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
Generator amplitudeInput_
ControlGenerator makeupGainGen_
ControlGenerator attackGen_
ControlGenerator releaseGen_
ControlGenerator threshGen_
ControlGenerator ratioGen_
ControlGenerator lookaheadGen_
DelayLine lookaheadDelayLine_
TonicFrames ampInputFrames_
TonicFloat ampEnvValue_
TonicFloat gainEnvValue_
bool isLimiter_
Protected Attributes inherited from Tonic::Tonic_::Effect_
Generator input_
TonicFrames dryFrames_
ControlGenerator bypassGen_
bool isStereoInput_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 23 of file CompressorLimiter.h.
Constructor & Destructor Documentation
Compressor_()
Tonic::Tonic_::Compressor_::Compressor_ ()
Definition at line 13 of file CompressorLimiter.cpp.
References ampInputFrames_, Tonic::DelayLine::initialize(), Tonic::kSynthesisBlockSize, lookaheadDelayLine_, makeupGainGen_, Tonic::TonicFrames::resize(), and Tonic::DelayLine::setInterpolates().
                            : isLimiter_(false), gainEnvValue_(1.f), ampEnvValue_(0) {
     ampInputFrames_.resize(kSynthesisBlockSize, 1, 0);
     lookaheadDelayLine_.initialize(0.01, 2);
     lookaheadDelayLine_.setInterpolates(false); // No real need to interpolate here for lookahead
     makeupGainGen_ = ControlValue(1.f);
   }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::Compressor_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 90 of file CompressorLimiter.h.
References Tonic::DelayLine::advance(), ampEnvValue_, ampInputFrames_, attackGen_, Tonic::TonicFrames::channels(), Tonic::clamp(), Tonic::Tonic_::Effect_::dryFrames_, gainEnvValue_, isLimiter_, Tonic::kSynthesisBlockSize, lookaheadDelayLine_, lookaheadGen_, makeupGainGen_, Tonic::max(), Tonic::onePoleLPFTick(), Tonic::Tonic_::Generator_::outputFrames_, ratioGen_, releaseGen_, Tonic::TonicFrames::size(), Tonic::t60ToOnePoleCoef(), threshGen_, Tonic::ControlGenerator::tick(), Tonic::DelayLine::tickIn(), Tonic::DelayLine::tickOut(), and Tonic::ControlGeneratorOutput::value.
{
       // Tick all scalar parameters
       float attackCoef = t60ToOnePoleCoef(max(0,attackGen_.tick(context).value));
       float releaseCoef = t60ToOnePoleCoef(max(0, releaseGen_.tick(context).value));
       float threshold = max(0,threshGen_.tick(context).value);
       float ratio = max(0,ratioGen_.tick(context).value);
       float lookaheadTime = max(0,lookaheadGen_.tick(context).value);
       // Absolute value of amplitude frames in prep for amp envelope
       TonicFloat * ampData = &ampInputFrames_[0];
       #ifdef USE_APPLE_ACCELERATE
       vDSP_vabs(ampData, 1, ampData, 1, ampInputFrames_.size());
       #else
       for (unsigned int i=0; i<ampInputFrames_.size(); i++, ampData++){
         *ampData = fabsf(*ampData);
       }
       #endif
       // Iterate through samples
       unsigned int nChannels = outputFrames_.channels();
       TonicFloat ampInputValue, gainValue, gainTarget;
       TonicFloat * outptr = &outputFrames_[0];
       TonicFloat * dryptr = &dryFrames_[0];
       ampData = &ampInputFrames_[0];
       for (unsigned int i=0; i<kSynthesisBlockSize; i++){
         // Tick input into lookahead delay and get amplitude input value - max of left/right
         ampInputValue = 0;
         for (unsigned int i=0; i<nChannels; i++){
           lookaheadDelayLine_.tickIn(*dryptr++, i);
           ampInputValue = max(ampInputValue,*ampData++);
         }
         // Smooth amplitude input
         if (ampInputValue >= ampEnvValue_){
           onePoleLPFTick(ampInputValue, ampEnvValue_, attackCoef);
         }
         else {
           onePoleLPFTick(ampInputValue, ampEnvValue_, releaseCoef);
         }
         // Calculate gain value
         if (ampEnvValue_ <= threshold){
           gainValue = 1.0f;
         }
         else{
           // compensate for ratio
           gainTarget = threshold + ((ampEnvValue_ - threshold)/ratio);
           gainValue = gainTarget/ampEnvValue_;
         }
         // Smooth gain value
         if (gainValue <= gainEnvValue_){
           onePoleLPFTick(gainValue, gainEnvValue_, attackCoef);
         }
         else {
           onePoleLPFTick(gainValue, gainEnvValue_, releaseCoef);
         }
         // apply gain
         for (unsigned int i=0; i<nChannels; i++){
           *outptr++ = lookaheadDelayLine_.tickOut(lookaheadTime,i) * gainEnvValue_;
         }
         lookaheadDelayLine_.advance();
       }
       TonicFloat makeupGain = max(0.f, makeupGainGen_.tick(context).value);
       outptr = &outputFrames_[0];
       #ifdef USE_APPLE_ACCELERATE
       vDSP_vsmul(outptr, 1, &makeupGain, outptr, 1, outputFrames_.size());
       #else
       for (unsigned int i=0; i<outputFrames_.size(); i++){
         *outptr++ *= makeupGain;
       }
       #endif
       if (isLimiter_){
         // clip to threshold in worst case (minor distortion introduced but much preferable to wrapping distortion)
         #ifdef USE_APPLE_ACCELERATE
         float negThresh = -threshold;
         vDSP_vclip(&outputFrames_[0], 1, &negThresh, &threshold, &outputFrames_[0], 1, outputFrames_.size());
         #else
         outptr = &outputFrames_[0];
         for (unsigned int i=0; i<outputFrames_.size(); i++, outptr++){
           *outptr = clamp(*outptr, -threshold, threshold);
         }
         #endif
       }
     }
setAmplitudeInput()
void Tonic::Tonic_::Compressor_::setAmplitudeInput (Generator gen)
Definition at line 33 of file CompressorLimiter.cpp.
References ampInputFrames_, amplitudeInput_, Tonic::Generator::isStereoOutput(), Tonic::kSynthesisBlockSize, and Tonic::TonicFrames::resize().
{
     amplitudeInput_ = gen;
     ampInputFrames_.resize(kSynthesisBlockSize, amplitudeInput_.isStereoOutput() ? 2 : 1, 0);
   }
setAttack()
void Tonic::Tonic_::Compressor_::setAttack (ControlGenerator gen) inline
Definition at line 62 of file CompressorLimiter.h.
References attackGen_.
 { attackGen_ = gen; };
setAudioInput()
void Tonic::Tonic_::Compressor_::setAudioInput (Generator gen)
Definition at line 27 of file CompressorLimiter.cpp.
References Tonic::Tonic_::Effect_::input_, Tonic::Generator::isStereoOutput(), Tonic::Tonic_::Effect_::setIsStereoInput(), and Tonic::Tonic_::Generator_::setIsStereoOutput().
{
     input_ = gen;
     setIsStereoInput(gen.isStereoOutput());
     setIsStereoOutput(gen.isStereoOutput());
   }
setInput()
void Tonic::Tonic_::Compressor_::setInput (Generator input) virtual
Reimplemented from Tonic::Tonic_::Effect_.
Definition at line 22 of file CompressorLimiter.cpp.
References setAmplitudeInput(), and setAudioInput().
{
     setAmplitudeInput(input);
     setAudioInput(input);
   }
setIsLimiter()
void Tonic::Tonic_::Compressor_::setIsLimiter (bool isLimiter) inline
Set whether is a limiter - limiters will hard clip to threshold in worst case.
Definition at line 69 of file CompressorLimiter.h.
References isLimiter_.
 { isLimiter_ = isLimiter; };
setIsStereo()
void Tonic::Tonic_::Compressor_::setIsStereo (bool isStereo)
Externally set whether operates on one or two channels.
Definition at line 38 of file CompressorLimiter.cpp.
References ampInputFrames_, Tonic::kSynthesisBlockSize, Tonic::TonicFrames::resize(), Tonic::Tonic_::Effect_::setIsStereoInput(), and Tonic::Tonic_::Generator_::setIsStereoOutput().
{
     setIsStereoInput(isStereo);
     setIsStereoOutput(isStereo);
     ampInputFrames_.resize(kSynthesisBlockSize, isStereo ? 2 : 1, 0);
   }
setLookahead()
void Tonic::Tonic_::Compressor_::setLookahead (ControlGenerator gen) inline
Definition at line 66 of file CompressorLimiter.h.
References lookaheadGen_.
 { lookaheadGen_ = gen; };
setMakeupGain()
void Tonic::Tonic_::Compressor_::setMakeupGain (ControlGenerator gen) inline
Definition at line 61 of file CompressorLimiter.h.
References makeupGainGen_.
 { makeupGainGen_ = gen; };
setRatio()
void Tonic::Tonic_::Compressor_::setRatio (ControlGenerator gen) inline
Definition at line 65 of file CompressorLimiter.h.
References ratioGen_.
 { ratioGen_ = gen; };
setRelease()
void Tonic::Tonic_::Compressor_::setRelease (ControlGenerator gen) inline
Definition at line 63 of file CompressorLimiter.h.
References releaseGen_.
 { releaseGen_ = gen; };
setThreshold()
void Tonic::Tonic_::Compressor_::setThreshold (ControlGenerator gen) inline
Definition at line 64 of file CompressorLimiter.h.
References threshGen_.
 { threshGen_ = gen; };
tick()
void Tonic::Tonic_::Compressor_::tick (TonicFrames & frames, const SynthesisContext_ & context) inline virtual
Reimplemented from Tonic::Tonic_::Effect_.
Definition at line 76 of file CompressorLimiter.h.
References ampInputFrames_, amplitudeInput_, Tonic::Tonic_::SynthesisContext_::elapsedFrames, Tonic::Tonic_::SynthesisContext_::forceNewOutput, Tonic::Tonic_::Generator_::lastFrameIndex_, Tonic::Tonic_::Effect_::tick(), and Tonic::Generator::tick().
{
       if (context.forceNewOutput || lastFrameIndex_ != context.elapsedFrames){
         amplitudeInput_.tick(ampInputFrames_, context); // get amp input frames
       }
       Effect_::tick(frames, context);
     }
tickThrough()
void Tonic::Tonic_::Compressor_::tickThrough (TonicFrames & inFrames, TonicFrames & outFrames, const SynthesisContext_ & context) inline virtual
Apply effect directly to passed in frames (output in-place)
DO NOT mix calls to tick() with calls to tickThrough().
Reimplemented from Tonic::Tonic_::Effect_.
Definition at line 85 of file CompressorLimiter.h.
References ampInputFrames_, Tonic::TonicFrames::copy(), and Tonic::Tonic_::Effect_::tickThrough().
{
       ampInputFrames_.copy(inFrames);
       Effect_::tickThrough(inFrames, outFrames, context);
     }
Member Data Documentation
ampEnvValue_
TonicFloat Tonic::Tonic_::Compressor_::ampEnvValue_ protected
Definition at line 41 of file CompressorLimiter.h.
ampInputFrames_
TonicFrames Tonic::Tonic_::Compressor_::ampInputFrames_ protected
Definition at line 39 of file CompressorLimiter.h.
amplitudeInput_
Generator Tonic::Tonic_::Compressor_::amplitudeInput_ protected
Definition at line 28 of file CompressorLimiter.h.
attackGen_
ControlGenerator Tonic::Tonic_::Compressor_::attackGen_ protected
Definition at line 31 of file CompressorLimiter.h.
gainEnvValue_
TonicFloat Tonic::Tonic_::Compressor_::gainEnvValue_ protected
Definition at line 42 of file CompressorLimiter.h.
isLimiter_
bool Tonic::Tonic_::Compressor_::isLimiter_ protected
Definition at line 44 of file CompressorLimiter.h.
lookaheadDelayLine_
DelayLine Tonic::Tonic_::Compressor_::lookaheadDelayLine_ protected
Definition at line 37 of file CompressorLimiter.h.
lookaheadGen_
ControlGenerator Tonic::Tonic_::Compressor_::lookaheadGen_ protected
Definition at line 35 of file CompressorLimiter.h.
makeupGainGen_
ControlGenerator Tonic::Tonic_::Compressor_::makeupGainGen_ protected
Definition at line 30 of file CompressorLimiter.h.
ratioGen_
ControlGenerator Tonic::Tonic_::Compressor_::ratioGen_ protected
Definition at line 34 of file CompressorLimiter.h.
releaseGen_
ControlGenerator Tonic::Tonic_::Compressor_::releaseGen_ protected
Definition at line 32 of file CompressorLimiter.h.
threshGen_
ControlGenerator Tonic::Tonic_::Compressor_::threshGen_ protected
Definition at line 33 of file CompressorLimiter.h.
The documentation for this class was generated from the following files:
CompressorLimiter.h
CompressorLimiter.cpp