YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::RectWave_ Class Reference
Tonic::Tonic_::RectWave_ Class Reference
Quick-and-dirty non-bandlimited rect wave.
#include <RectWave.h>
Public Member Functions
RectWave_ ()
void setFrequencyGenerator (Generator gen)
void setPwmGenerator (Generator gen)
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
Generator freqGen_
Generator pwmGen_
TonicFrames freqFrames_
TonicFrames pwmFrames_
double phaseAccum_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Quick-and-dirty non-bandlimited rect wave.
Definition at line 25 of file RectWave.h.
Constructor & Destructor Documentation
RectWave_()
Tonic::Tonic_::RectWave_::RectWave_ ()
Definition at line 13 of file RectWave.cpp.
References freqFrames_, Tonic::kSynthesisBlockSize, pwmFrames_, pwmGen_, and Tonic::TonicFrames::resize().
                        : phaseAccum_(0) {
     pwmGen_ = FixedValue(0.5);
     freqFrames_.resize(kSynthesisBlockSize, 1 ,0);
     pwmFrames_.resize(kSynthesisBlockSize, 1, 0);
   }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::RectWave_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 55 of file RectWave.h.
References BIT32DECPT, Tonic::FastPhasor::d, Tonic::TonicFrames::frames(), freqFrames_, freqGen_, Tonic::FastPhasor::i, Tonic::kSynthesisBlockSize, Tonic::Tonic_::Generator_::outputFrames_, phaseAccum_, pwmFrames_, pwmGen_, Tonic::sampleRate(), Tonic::Generator::tick(), and TONIC_RECT_RES.
{
       // tick freq and pwm
       freqGen_.tick(freqFrames_, context);
       pwmGen_.tick(pwmFrames_, context);
       const TonicFloat rateConstant =  TONIC_RECT_RES / Tonic::sampleRate();
       TonicFloat *outptr = &outputFrames_[0];
       TonicFloat *freqptr = &freqFrames_[0];
       TonicFloat *pwmptr = &pwmFrames_[0];
       FastPhasor sd;
       // pre-multiply rate constant for speed
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vsmul(freqptr, 1, &rateConstant, freqptr, 1, kSynthesisBlockSize);
 #else
       for (unsigned int i=0; i<kSynthesisBlockSize; i++){
         *freqptr++ *= rateConstant;
       }
       freqptr = &freqFrames_[0];
 #endif
       sd.d = BIT32DECPT;
       TonicInt32 offs, msbi = sd.i[1];
       double ps = phaseAccum_ + BIT32DECPT;
       for ( unsigned int i=0; i<outputFrames_.frames(); i++ ) {
         sd.d = ps;
         ps += *freqptr++;
         offs = sd.i[1] & (TONIC_RECT_RES-1);
         sd.i[1] = msbi;
         *outptr++ = offs > (TONIC_RECT_RES * *pwmptr++) ? -1.0f : 1.0f;
       }
       sd.d = BIT32DECPT * TONIC_RECT_RES;
       msbi = sd.i[1];
       sd.d = ps + (BIT32DECPT * TONIC_RECT_RES - BIT32DECPT);
       sd.i[1] = msbi;
       phaseAccum_ = sd.d - BIT32DECPT * TONIC_RECT_RES;
     }
setFrequencyGenerator()
void Tonic::Tonic_::RectWave_::setFrequencyGenerator (Generator gen) inline
Definition at line 44 of file RectWave.h.
References freqGen_.
{
           freqGen_ = gen;
         }
setPwmGenerator()
void Tonic::Tonic_::RectWave_::setPwmGenerator (Generator gen) inline
Definition at line 48 of file RectWave.h.
References pwmGen_.
{
           pwmGen_ = gen;
         }
Member Data Documentation
freqFrames_
TonicFrames Tonic::Tonic_::RectWave_::freqFrames_ protected
Definition at line 33 of file RectWave.h.
freqGen_
Generator Tonic::Tonic_::RectWave_::freqGen_ protected
Definition at line 30 of file RectWave.h.
phaseAccum_
double Tonic::Tonic_::RectWave_::phaseAccum_ protected
Definition at line 36 of file RectWave.h.
pwmFrames_
TonicFrames Tonic::Tonic_::RectWave_::pwmFrames_ protected
Definition at line 34 of file RectWave.h.
pwmGen_
Generator Tonic::Tonic_::RectWave_::pwmGen_ protected
Definition at line 31 of file RectWave.h.
The documentation for this class was generated from the following files:
RectWave.h
RectWave.cpp