YOURPROJECTNAMEGOESHERE: Tonic::Biquad Class Reference
Tonic::Biquad Class Reference
Biquad_ is an IIR biquad filter which provides a base object on which to build more advanced filters.
#include <FilterUtils.h>
Public Member Functions
Biquad ()
void setIsStereo (bool stereo)
void setCoefficients (TonicFloat b0, TonicFloat b1, TonicFloat b2, TonicFloat a1, TonicFloat a2)
Set the coefficients for the filtering operation.
void setCoefficients (TonicFloat *newCoef)
void filter (TonicFrames &inFrames, TonicFrames &outFrames)
Protected Attributes
TonicFloat coef_ [5]
TonicFrames inputVec_
TonicFrames outputVec_
Detailed Description
Biquad_ is an IIR biquad filter which provides a base object on which to build more advanced filters.
Definition at line 68 of file FilterUtils.h.
Constructor & Destructor Documentation
Biquad()
Tonic::Biquad::Biquad ()
Definition at line 11 of file FilterUtils.cpp.
References coef_, inputVec_, Tonic::kSynthesisBlockSize, outputVec_, and Tonic::TonicFrames::resize().
                 {
     memset(coef_, 0, 5 * sizeof(TonicFloat));
     inputVec_.resize(kSynthesisBlockSize + 4, 1, 0);
     outputVec_.resize(kSynthesisBlockSize + 4, 1, 0);
   }
Member Function Documentation
filter()
void Tonic::Biquad::filter (TonicFrames & inFrames, TonicFrames & outFrames) inline
Definition at line 110 of file FilterUtils.h.
References Tonic::TonicFrames::channels(), coef_, Tonic::error(), inputVec_, Tonic::kSynthesisBlockSize, outputVec_, and Tonic::TonicFrames::size().
{
     // initialize vectors
     memcpy(&inputVec_[0], &inputVec_(kSynthesisBlockSize, 0), 2 * inputVec_.channels() * sizeof(TonicFloat));
     memcpy(&inputVec_(2, 0), &inFrames[0], inFrames.size() * sizeof(TonicFloat));
     memcpy(&outputVec_[0], &outputVec_(kSynthesisBlockSize, 0), 2 * outputVec_.channels() * sizeof(TonicFloat));
     // perform IIR filter
     unsigned int stride = inFrames.channels();
 #ifdef USE_APPLE_ACCELERATE
     for (unsigned int c=0; c<stride; c++){
       vDSP_deq22(&inputVec_[0] + c, stride, coef_, &outputVec_[0] + c, stride, kSynthesisBlockSize);
     }
 #else
     for (unsigned int c=0; c<stride; c++){
       TonicFloat* in = &inputVec_(2, c);
       TonicFloat* out = &outputVec_(2, c);
       for (unsigned int i=0; i<kSynthesisBlockSize; i++){
         *out = *(in)*coef_[0] + *(in-stride)*coef_[1] + *(in-2*stride)*coef_[2] - *(out-stride)*coef_[3] - *(out-2*stride)*coef_[4];
         in += stride;
         out += stride;
       }
     }
 #endif
 #ifdef TONIC_DEBUG
     if(outFrames(0,0) != outFrames(0,0)){
       Tonic::error("Biquad::filter NaN detected.", false);
     }
 #endif
     // copy to synthesis block
     memcpy(&outFrames[0], &outputVec_(2,0), kSynthesisBlockSize * stride * sizeof(TonicFloat));
   }
setCoefficients() [1/2]
void Tonic::Biquad::setCoefficients (TonicFloat b0, TonicFloat b1, TonicFloat b2, TonicFloat a1, TonicFloat a2) inline
Set the coefficients for the filtering operation.
Definition at line 98 of file FilterUtils.h.
References coef_.
{
     coef_[0] = b0;
     coef_[1] = b1;
     coef_[2] = b2;
     coef_[3] = a1;
     coef_[4] = a2;
   }
setCoefficients() [2/2]
void Tonic::Biquad::setCoefficients (TonicFloat * newCoef) inline
Definition at line 106 of file FilterUtils.h.
References coef_.
{
     memcpy(coef_, newCoef, 5 * sizeof(TonicFloat));
   }
setIsStereo()
void Tonic::Biquad::setIsStereo (bool stereo) inline
Definition at line 80 of file FilterUtils.h.
References inputVec_, Tonic::kSynthesisBlockSize, outputVec_, and Tonic::TonicFrames::resize().
{
       // resize vectors to match number of channels
       inputVec_.resize(kSynthesisBlockSize + 4, stereo ? 2 : 1, 0);
       outputVec_.resize(kSynthesisBlockSize + 4, stereo ? 2 : 1, 0);
     }
Member Data Documentation
coef_
TonicFloat Tonic::Biquad::coef_[5] protected
Definition at line 72 of file FilterUtils.h.
inputVec_
TonicFrames Tonic::Biquad::inputVec_ protected
Definition at line 73 of file FilterUtils.h.
outputVec_
TonicFrames Tonic::Biquad::outputVec_ protected
Definition at line 74 of file FilterUtils.h.
The documentation for this class was generated from the following files:
FilterUtils.h
FilterUtils.cpp