YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::ControlGenerator_ Class Reference
Tonic::Tonic_::ControlGenerator_ Class Reference
#include <ControlGenerator.h>
Public Member Functions
ControlGenerator_ ()
virtual ~ControlGenerator_ ()
void lockMutex ()
void unlockMutex ()
virtual ControlGeneratorOutput tick (const SynthesisContext_ &context)
virtual ControlGeneratorOutput initialOutput ()
Protected Member Functions
virtual void computeOutput (const SynthesisContext_ &context)
Override this function to implement a new ControlGenerator.
Protected Attributes
ControlGeneratorOutput output_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 28 of file ControlGenerator.h.
Constructor & Destructor Documentation
ControlGenerator_()
Tonic::Tonic_::ControlGenerator_::ControlGenerator_ ()
Definition at line 21 of file ControlGenerator.cpp.
                                          :
       lastFrameIndex_(0)
     {
     }
~ControlGenerator_()
Tonic::Tonic_::ControlGenerator_::~ControlGenerator_ () virtual
Definition at line 26 of file ControlGenerator.cpp.
     {
     }
Member Function Documentation
computeOutput()
virtual void Tonic::Tonic_::ControlGenerator_::computeOutput (const SynthesisContext_ & context) inline protected virtual
Override this function to implement a new ControlGenerator.
Subclasses should use this function to put new data into output_
Reimplemented in Tonic::Tonic_::ControlDivider_, Tonic::Tonic_::ControlMultiplier_, Tonic::Tonic_::ControlSubtractor_, Tonic::Tonic_::ControlComparisonOperator_, Tonic::Tonic_::ControlAdder_, Tonic::Tonic_::ControlValue_, Tonic::Tonic_::ControlStepper_, Tonic::Tonic_::ControlXYSpeed_, Tonic::Tonic_::ControlDelay_, Tonic::Tonic_::ControlChangeNotifier_, Tonic::Tonic_::ControlMetro_, Tonic::Tonic_::ControlDbToLinear_, Tonic::Tonic_::ControlPulse_, Tonic::Tonic_::ControlMetroDivider_, Tonic::Tonic_::ControlPrinter_, Tonic::Tonic_::ControlRandom_, Tonic::Tonic_::ControlRecorder_, Tonic::Tonic_::ControlSnapToScale_, Tonic::Tonic_::ControlSwitcher_, Tonic::Tonic_::ControlTriggerFilter_, Tonic::Tonic_::ControlCounter_, Tonic::Tonic_::ControlMidiToFreq_, Tonic::Tonic_::ControlFloor_, and Tonic::Tonic_::ControlTrigger_.
Definition at line 52 of file ControlGenerator.h.
 {};
initialOutput()
ControlGeneratorOutput Tonic::Tonic_::ControlGenerator_::initialOutput () virtual
Definition at line 30 of file ControlGenerator.cpp.
References Tonic::DummyContext, and tick().
{
       // return output from passing in dummy context
       return tick(Tonic::DummyContext);
     }
lockMutex()
void Tonic::Tonic_::ControlGenerator_::lockMutex ()
tick()
ControlGeneratorOutput Tonic::Tonic_::ControlGenerator_::tick (const SynthesisContext_ & context) inline virtual
Definition at line 59 of file ControlGenerator.h.
References computeOutput(), Tonic::Tonic_::SynthesisContext_::elapsedFrames, Tonic::error(), Tonic::Tonic_::SynthesisContext_::forceNewOutput, lastFrameIndex_, output_, and Tonic::ControlGeneratorOutput::value.
{
       if (context.forceNewOutput || lastFrameIndex_ != context.elapsedFrames){
         lastFrameIndex_ = context.elapsedFrames;
         computeOutput(context);
       }
 #ifdef TONIC_DEBUG
       if(output_.value != output_.value){
         Tonic::error("ControlGenerator_::tick NaN detected.", true);
       }
 #endif
       return output_;
     }
unlockMutex()
void Tonic::Tonic_::ControlGenerator_::unlockMutex ()
Member Data Documentation
lastFrameIndex_
unsigned long Tonic::Tonic_::ControlGenerator_::lastFrameIndex_ protected
Definition at line 55 of file ControlGenerator.h.
output_
ControlGeneratorOutput Tonic::Tonic_::ControlGenerator_::output_ protected
Definition at line 52 of file ControlGenerator.h.
The documentation for this class was generated from the following files:
ControlGenerator.h
ControlGenerator.cpp