YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::Subtractor_ Class Reference
Tonic::Tonic_::Subtractor_ Class Reference
#include <Arithmetic.h>
Public Member Functions
Subtractor_ ()
void setLeft (Generator arg)
void setRight (Generator arg)
void setIsStereoOutput (bool stereo)
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
bool isStereoOutput ()
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
Generator left_
Generator right_
TonicFrames workSpace_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 130 of file Arithmetic.h.
Constructor & Destructor Documentation
Subtractor_()
Tonic::Tonic_::Subtractor_::Subtractor_ ()
Definition at line 42 of file Arithmetic.cpp.
References Tonic::kSynthesisBlockSize, Tonic::TonicFrames::resize(), and workSpace_.
{
     workSpace_.resize(kSynthesisBlockSize, 1, 0);
   }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::Subtractor_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 150 of file Arithmetic.h.
References left_, Tonic::Tonic_::Generator_::outputFrames_, right_, Tonic::Generator::tick(), and workSpace_.
{
       left_.tick(outputFrames_, context);
       right_.tick(workSpace_, context);
       outputFrames_ -= workSpace_;
     }
setIsStereoOutput()
void Tonic::Tonic_::Subtractor_::setIsStereoOutput (bool stereo) virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 62 of file Arithmetic.cpp.
References Tonic::kSynthesisBlockSize, Tonic::TonicFrames::resize(), Tonic::Tonic_::Generator_::setIsStereoOutput(), and workSpace_.
   {
     Generator_::setIsStereoOutput(stereo);
     workSpace_.resize(kSynthesisBlockSize, stereo ? 2 : 1, 0);
   }
setLeft()
void Tonic::Tonic_::Subtractor_::setLeft (Generator arg)
Definition at line 46 of file Arithmetic.cpp.
References Tonic::Tonic_::Generator_::isStereoOutput(), Tonic::Generator::isStereoOutput(), left_, and setIsStereoOutput().
{
     if (arg.isStereoOutput() && !isStereoOutput())
     {
       setIsStereoOutput(true);
     }
     left_ = arg;
   }
setRight()
void Tonic::Tonic_::Subtractor_::setRight (Generator arg)
Definition at line 54 of file Arithmetic.cpp.
References Tonic::Tonic_::Generator_::isStereoOutput(), Tonic::Generator::isStereoOutput(), right_, and setIsStereoOutput().
{
     if (arg.isStereoOutput() && !isStereoOutput())
     {
       setIsStereoOutput(true);
     }
     right_ = arg;
   }
Member Data Documentation
left_
Generator Tonic::Tonic_::Subtractor_::left_ protected
Definition at line 134 of file Arithmetic.h.
right_
Generator Tonic::Tonic_::Subtractor_::right_ protected
Definition at line 135 of file Arithmetic.h.
workSpace_
TonicFrames Tonic::Tonic_::Subtractor_::workSpace_ protected
Definition at line 136 of file Arithmetic.h.
The documentation for this class was generated from the following files:
Arithmetic.h
Arithmetic.cpp