YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::ImpulseDiffuserAllpass Class Reference
Tonic::Tonic_::ImpulseDiffuserAllpass Class Reference
Allpass filter for use with reverb.
#include <Reverb.h>
Public Member Functions
ImpulseDiffuserAllpass (TonicFloat delay, TonicFloat coef)
ImpulseDiffuserAllpass (const ImpulseDiffuserAllpass &other)
void tickThrough (TonicFrames &frames)
Protected Attributes
DelayLine delayForward_
DelayLine delayBack_
TonicFloat delay_
TonicFloat coef_
Detailed Description
Allpass filter for use with reverb.
This is not a Generator_ subclass and is optimized for the purposes of the Reverb_ class.
Definition at line 30 of file Reverb.h.
Constructor & Destructor Documentation
ImpulseDiffuserAllpass() [1/2]
Tonic::Tonic_::ImpulseDiffuserAllpass::ImpulseDiffuserAllpass (TonicFloat delay, TonicFloat coef)
Definition at line 33 of file Reverb.cpp.
References coef_, delay_, delayBack_, delayForward_, Tonic::DelayLine::initialize(), and Tonic::DelayLine::setInterpolates().
   {
     delay_ = delay;
     coef_ = coef;
     delayBack_.initialize(delay, 1);
     delayForward_.initialize(delay, 1);
     delayBack_.setInterpolates(false);
     delayForward_.setInterpolates(false);
   }
ImpulseDiffuserAllpass() [2/2]
Tonic::Tonic_::ImpulseDiffuserAllpass::ImpulseDiffuserAllpass (const ImpulseDiffuserAllpass & other)
Definition at line 43 of file Reverb.cpp.
References coef_, delay_, delayBack_, delayForward_, Tonic::DelayLine::initialize(), and Tonic::DelayLine::setInterpolates().
   {
     delay_ = other.delay_;
     coef_ = other.coef_;
     delayBack_.initialize(delay_,1);
     delayForward_.initialize(delay_,1);
     delayBack_.setInterpolates(false);
     delayForward_.setInterpolates(false);
   }
Member Function Documentation
tickThrough()
void Tonic::Tonic_::ImpulseDiffuserAllpass::tickThrough (Tonic::TonicFrames & frames) inline
Definition at line 47 of file Reverb.h.
References Tonic::DelayLine::advance(), coef_, delay_, delayBack_, delayForward_, Tonic::kSynthesisBlockSize, Tonic::DelayLine::tickIn(), and Tonic::DelayLine::tickOut().
     {
       TonicFloat *dptr = &frames[0];
       TonicFloat y;
       for (int i=0; i<kSynthesisBlockSize; i++){
         // feedback stage
         y = *dptr + delayBack_.tickOut(delay_) * coef_;
         delayBack_.tickIn(y);
         delayBack_.advance();
         // feed forward stage
         *dptr++ = (1.f+coef_)*delayForward_.tickOut(delay_) - y;
         delayForward_.tickIn(y);
         delayForward_.advance();
       }
     }
Member Data Documentation
coef_
TonicFloat Tonic::Tonic_::ImpulseDiffuserAllpass::coef_ protected
Definition at line 37 of file Reverb.h.
delay_
TonicFloat Tonic::Tonic_::ImpulseDiffuserAllpass::delay_ protected
Definition at line 36 of file Reverb.h.
delayBack_
DelayLine Tonic::Tonic_::ImpulseDiffuserAllpass::delayBack_ protected
Definition at line 35 of file Reverb.h.
delayForward_
DelayLine Tonic::Tonic_::ImpulseDiffuserAllpass::delayForward_ protected
Definition at line 34 of file Reverb.h.
The documentation for this class was generated from the following files:
Reverb.h
Reverb.cpp