YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::LFNoise_ Class Reference
Tonic::Tonic_::LFNoise_ Class Reference
#include <LFNoise.h>
Public Member Functions
void setFreq (ControlGenerator freq)
LFNoise_ ()
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Public Attributes
ControlGenerator mFreq
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
TonicFrames mFreqFrames
float mSlope
signed long mCounter
float mLevel
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 21 of file LFNoise.h.
Constructor & Destructor Documentation
LFNoise_()
Tonic::Tonic_::LFNoise_::LFNoise_ ()
Definition at line 18 of file LFNoise.cpp.
References Tonic::kSynthesisBlockSize, mFreqFrames, and Tonic::TonicFrames::resize().
                    : mCounter(0){
   mFreqFrames.resize(kSynthesisBlockSize);
 }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::LFNoise_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 39 of file LFNoise.h.
References Tonic::TonicFrames::frames(), mCounter, mFreq, Tonic::min(), mLevel, mSlope, Tonic::Tonic_::Generator_::outputFrames_, Tonic::randomFloat(), Tonic::sampleRate(), Tonic::ControlGenerator::tick(), and Tonic::ControlGeneratorOutput::value.
{
       unsigned long remain = (unsigned int)outputFrames_.frames();
       TonicFloat* out = &outputFrames_[0];
       do{
         if (mCounter<=0) {
           mCounter = sampleRate() / std::max<float>(mFreq.tick(context).value, .001f);
           mCounter = std::max<float>(1, mCounter);
           float nextlevel = randomFloat(-1, 1);
           mSlope = (nextlevel - mLevel) / mCounter;
         }
         unsigned long nsmps = std::min(remain, (unsigned long)mCounter);
         remain -= nsmps;
         mCounter -= nsmps;
         for(int i = 0; i < nsmps; i++){
           *(out++) = mLevel;
           mLevel += mSlope;
         }
       }while (remain);
     }
setFreq()
void Tonic::Tonic_::LFNoise_::setFreq (ControlGenerator freq)
Definition at line 22 of file LFNoise.cpp.
References mFreq.
{
   mFreq = freq;
 }
Member Data Documentation
mCounter
signed long Tonic::Tonic_::LFNoise_::mCounter protected
Definition at line 26 of file LFNoise.h.
mFreq
ControlGenerator Tonic::Tonic_::LFNoise_::mFreq
Definition at line 33 of file LFNoise.h.
mFreqFrames
TonicFrames Tonic::Tonic_::LFNoise_::mFreqFrames protected
Definition at line 24 of file LFNoise.h.
mLevel
float Tonic::Tonic_::LFNoise_::mLevel protected
Definition at line 27 of file LFNoise.h.
mSlope
float Tonic::Tonic_::LFNoise_::mSlope protected
Definition at line 25 of file LFNoise.h.
The documentation for this class was generated from the following files:
LFNoise.h
LFNoise.cpp