YOURPROJECTNAMEGOESHERE: Tonic::RingBufferReader Class Reference
Tonic::RingBufferReader Class Reference
#include <RingBuffer.h>
Public Member Functions
RingBufferReader & bufferName (string name)
Public Member Functions inherited from Tonic::TemplatedGenerator< Tonic_::RingBufferReader_ >
TemplatedGenerator ()
Public Member Functions inherited from Tonic::Generator
Generator (Tonic_::Generator_ *gen=new Tonic_::Generator_)
bool isStereoOutput ()
virtual void tick (TonicFrames &frames, const Tonic_::SynthesisContext_ &context)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::Generator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Public Types inherited from Tonic::TemplatedGenerator< Tonic_::RingBufferReader_ >
typedef Tonic_::RingBufferReader_ gen_t
Protected Member Functions inherited from Tonic::TemplatedGenerator< Tonic_::RingBufferReader_ >
Tonic_::RingBufferReader_ * gen ()
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
Tonic_::Generator_ * obj
int * pcount
Detailed Description
Definition at line 242 of file RingBuffer.h.
Member Function Documentation
bufferName()
RingBufferReader & Tonic::RingBufferReader::bufferName (string name)
Definition at line 48 of file RingBuffer.cpp.
References Tonic::error(), Tonic::TemplatedGenerator< Tonic_::RingBufferReader_ >::gen(), Tonic::s_RingBuffers_, and Tonic::Tonic_::RingBufferReader_::setRingBuffer().
{
     if (s_RingBuffers_.containsObjectNamed(name)){
       gen()->setRingBuffer(s_RingBuffers_.objectNamed(name));
     }
     else{
       error("RingBuffer named " + name + " does not exist.");
     }
     return *this;
   }
The documentation for this class was generated from the following files:
RingBuffer.h
RingBuffer.cpp