YOURPROJECTNAMEGOESHERE: Tonic::Synth Class Reference
Tonic::Synth Class Reference
#include <Synth.h>
Public Member Functions
void setOutputGen (Generator generator)
Set the output gen that produces audio for the Synth.
const Generator getOutputGen ()
Returns a reference to outputGen.
void setLimitOutput (bool shouldLimit)
Set whether synth uses dynamic limiter to prevent clipping/wrapping. Defaults to true.
ControlParameter addParameter (string name, TonicFloat initialValue=0.f)
Add a ControlParameter with name "name".
void addParameter (ControlParameter parameter)
Add a ControlParameter initialized elsewhere. Will overwrite existing parameter with the same name.
void addParametersFromSynth (Synth synth)
Add all the parameters from another synth.
ControlChangeNotifier publishChanges (ControlGenerator input, string name="")
void addAuxControlGenerator (ControlGenerator generator)
Add a ControlGenerator to a list of objects which will be ticked regardless of whether they're part of the synthesis graph or not.
void addControlChangeSubscriber (string name, ControlChangeSubscriber *resp)
Add an object which will be notified when a particular ControlChangeNotifier changes value or is triggered.
void addControlChangeSubscriber (ControlChangeSubscriber *resp)
Add an object which will be notified when any ControlChangeNotifier changes value or is triggered.
void removeControlChangeSubscriber (ControlChangeSubscriber *sub)
Unsubscribe a ControlChangeSubscriber.
void sendControlChangesToSubscribers ()
void setParameter (string name, float value=1.f, bool normalized=false)
Set the value of a control parameter on this synth.
vector< ControlParameter > getParameters ()
Get all of the control parameters registered for this synth.
void forceNewOutput ()
Public Member Functions inherited from Tonic::TemplatedBufferFiller< Tonic_::Synth_ >
TemplatedBufferFiller ()
Public Member Functions inherited from Tonic::BufferFiller
BufferFiller (Tonic_::BufferFiller_ *newBf)
void fillBufferOfFloats (float *outData, unsigned int numFrames, unsigned int numChannels)
Fill an arbitrarily-sized, interleaved buffer of audio samples as floats.
Public Member Functions inherited from Tonic::Generator
Generator (Tonic_::Generator_ *gen=new Tonic_::Generator_)
bool isStereoOutput ()
virtual void tick (TonicFrames &frames, const Tonic_::SynthesisContext_ &context)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::Generator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Protected Member Functions inherited from Tonic::TemplatedBufferFiller< Tonic_::Synth_ >
Tonic_::Synth_ * gen ()
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
Tonic_::Generator_ * obj
int * pcount
Detailed Description
Definition at line 101 of file Synth.h.
Member Function Documentation
addAuxControlGenerator()
void Tonic::Synth::addAuxControlGenerator (ControlGenerator generator) inline
Add a ControlGenerator to a list of objects which will be ticked regardless of whether they're part of the synthesis graph or not.
Definition at line 151 of file Synth.h.
References Tonic::Tonic_::Synth_::addAuxControlGenerator(), and Tonic::TemplatedBufferFiller< Tonic_::Synth_ >::gen().
{
       gen()->addAuxControlGenerator(generator);
     }
addControlChangeSubscriber() [1/2]
void Tonic::Synth::addControlChangeSubscriber (string name, ControlChangeSubscriber * resp) inline
Add an object which will be notified when a particular ControlChangeNotifier changes value or is triggered.
Definition at line 156 of file Synth.h.
References Tonic::Tonic_::Synth_::addControlChangeSubscriber(), and Tonic::TemplatedBufferFiller< Tonic_::Synth_ >::gen().
{
       gen()->addControlChangeSubscriber(name, resp);
     }
addControlChangeSubscriber() [2/2]
void Tonic::Synth::addControlChangeSubscriber (ControlChangeSubscriber * resp) inline
Add an object which will be notified when any ControlChangeNotifier changes value or is triggered.
Definition at line 161 of file Synth.h.
References Tonic::Tonic_::Synth_::addControlChangeSubscriber(), and Tonic::TemplatedBufferFiller< Tonic_::Synth_ >::gen().
{
       gen()->addControlChangeSubscriber(resp);
     }
addParameter() [1/2]
ControlParameter Tonic::Synth::addParameter (string name, TonicFloat initialValue = 0.f) inline
Add a ControlParameter with name "name".
Definition at line 121 of file Synth.h.
References Tonic::Tonic_::Synth_::addParameter(), and Tonic::TemplatedBufferFiller< Tonic_::Synth_ >::gen().
     {
       return gen()->addParameter(name, initialValue);
     }
addParameter() [2/2]
void Tonic::Synth::addParameter (ControlParameter parameter) inline
Add a ControlParameter initialized elsewhere. Will overwrite existing parameter with the same name.
Definition at line 127 of file Synth.h.
References Tonic::Tonic_::Synth_::addParameter(), and Tonic::TemplatedBufferFiller< Tonic_::Synth_ >::gen().
     {
       gen()->addParameter(parameter);
     }
addParametersFromSynth()
void Tonic::Synth::addParametersFromSynth (Synth synth) inline
Add all the parameters from another synth.
Definition at line 133 of file Synth.h.
References Tonic::Tonic_::Synth_::addParametersFromSynth(), and Tonic::TemplatedBufferFiller< Tonic_::Synth_ >::gen().
     {
       gen()->addParametersFromSynth(synth);
     }
forceNewOutput()
void Tonic::Synth::forceNewOutput () inline
Definition at line 195 of file Synth.h.
References Tonic::Tonic_::Synth_::forceNewOutput(), and Tonic::TemplatedBufferFiller< Tonic_::Synth_ >::gen().
{
       gen()->forceNewOutput();
     }
getOutputGen()
const Generator Tonic::Synth::getOutputGen () inline
Returns a reference to outputGen.
Definition at line 111 of file Synth.h.
References Tonic::TemplatedBufferFiller< Tonic_::Synth_ >::gen(), and Tonic::Tonic_::Synth_::getOutputGen().
{
       return gen()->getOutputGen();
     }
getParameters()
vector<ControlParameter> Tonic::Synth::getParameters () inline
Get all of the control parameters registered for this synth.
Definition at line 190 of file Synth.h.
References Tonic::TemplatedBufferFiller< Tonic_::Synth_ >::gen(), and Tonic::Tonic_::Synth_::getParameters().
     {
       return gen()->getParameters();
     }
publishChanges()
ControlChangeNotifier Tonic::Synth::publishChanges (ControlGenerator input, string name = "") inline
Returns a ControlConditioner which accepts an input and a ControlChangeSubscriber (supplied by the UI). When the input value changes, ControlChangeSubscriber::messageRecieved is called. You would typically call this method inside a synth definition if you have a ControlGenerator whose value you want to make accessible to the UI thread. You then subscribe to these events by creating a subclass of ControlChangeSubscriber and passing a pointer to that object to Synth::addControlChangeSubscriber.
Definition at line 146 of file Synth.h.
References Tonic::TemplatedBufferFiller< Tonic_::Synth_ >::gen(), and Tonic::Tonic_::Synth_::publishChanges().
{
       return gen()->publishChanges(input, name);
     }
removeControlChangeSubscriber()
void Tonic::Synth::removeControlChangeSubscriber (ControlChangeSubscriber * sub) inline
Unsubscribe a ControlChangeSubscriber.
Definition at line 166 of file Synth.h.
References Tonic::TemplatedBufferFiller< Tonic_::Synth_ >::gen(), and Tonic::Tonic_::Synth_::removeControlChangeSubscriber().
{
       gen()->removeControlChangeSubscriber(sub);
     }
sendControlChangesToSubscribers()
void Tonic::Synth::sendControlChangesToSubscribers () inline
Use in conjunction with publishChanges and addControlChangeSubscriber. This is designed as a way to get events from the audio thread to the UI thread. sendControlChangesToSubscribers should be called from the UI thread, not the audio thread.
Definition at line 175 of file Synth.h.
References Tonic::TemplatedBufferFiller< Tonic_::Synth_ >::gen(), and Tonic::Tonic_::Synth_::sendControlChangesToSubscribers().
{
       gen()->sendControlChangesToSubscribers();
     }
setLimitOutput()
void Tonic::Synth::setLimitOutput (bool shouldLimit) inline
Set whether synth uses dynamic limiter to prevent clipping/wrapping. Defaults to true.
Definition at line 116 of file Synth.h.
References Tonic::TemplatedBufferFiller< Tonic_::Synth_ >::gen(), and Tonic::Tonic_::Synth_::setLimitOutput().
{
       gen()->setLimitOutput(shouldLimit);
     }
setOutputGen()
void Tonic::Synth::setOutputGen (Generator generator) inline
Set the output gen that produces audio for the Synth.
Definition at line 106 of file Synth.h.
References Tonic::TemplatedBufferFiller< Tonic_::Synth_ >::gen(), and Tonic::Tonic_::Synth_::setOutputGen().
{
       gen()->setOutputGen(generator);
     }
setParameter()
void Tonic::Synth::setParameter (string name, float value = 1.f, bool normalized = false) inline
Set the value of a control parameter on this synth.
If normalized is true, value will be mapped to defined range of parameter
Definition at line 183 of file Synth.h.
References Tonic::TemplatedBufferFiller< Tonic_::Synth_ >::gen(), and Tonic::Tonic_::Synth_::setParameter().
     {
       gen()->setParameter(name, value, normalized);
     }
The documentation for this class was generated from the following file:
Synth.h