YOURPROJECTNAMEGOESHERE: Tonic::SineWave Class Reference
Tonic::SineWave Class Reference
#include <SineWave.h>
Public Member Functions
SineWave ()
Public Member Functions inherited from Tonic::TemplatedGenerator< Tonic_::TableLookupOsc_ >
TemplatedGenerator ()
Public Member Functions inherited from Tonic::Generator
Generator (Tonic_::Generator_ *gen=new Tonic_::Generator_)
bool isStereoOutput ()
virtual void tick (TonicFrames &frames, const Tonic_::SynthesisContext_ &context)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::Generator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Public Types inherited from Tonic::TemplatedGenerator< Tonic_::TableLookupOsc_ >
typedef Tonic_::TableLookupOsc_ gen_t
Protected Member Functions inherited from Tonic::TemplatedGenerator< Tonic_::TableLookupOsc_ >
Tonic_::TableLookupOsc_ * gen ()
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
Tonic_::Generator_ * obj
int * pcount
Detailed Description
Definition at line 19 of file SineWave.h.
Constructor & Destructor Documentation
SineWave()
Tonic::SineWave::SineWave ()
Definition at line 13 of file SineWave.cpp.
References Tonic::SampleTable::dataPointer(), Tonic::TemplatedGenerator< Tonic_::TableLookupOsc_ >::gen(), Tonic::Tonic_::s_oscillatorTables(), Tonic::Tonic_::TableLookupOsc_::setLookupTable(), and TWO_PI.
                     {
     static string const TONIC_SIN_TABLE = "_TONIC_SIN_TABLE_";
     // As soon as the first SineWave is allocated, persistent SampleTable is created. Will stay in memory for program lifetime.
     if (!Tonic_::s_oscillatorTables()->containsObjectNamed(TONIC_SIN_TABLE)){
       const unsigned int tableSize = 4096;
       SampleTable sineTable = SampleTable(tableSize+1, 1);
       TonicFloat norm = 1.0f / tableSize;
       TonicFloat *data = sineTable.dataPointer();
       for ( unsigned long i=0; i<tableSize+1; i++ ){
         *data++ = sinf( TWO_PI * i * norm );
       }
       Tonic_::s_oscillatorTables()->insertObject(TONIC_SIN_TABLE, sineTable);
       this->gen()->setLookupTable(sineTable);
     }
     else{
       this->gen()->setLookupTable(Tonic_::s_oscillatorTables()->objectNamed(TONIC_SIN_TABLE));
     }
   }
The documentation for this class was generated from the following files:
SineWave.h
SineWave.cpp