YOURPROJECTNAMEGOESHERE: Tonic::ControlValue Class Reference
Tonic::ControlValue Class Reference
#include <ControlValue.h>
Public Member Functions
ControlValue (TonicFloat value=0)
ControlValue & value (TonicFloat value)
float getValue ()
Public Member Functions inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlValue_ >
TemplatedControlGenerator ()
Public Member Functions inherited from Tonic::ControlGenerator
ControlGenerator (Tonic_::ControlGenerator_ *cGen=new Tonic_::ControlGenerator_)
ControlGeneratorOutput tick (const Tonic_::SynthesisContext_ &context)
RampedValue smoothed (float length=0.05)
ControlAdder operator+ (ControlGenerator b)
ControlAdder operator+ (float b)
ControlSubtractor operator- (ControlGenerator b)
ControlSubtractor operator- (float b)
ControlMultiplier operator* (ControlGenerator b)
ControlMultiplier operator* (float b)
ControlDivider operator/ (ControlGenerator b)
ControlDivider operator/ (float b)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::ControlGenerator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Public Types inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlValue_ >
typedef Tonic_::ControlValue_ gen_t
Protected Member Functions inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlValue_ >
Tonic_::ControlValue_ * gen ()
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >
Tonic_::ControlGenerator_ * obj
int * pcount
Detailed Description
Definition at line 51 of file ControlValue.h.
Constructor & Destructor Documentation
ControlValue()
Tonic::ControlValue::ControlValue (TonicFloat value = 0) inline
Definition at line 55 of file ControlValue.h.
References Tonic::TemplatedControlGenerator< Tonic_::ControlValue_ >::gen(), Tonic::Tonic_::ControlValue_::setValue(), and value().
{
       gen()->setValue(value);
     }
Member Function Documentation
getValue()
float Tonic::ControlValue::getValue () inline
Definition at line 66 of file ControlValue.h.
References Tonic::TemplatedControlGenerator< Tonic_::ControlValue_ >::gen(), and Tonic::Tonic_::ControlValue_::getValue().
                     {
       return gen()->getValue();
     }
value()
ControlValue& Tonic::ControlValue::value (TonicFloat value) inline
Definition at line 59 of file ControlValue.h.
References Tonic::TemplatedControlGenerator< Tonic_::ControlValue_ >::gen(), and Tonic::Tonic_::ControlValue_::setValue().
     {
       gen()->setValue(value);
       return *this;
     }
The documentation for this class was generated from the following file:
ControlValue.h