YOURPROJECTNAMEGOESHERE: Tonic::ControlSwitcher Class Reference
Tonic::ControlSwitcher Class Reference
#include <ControlSwitcher.h>
Public Member Functions
ControlSwitcher & setFloatInputs (vector< float > inputs)
TONIC_MAKE_CTRL_GEN_SETTERS (ControlSwitcher, addInput, addInput)
TONIC_MAKE_CTRL_GEN_SETTERS (ControlSwitcher, inputIndex, setInputIndex)
TONIC_MAKE_CTRL_GEN_SETTERS (ControlSwitcher, doesWrap, setDoesWrap)
TONIC_MAKE_CTRL_GEN_SETTERS (ControlSwitcher, addAfterWrap, setAddAfterWrap)
Useful if you want to use this to map to scale degrees. For midi notes, you can use 12 to jump to the next octave when it wraps.
ControlSwitcher & triggerForIndex (ControlGenerator trigger, int index)
Public Member Functions inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlSwitcher_ >
TemplatedControlGenerator ()
Public Member Functions inherited from Tonic::ControlGenerator
ControlGenerator (Tonic_::ControlGenerator_ *cGen=new Tonic_::ControlGenerator_)
ControlGeneratorOutput tick (const Tonic_::SynthesisContext_ &context)
RampedValue smoothed (float length=0.05)
ControlAdder operator+ (ControlGenerator b)
ControlAdder operator+ (float b)
ControlSubtractor operator- (ControlGenerator b)
ControlSubtractor operator- (float b)
ControlMultiplier operator* (ControlGenerator b)
ControlMultiplier operator* (float b)
ControlDivider operator/ (ControlGenerator b)
ControlDivider operator/ (float b)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::ControlGenerator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Public Types inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlSwitcher_ >
typedef Tonic_::ControlSwitcher_ gen_t
Protected Member Functions inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlSwitcher_ >
Tonic_::ControlSwitcher_ * gen ()
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >
Tonic_::ControlGenerator_ * obj
int * pcount
Detailed Description
ControlSwitcher allows you to switch between an unlimited number of inputs (added via addInput). The "active" input is controlled by the value of inputIndex and any iputs passed via triggerForIndex. If the input index changes, the object will send a trigger (formerly known as "hasChanged") message. Currently, the inputIndex must send a trigger message every time it changes, or the change won't be registered.
Definition at line 55 of file ControlSwitcher.h.
Member Function Documentation
setFloatInputs()
ControlSwitcher & Tonic::ControlSwitcher::setFloatInputs (vector< float > inputs)
Definition at line 108 of file ControlSwitcher.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlSwitcher_ >::gen(), and Tonic::Tonic_::ControlSwitcher_::setInputs().
{
     vector<ControlGenerator> newInputs;
     for(vector<float>::iterator it = inputs.begin(); it != inputs.end(); it++){
       newInputs.push_back(ControlValue(*it));
     }
     gen()->setInputs(newInputs);
     return *this;
   }
TONIC_MAKE_CTRL_GEN_SETTERS() [1/4]
Tonic::ControlSwitcher::TONIC_MAKE_CTRL_GEN_SETTERS (ControlSwitcher , addInput , addInput)
TONIC_MAKE_CTRL_GEN_SETTERS() [2/4]
Tonic::ControlSwitcher::TONIC_MAKE_CTRL_GEN_SETTERS (ControlSwitcher , inputIndex , setInputIndex)
TONIC_MAKE_CTRL_GEN_SETTERS() [3/4]
Tonic::ControlSwitcher::TONIC_MAKE_CTRL_GEN_SETTERS (ControlSwitcher , doesWrap , setDoesWrap)
TONIC_MAKE_CTRL_GEN_SETTERS() [4/4]
Tonic::ControlSwitcher::TONIC_MAKE_CTRL_GEN_SETTERS (ControlSwitcher , addAfterWrap , setAddAfterWrap)
Useful if you want to use this to map to scale degrees. For midi notes, you can use 12 to jump to the next octave when it wraps.
triggerForIndex()
ControlSwitcher & Tonic::ControlSwitcher::triggerForIndex (ControlGenerator trigger, int index)
Definition at line 103 of file ControlSwitcher.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlSwitcher_ >::gen(), and Tonic::Tonic_::ControlSwitcher_::setTriggerForIndex().
{
     gen()->setTriggerForIndex(trigger, index);
     return *this;
   }
The documentation for this class was generated from the following files:
ControlSwitcher.h
ControlSwitcher.cpp