YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::ADSR_ Class Reference
Tonic::Tonic_::ADSR_ Class Reference
#include <ADSR.h>
Public Member Functions
ADSR_ ()
~ADSR_ ()
void setTrigger (ControlGenerator trig)
void setAttack (ControlGenerator gen)
void setDecay (ControlGenerator gen)
void setSustain (ControlGenerator gen)
void setRelease (ControlGenerator gen)
void setIsExponential (ControlGenerator gen)
Exponential or linear ramp.
void setIsLegato (ControlGenerator gen)
Controls whether the envelope picks up from current position or zero when re-triggered while still releasing.
void setDoesSustain (ControlGenerator gen)
Controls whether or not the envelope pauses on the SUSTAIN stage.
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Types
enum ADSRState {
NEUTRAL, ATTACK, SUSTAIN, DECAY,
RELEASE
}
Protected Member Functions
void switchState (ADSRState newState)
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
ControlGenerator mTrigger
ControlGenerator attack
ControlGenerator decay
ControlGenerator sustain
ControlGenerator release
ControlGenerator doesSustain
ControlGenerator isLegato
ControlGenerator isExponential
TonicFloat attackTime
TonicFloat decayTime
TonicFloat sustainLevelVal
TonicFloat releaseTime
bool bIsLegato
bool bDoesSustain
bool bIsExponential
unsigned long segCounter
unsigned long segLength
TonicFloat targetValue
TonicFloat lastValue
TonicFloat increment
TonicFloat pole
ADSRState state
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 23 of file ADSR.h.
Member Enumeration Documentation
ADSRState
enum Tonic::Tonic_::ADSR_::ADSRState protected
Enumerator
NEUTRAL
ATTACK
SUSTAIN
DECAY
RELEASE
Definition at line 53 of file ADSR.h.
                      {
         NEUTRAL,
         ATTACK,
         SUSTAIN,
         DECAY,
         RELEASE
       };
Constructor & Destructor Documentation
ADSR_()
Tonic::Tonic_::ADSR_::ADSR_ ()
Definition at line 13 of file ADSR.cpp.
References doesSustain, isExponential, isLegato, and mTrigger.
                :
     state(NEUTRAL),
     lastValue(0),
     targetValue(0),
     increment(0),
     segCounter(0),
     segLength(0),
     pole(0)
   {
     mTrigger = ControlValue(0); // empty trigger by default
     isLegato = ControlValue(false);
     doesSustain = ControlValue(true);
     isExponential = ControlValue(false);
   }
~ADSR_()
Tonic::Tonic_::ADSR_::~ADSR_ ()
Definition at line 28 of file ADSR.cpp.
                {
   }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::ADSR_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 88 of file ADSR.h.
References attack, ATTACK, attackTime, bDoesSustain, bIsExponential, bIsLegato, decay, DECAY, decayTime, doesSustain, increment, isExponential, isLegato, Tonic::kSynthesisBlockSize, lastValue, mTrigger, NEUTRAL, Tonic::onePoleLPFTick(), Tonic::Tonic_::Generator_::outputFrames_, pole, release, RELEASE, releaseTime, segCounter, segLength, state, sustain, SUSTAIN, sustainLevelVal, switchState(), targetValue, Tonic::ControlGenerator::tick(), Tonic::ControlGeneratorOutput::triggered, and Tonic::ControlGeneratorOutput::value.
{
       ControlGeneratorOutput triggerOutput = mTrigger.tick(context);
       // frames to go in this block
       // Tick ALL inputs every time to keep everything in sync
       attackTime = attack.tick(context).value;
       decayTime = decay.tick(context).value;
       sustainLevelVal = sustain.tick(context).value;
       releaseTime = release.tick(context).value;
       bIsExponential = (bool)isExponential.tick(context).value;
       bDoesSustain = (bool)doesSustain.tick(context).value;
       bIsLegato = (bool)isLegato.tick(context).value;
       TonicFloat * fdata = &outputFrames_[0];
       if(triggerOutput.triggered){
         if(triggerOutput.value != 0){
           switchState(ATTACK);
         }else if(bDoesSustain){
           switchState(RELEASE);
         }
       }
       int samplesRemaining = kSynthesisBlockSize;
       while (samplesRemaining > 0)
       {
         switch (state) {
           // Both of these cases just fill the synthesis block the rest of the way up
           case NEUTRAL:
           case SUSTAIN:
           {
             #ifdef USE_APPLE_ACCELERATE
             vDSP_vfill(&lastValue, fdata, 1, samplesRemaining);
             #else
             std::fill(fdata, fdata + samplesRemaining, lastValue);
             #endif
             samplesRemaining = 0;
           }
             break;
           case ATTACK:
           case DECAY:
           case RELEASE:
           {
             // how many samples remain in current segment
             unsigned long remainder = (segCounter > segLength) ? 0 : segLength - segCounter;
             if (remainder < samplesRemaining){
               // fill up part of the ramp then switch segment
               if (bIsExponential){
                 // one pole filter
                 for (unsigned long i=0; i<remainder; i++){
                   onePoleLPFTick(targetValue, lastValue, pole);
                   *fdata++ = lastValue;
                 }
               }
               else{
                 #ifdef USE_APPLE_ACCELERATE
                 // starting point
                 lastValue += increment;
                 // vector calculation
                 vDSP_vramp(&lastValue, &increment, fdata, 1, remainder);
                 // end point
                 lastValue += increment*(remainder-1);
                 fdata += remainder;
                 #else
                 for (unsigned long i=0; i<remainder; i++){
                   lastValue += increment;
                   *fdata++ = lastValue;
                 }
                 #endif
               }
               segCounter += remainder;
               samplesRemaining -= remainder;
               // switch segment
               if (state == ATTACK){
                 switchState(DECAY);
               }
               else if (state == DECAY){
                 switchState(bDoesSustain ? SUSTAIN : RELEASE);
               }
               else{
                 switchState(NEUTRAL);
               }
             }
             else{
               if (bIsExponential){
                 // one pole filter
                 for (int i=0; i<samplesRemaining; i++){
                   onePoleLPFTick(targetValue, lastValue, pole);
                   *fdata++ = lastValue;
                 }
               }
               else{
                 // fill the rest of the ramp up
                 #ifdef USE_APPLE_ACCELERATE
                 // starting point
                 lastValue += increment;
                 // vector calculation
                 vDSP_vramp(&lastValue, &increment, fdata, 1, samplesRemaining);
                 // end point
                 lastValue += increment*(samplesRemaining-1);
                 #else
                 for (int i=0; i<samplesRemaining; i++){
                   lastValue += increment;
                   *fdata++ = lastValue;
                 }
                 #endif
               }
               segCounter += samplesRemaining;
               samplesRemaining = 0;
             }
           }
             break;
           default:
             break;
         }
       }
     }
setAttack()
void Tonic::Tonic_::ADSR_::setAttack (ControlGenerator gen) inline
Definition at line 72 of file ADSR.h.
References attack.
 {attack = gen;}
setDecay()
void Tonic::Tonic_::ADSR_::setDecay (ControlGenerator gen) inline
Definition at line 73 of file ADSR.h.
References decay.
 {decay = gen;}
setDoesSustain()
void Tonic::Tonic_::ADSR_::setDoesSustain (ControlGenerator gen) inline
Controls whether or not the envelope pauses on the SUSTAIN stage.
Definition at line 84 of file ADSR.h.
References doesSustain.
 {doesSustain = gen;};
setIsExponential()
void Tonic::Tonic_::ADSR_::setIsExponential (ControlGenerator gen) inline
Exponential or linear ramp.
Definition at line 78 of file ADSR.h.
References isExponential.
 {isExponential = gen;}
setIsLegato()
void Tonic::Tonic_::ADSR_::setIsLegato (ControlGenerator gen) inline
Controls whether the envelope picks up from current position or zero when re-triggered while still releasing.
Definition at line 81 of file ADSR.h.
References isLegato.
 {isLegato = gen;}
setRelease()
void Tonic::Tonic_::ADSR_::setRelease (ControlGenerator gen) inline
Definition at line 75 of file ADSR.h.
References release.
 {release = gen;}
setSustain()
void Tonic::Tonic_::ADSR_::setSustain (ControlGenerator gen) inline
Definition at line 74 of file ADSR.h.
References sustain.
 {sustain = gen;}
setTrigger()
void Tonic::Tonic_::ADSR_::setTrigger (ControlGenerator trig) inline
Definition at line 71 of file ADSR.h.
References mTrigger.
 {mTrigger = trig;}
switchState()
void Tonic::Tonic_::ADSR_::switchState (ADSRState newState) protected
Definition at line 32 of file ADSR.cpp.
References ATTACK, attackTime, bDoesSustain, bIsLegato, DECAY, decayTime, increment, lastValue, NEUTRAL, pole, RELEASE, releaseTime, Tonic::sampleRate(), segCounter, segLength, state, SUSTAIN, sustainLevelVal, Tonic::t60ToOnePoleCoef(), and targetValue.
{
     state = newState;
     segCounter = 0;
     switch(state){
       case NEUTRAL:{
         lastValue = 0.f;
         increment = 0.f;
       }
       break;
       case ATTACK:{
         if (!bIsLegato){
           lastValue = 0.f;
         }
         segLength = attackTime * sampleRate();
         pole = t60ToOnePoleCoef(attackTime);
         if (segLength == 0){
           lastValue = 1.0f;
           switchState(DECAY);
         }
         else{
           targetValue = 1.0f;
           increment = (TonicFloat)(1.0f - lastValue)/segLength;
         }
       }
       break;
       case DECAY:{
         segLength = decayTime * sampleRate();
         pole = t60ToOnePoleCoef(decayTime);
         targetValue = sustainLevelVal;
         if (segLength == 0){
           lastValue = sustainLevelVal;
           switchState(bDoesSustain ? SUSTAIN : RELEASE);
         }
         else{
           increment = (TonicFloat)(sustainLevelVal - lastValue)/segLength;
         }
       }
       break;
       case SUSTAIN:
       {
         targetValue = sustainLevelVal;
         lastValue = sustainLevelVal;
         increment = 0.f;
       }
       break;
       case RELEASE:{
         segLength = releaseTime * sampleRate();
         pole = t60ToOnePoleCoef(releaseTime);
         targetValue = 0.f;
         if (segLength == 0){
           lastValue = 0.f;
           switchState(NEUTRAL);
         }
         else{
           increment = (TonicFloat)(-lastValue)/segLength;
         }
       }
       break;
       default:
       break;
     }
   }
Member Data Documentation
attack
ControlGenerator Tonic::Tonic_::ADSR_::attack protected
Definition at line 29 of file ADSR.h.
attackTime
TonicFloat Tonic::Tonic_::ADSR_::attackTime protected
Definition at line 37 of file ADSR.h.
bDoesSustain
bool Tonic::Tonic_::ADSR_::bDoesSustain protected
Definition at line 42 of file ADSR.h.
bIsExponential
bool Tonic::Tonic_::ADSR_::bIsExponential protected
Definition at line 43 of file ADSR.h.
bIsLegato
bool Tonic::Tonic_::ADSR_::bIsLegato protected
Definition at line 41 of file ADSR.h.
decay
ControlGenerator Tonic::Tonic_::ADSR_::decay protected
Definition at line 30 of file ADSR.h.
decayTime
TonicFloat Tonic::Tonic_::ADSR_::decayTime protected
Definition at line 38 of file ADSR.h.
doesSustain
ControlGenerator Tonic::Tonic_::ADSR_::doesSustain protected
Definition at line 33 of file ADSR.h.
increment
TonicFloat Tonic::Tonic_::ADSR_::increment protected
Definition at line 50 of file ADSR.h.
isExponential
ControlGenerator Tonic::Tonic_::ADSR_::isExponential protected
Definition at line 35 of file ADSR.h.
isLegato
ControlGenerator Tonic::Tonic_::ADSR_::isLegato protected
Definition at line 34 of file ADSR.h.
lastValue
TonicFloat Tonic::Tonic_::ADSR_::lastValue protected
Definition at line 49 of file ADSR.h.
mTrigger
ControlGenerator Tonic::Tonic_::ADSR_::mTrigger protected
Definition at line 28 of file ADSR.h.
pole
TonicFloat Tonic::Tonic_::ADSR_::pole protected
Definition at line 51 of file ADSR.h.
release
ControlGenerator Tonic::Tonic_::ADSR_::release protected
Definition at line 32 of file ADSR.h.
releaseTime
TonicFloat Tonic::Tonic_::ADSR_::releaseTime protected
Definition at line 40 of file ADSR.h.
segCounter
unsigned long Tonic::Tonic_::ADSR_::segCounter protected
Definition at line 46 of file ADSR.h.
segLength
unsigned long Tonic::Tonic_::ADSR_::segLength protected
Definition at line 47 of file ADSR.h.
state
ADSRState Tonic::Tonic_::ADSR_::state protected
Definition at line 61 of file ADSR.h.
sustain
ControlGenerator Tonic::Tonic_::ADSR_::sustain protected
Definition at line 31 of file ADSR.h.
sustainLevelVal
TonicFloat Tonic::Tonic_::ADSR_::sustainLevelVal protected
Definition at line 39 of file ADSR.h.
targetValue
TonicFloat Tonic::Tonic_::ADSR_::targetValue protected
Definition at line 48 of file ADSR.h.
The documentation for this class was generated from the following files:
ADSR.h
ADSR.cpp