YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::RampedValue_ Class Reference
Tonic::Tonic_::RampedValue_ Class Reference
#include <RampedValue.h>
Public Member Functions
RampedValue_ ()
~RampedValue_ ()
void setValueGen (ControlGenerator value)
void setTargetGen (ControlGenerator target)
void setLengthGen (ControlGenerator length)
void updateValue (TonicFloat value)
void updateTarget (TonicFloat target, unsigned long lengthSamp)
bool isFinished ()
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
bool finished_
unsigned long count_
unsigned long len_
TonicFloat target_
TonicFloat last_
TonicFloat inc_
ControlGenerator targetGen_
ControlGenerator lengthGen_
ControlGenerator valueGen_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 23 of file RampedValue.h.
Constructor & Destructor Documentation
RampedValue_()
Tonic::Tonic_::RampedValue_::RampedValue_ ()
Definition at line 14 of file RampedValue.cpp.
                              :
     finished_(true),
     count_(0),
     len_(0),
     target_(0),
     last_(0),
     inc_(0)
   {
   }
~RampedValue_()
Tonic::Tonic_::RampedValue_::~RampedValue_ ()
Definition at line 24 of file RampedValue.cpp.
{
   }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::RampedValue_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 54 of file RampedValue.h.
References Tonic::TonicFrames::channels(), count_, Tonic::error(), Tonic::TonicFrames::fillChannels(), finished_, inc_, Tonic::kSynthesisBlockSize, last_, len_, lengthGen_, Tonic::Tonic_::Generator_::outputFrames_, Tonic::sampleRate(), target_, targetGen_, Tonic::ControlGenerator::tick(), Tonic::ControlGeneratorOutput::triggered, updateTarget(), updateValue(), Tonic::ControlGeneratorOutput::value, and valueGen_.
{
       // First set the value, if necessary (abort ramp, go immediately to value)
       ControlGeneratorOutput valueOutput = valueGen_.tick(context);
       if(valueOutput.triggered){
         updateValue(valueOutput.value);
       }
       // Then update the target or ramp length (start a new ramp)
       ControlGeneratorOutput lengthOutput = lengthGen_.tick(context);
       ControlGeneratorOutput targetOutput = targetGen_.tick(context);
       if (lengthOutput.triggered || targetOutput.triggered){
         unsigned long lSamp = lengthOutput.value*Tonic::sampleRate();
         updateTarget(targetOutput.value, lSamp);
       }
       TonicFloat *fdata = &outputFrames_[0];
       unsigned int nFrames = kSynthesisBlockSize;
       unsigned int stride = outputFrames_.channels();
       // edge case
       if (count_ == len_){
         finished_ = true;
       }
       if (finished_){
         #ifdef USE_APPLE_ACCELERATE
         vDSP_vfill(&last_, fdata, stride, nFrames);
         #else
         for (unsigned int i=0; i<nFrames; i++){
           *fdata = last_;
           fdata += stride;
         }
         #endif
       }
       else{
         // figure out if we will finish the ramp in this tick
         unsigned long remainder = count_ > len_ ? 0 : len_ - count_;
         if (remainder < nFrames){
           // fill part of the ramp - no need to check if remainder is 1 when using vramp
           // uses algorithm out[n] = start + n * increment;
           #ifdef USE_APPLE_ACCELERATE
           // starting point
           last_ += inc_;
           vDSP_vramp(&last_, &inc_, fdata, stride, remainder);
             #ifdef TONIC_DEBUG
             if(*fdata != *fdata){
               Tonic::error("RampedValue_::computeSynthesisBlock NaN detected.\n");
             }
             #endif
           #else
           for (unsigned int i=0; i<remainder; i++){
             last_ += inc_;
             *fdata = last_;
             fdata += stride;
           }
           #endif
           #ifdef USE_APPLE_ACCELERATE
           vDSP_vfill(&target_, fdata + remainder, stride, nFrames - remainder);
           #else
           for (unsigned int i=remainder; i<nFrames; i++){
             *fdata = target_;
             fdata += stride;
           }
           #endif
           count_ = len_;
           last_ = target_;
           finished_ = true;
         }
         else{
           // fill the whole ramp
           #ifdef USE_APPLE_ACCELERATE
           last_ += inc_;
           vDSP_vramp(&last_, &inc_, fdata, stride, nFrames);
             #ifdef TONIC_DEBUG
             if(*fdata != *fdata){
               Tonic::error("RampedValue_::computeSynthesisBlock NaN detected.\n");
             }
             #endif
           #else
           for (unsigned int i=0; i<nFrames; i++){
             last_ += inc_;
             *fdata = last_;
             fdata += stride;
           }
           #endif
           count_ += nFrames;
           last_ = outputFrames_(nFrames - 1, 0);
         }
       }
       #ifdef TONIC_DEBUG
       if(*fdata != *fdata){
         Tonic::error("RampedValue_::computeSynthesisBlock NaN detected.\n");
       }
       #endif
       // mono source, so need to fill out channels if necessary
       outputFrames_.fillChannels();
     }
isFinished()
bool Tonic::Tonic_::RampedValue_::isFinished ()
Definition at line 29 of file RampedValue.cpp.
References finished_.
{
     return finished_;
   }
setLengthGen()
void Tonic::Tonic_::RampedValue_::setLengthGen (ControlGenerator length) inline
Definition at line 177 of file RampedValue.h.
References lengthGen_.
{
       lengthGen_ = length;
     }
setTargetGen()
void Tonic::Tonic_::RampedValue_::setTargetGen (ControlGenerator target) inline
Definition at line 173 of file RampedValue.h.
References targetGen_.
{
       targetGen_ = target;
     }
setValueGen()
void Tonic::Tonic_::RampedValue_::setValueGen (ControlGenerator value) inline
Definition at line 169 of file RampedValue.h.
References valueGen_.
{
       valueGen_ = value;
     }
updateTarget()
void Tonic::Tonic_::RampedValue_::updateTarget (TonicFloat target, unsigned long lengthSamp) inline
Definition at line 194 of file RampedValue.h.
References count_, Tonic::error(), finished_, inc_, last_, len_, and target_.
{
       target_ = target;
       count_ = 0;
       // ND- Fixes bug with NaN when using Accelerate ramps
       if (lengthSamp == 0 || target_ == last_){
         last_ = target_;
         finished_ = true;
         inc_ = 0;
       }
       else{
         len_ = lengthSamp;
         inc_ = (TonicFloat)(target_ - last_)/len_;
         finished_ = false;
       }
       #ifdef TONIC_DEBUG
       if(inc_ != inc_){
         Tonic::error("RampedValue_::updateTarget NaN found\n");
       }
       #endif
     }
updateValue()
void Tonic::Tonic_::RampedValue_::updateValue (TonicFloat value) inline
Definition at line 183 of file RampedValue.h.
References count_, finished_, inc_, last_, and target_.
{
       // When the value gen changes, immediately abort the current ramp and go to the new value.
       finished_ = true;
       last_ = value;
       target_ = value;
       inc_ = 0;
       count_ = 0;
     }
Member Data Documentation
count_
unsigned long Tonic::Tonic_::RampedValue_::count_ protected
Definition at line 28 of file RampedValue.h.
finished_
bool Tonic::Tonic_::RampedValue_::finished_ protected
Definition at line 27 of file RampedValue.h.
inc_
TonicFloat Tonic::Tonic_::RampedValue_::inc_ protected
Definition at line 32 of file RampedValue.h.
last_
TonicFloat Tonic::Tonic_::RampedValue_::last_ protected
Definition at line 31 of file RampedValue.h.
len_
unsigned long Tonic::Tonic_::RampedValue_::len_ protected
Definition at line 29 of file RampedValue.h.
lengthGen_
ControlGenerator Tonic::Tonic_::RampedValue_::lengthGen_ protected
Definition at line 34 of file RampedValue.h.
target_
TonicFloat Tonic::Tonic_::RampedValue_::target_ protected
Definition at line 30 of file RampedValue.h.
targetGen_
ControlGenerator Tonic::Tonic_::RampedValue_::targetGen_ protected
Definition at line 33 of file RampedValue.h.
valueGen_
ControlGenerator Tonic::Tonic_::RampedValue_::valueGen_ protected
Definition at line 35 of file RampedValue.h.
The documentation for this class was generated from the following files:
RampedValue.h
RampedValue.cpp