YOURPROJECTNAMEGOESHERE: Tonic::RingBufferWriter Class Reference
Tonic::RingBufferWriter Class Reference
#include <RingBuffer.h>
Public Member Functions
RingBufferWriter ()
RingBufferWriter (string name, unsigned int nFrames, unsigned int nChannels)
void write (float *data, unsigned int nFrames, unsigned int nChannels)
void reset ()
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::RingBufferWriter_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::RingBufferWriter_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::RingBufferWriter_ >
Tonic_::RingBufferWriter_ * obj
int * pcount
Detailed Description
Definition at line 252 of file RingBuffer.h.
Constructor & Destructor Documentation
RingBufferWriter() [1/2]
Tonic::RingBufferWriter::RingBufferWriter () inline
Definition at line 256 of file RingBuffer.h.
 : TonicSmartPointer<Tonic_::RingBufferWriter_>(new Tonic_::RingBufferWriter_) {}
RingBufferWriter() [2/2]
Tonic::RingBufferWriter::RingBufferWriter (string name, unsigned int nFrames, unsigned int nChannels)
Definition at line 59 of file RingBuffer.cpp.
References Tonic::Tonic_::RingBufferWriter_::initRingBuffer(), and Tonic::TonicSmartPointer< Tonic_::RingBufferWriter_ >::obj.
   {
     obj = new Tonic_::RingBufferWriter_();
     obj->initRingBuffer(name, nFrames, nChannels);
   }
Member Function Documentation
reset()
void Tonic::RingBufferWriter::reset () inline
Definition at line 263 of file RingBuffer.h.
References Tonic::TonicSmartPointer< Tonic_::RingBufferWriter_ >::obj, and Tonic::Tonic_::RingBufferWriter_::reset().
                   {
         obj->reset();
       }
write()
void Tonic::RingBufferWriter::write (float * data, unsigned int nFrames, unsigned int nChannels) inline
Definition at line 259 of file RingBuffer.h.
References Tonic::TonicSmartPointer< Tonic_::RingBufferWriter_ >::obj, and Tonic::Tonic_::RingBufferWriter_::write().
{
         obj->write(data, nFrames, nChannels);
       }
The documentation for this class was generated from the following files:
RingBuffer.h
RingBuffer.cpp