YOURPROJECTNAMEGOESHERE: Tonic::FixedValue Class Reference
Tonic::FixedValue Class Reference
#include <FixedValue.h>
Public Member Functions
FixedValue ()
FixedValue (float val)
FixedValue & setValue (float val)
FixedValue & setValue (ControlGenerator val)
Public Member Functions inherited from Tonic::TemplatedGenerator< Tonic_::FixedValue_ >
TemplatedGenerator ()
Public Member Functions inherited from Tonic::Generator
Generator (Tonic_::Generator_ *gen=new Tonic_::Generator_)
bool isStereoOutput ()
virtual void tick (TonicFrames &frames, const Tonic_::SynthesisContext_ &context)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::Generator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Public Types inherited from Tonic::TemplatedGenerator< Tonic_::FixedValue_ >
typedef Tonic_::FixedValue_ gen_t
Protected Member Functions inherited from Tonic::TemplatedGenerator< Tonic_::FixedValue_ >
Tonic_::FixedValue_ * gen ()
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
Tonic_::Generator_ * obj
int * pcount
Detailed Description
Definition at line 63 of file FixedValue.h.
Constructor & Destructor Documentation
FixedValue() [1/2]
Tonic::FixedValue::FixedValue () inline
Definition at line 65 of file FixedValue.h.
 {}
FixedValue() [2/2]
Tonic::FixedValue::FixedValue (float val) inline
Definition at line 66 of file FixedValue.h.
References setValue().
{
       setValue(val);
     }
Member Function Documentation
setValue() [1/2]
FixedValue& Tonic::FixedValue::setValue (float val) inline
Definition at line 69 of file FixedValue.h.
References Tonic::TemplatedGenerator< Tonic_::FixedValue_ >::gen(), and Tonic::Tonic_::FixedValue_::setValue().
{
       gen()->setValue(ControlValue(val));
       return *this;
     }
setValue() [2/2]
FixedValue& Tonic::FixedValue::setValue (ControlGenerator val) inline
Definition at line 73 of file FixedValue.h.
References Tonic::TemplatedGenerator< Tonic_::FixedValue_ >::gen(), and Tonic::Tonic_::FixedValue_::setValue().
{
       gen()->setValue(val);
       return *this;
     }
The documentation for this class was generated from the following file:
FixedValue.h