YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::Generator_ Class Reference
Tonic::Tonic_::Generator_ Class Reference
#include <Generator.h>
Public Member Functions
Generator_ ()
virtual ~Generator_ ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
virtual void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 22 of file Generator.h.
Constructor & Destructor Documentation
Generator_()
Tonic::Tonic_::Generator_::Generator_ ()
Definition at line 16 of file Generator.cpp.
References Tonic::kSynthesisBlockSize, outputFrames_, and Tonic::TonicFrames::resize().
                          : lastFrameIndex_(0), isStereoOutput_(false){
     outputFrames_.resize(kSynthesisBlockSize, 1, 0);
   }
~Generator_()
Tonic::Tonic_::Generator_::~Generator_ () virtual
Definition at line 20 of file Generator.cpp.
 {}
Member Function Documentation
computeSynthesisBlock()
virtual void Tonic::Tonic_::Generator_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented in Tonic::Tonic_::Divider_, Tonic::Tonic_::Multiplier_, Tonic::Tonic_::RingBufferReader_, Tonic::Tonic_::Subtractor_, Tonic::Tonic_::SawtoothWaveBL_, Tonic::Tonic_::Reverb_, Tonic::Tonic_::FilteredFBCombFilter6_, Tonic::Tonic_::RectWaveBL_, Tonic::Tonic_::FBCombFilter_, Tonic::Tonic_::ADSR_, Tonic::Tonic_::Filter_, Tonic::Tonic_::PinkNoise_, Tonic::Tonic_::FFCombFilter_, Tonic::Tonic_::Compressor_, Tonic::Tonic_::TableLookupOsc_, Tonic::Tonic_::Synth_, Tonic::Tonic_::BufferPlayer_, Tonic::Tonic_::RectWave_, Tonic::Tonic_::AngularWave_, Tonic::Tonic_::RampedValue_, Tonic::Tonic_::BasicDelay_, Tonic::Tonic_::StereoDelay_, Tonic::Tonic_::Mixer_, Tonic::Tonic_::Adder_, Tonic::Tonic_::LFNoise_, Tonic::Tonic_::MonoToStereoPanner_, Tonic::Tonic_::FixedValue_, Tonic::Tonic_::BitCrusher_, and Tonic::Tonic_::Noise_.
Definition at line 41 of file Generator.h.
 {};
isStereoOutput()
bool Tonic::Tonic_::Generator_::isStereoOutput () inline
Definition at line 31 of file Generator.h.
References isStereoOutput_.
 { return isStereoOutput_; };
setIsStereoOutput()
void Tonic::Tonic_::Generator_::setIsStereoOutput (bool stereo) virtual
Reimplemented in Tonic::Tonic_::Divider_, Tonic::Tonic_::Multiplier_, Tonic::Tonic_::Subtractor_, and Tonic::Tonic_::Adder_.
Definition at line 22 of file Generator.cpp.
References isStereoOutput_, Tonic::kSynthesisBlockSize, outputFrames_, and Tonic::TonicFrames::resize().
{
     if (stereo != isStereoOutput_){
       outputFrames_.resize(kSynthesisBlockSize, stereo ? 2 : 1, 0);
     }
     isStereoOutput_ = stereo;
   }
tick()
void Tonic::Tonic_::Generator_::tick (TonicFrames & frames, const SynthesisContext_ & context) inline virtual
Reimplemented in Tonic::Tonic_::WetDryEffect_, Tonic::Tonic_::Compressor_, and Tonic::Tonic_::Effect_.
Definition at line 50 of file Generator.h.
References computeSynthesisBlock(), Tonic::TonicFrames::copy(), Tonic::Tonic_::SynthesisContext_::elapsedFrames, Tonic::Tonic_::SynthesisContext_::forceNewOutput, lastFrameIndex_, and outputFrames_.
{
       // check context to see if we need new frames
       if (context.forceNewOutput || lastFrameIndex_ != context.elapsedFrames){
         computeSynthesisBlock(context);
         lastFrameIndex_ = context.elapsedFrames;
       }
       // copy synthesis block to frames passed in
       frames.copy(outputFrames_);
     }
Member Data Documentation
isStereoOutput_
bool Tonic::Tonic_::Generator_::isStereoOutput_ protected
Definition at line 41 of file Generator.h.
lastFrameIndex_
unsigned long Tonic::Tonic_::Generator_::lastFrameIndex_ protected
Definition at line 46 of file Generator.h.
outputFrames_
TonicFrames Tonic::Tonic_::Generator_::outputFrames_ protected
Definition at line 45 of file Generator.h.
The documentation for this class was generated from the following files:
Generator.h
Generator.cpp