YOURPROJECTNAMEGOESHERE: Tonic::RampedValue Class Reference
Tonic::RampedValue Class Reference
#include <RampedValue.h>
Public Member Functions
RampedValue (TonicFloat startValue=0, TonicFloat initLength=0.05)
TONIC_MAKE_CTRL_GEN_SETTERS (RampedValue, target, setTargetGen)
Set target value.
TONIC_MAKE_CTRL_GEN_SETTERS (RampedValue, length, setLengthGen)
Set length before reaching target value, in ms.
TONIC_MAKE_CTRL_GEN_SETTERS (RampedValue, value, setValueGen)
Go to value immediately.
Adder operator+ (Generator b)
Adder operator+ (float b)
Subtractor operator- (Generator b)
Subtractor operator- (float b)
Multiplier operator* (Generator b)
Multiplier operator* (float b)
Divider operator/ (Generator b)
Divider operator/ (float b)
bool isFinished ()
Public Member Functions inherited from Tonic::TemplatedGenerator< Tonic_::RampedValue_ >
TemplatedGenerator ()
Public Member Functions inherited from Tonic::Generator
Generator (Tonic_::Generator_ *gen=new Tonic_::Generator_)
bool isStereoOutput ()
virtual void tick (TonicFrames &frames, const Tonic_::SynthesisContext_ &context)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::Generator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Public Types inherited from Tonic::TemplatedGenerator< Tonic_::RampedValue_ >
typedef Tonic_::RampedValue_ gen_t
Protected Member Functions inherited from Tonic::TemplatedGenerator< Tonic_::RampedValue_ >
Tonic_::RampedValue_ * gen ()
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
Tonic_::Generator_ * obj
int * pcount
Detailed Description
Definition at line 225 of file RampedValue.h.
Constructor & Destructor Documentation
RampedValue()
Tonic::RampedValue::RampedValue (TonicFloat startValue = 0, TonicFloat initLength = 0.05) inline
Definition at line 229 of file RampedValue.h.
{
       target(startValue);
       value(startValue);
       length(initLength);
     }
Member Function Documentation
isFinished()
bool Tonic::RampedValue::isFinished ()
Definition at line 92 of file RampedValue.cpp.
References Tonic::TemplatedGenerator< Tonic_::RampedValue_ >::gen(), and Tonic::Tonic_::RampedValue_::isFinished().
{
     return gen()->isFinished();
   }
operator*() [1/2]
Multiplier Tonic::RampedValue::operator* (Generator b)
Definition at line 64 of file RampedValue.cpp.
References Tonic::Multiplier::input().
{
    Multiplier mult;
    mult.input(*this);
    mult.input(b);
    return mult;
  }
operator*() [2/2]
Multiplier Tonic::RampedValue::operator* (float b)
Definition at line 71 of file RampedValue.cpp.
References Tonic::Multiplier::input().
{
    Multiplier mult;
    mult.input(*this);
    mult.input(FixedValue(b));
    return mult;
  }
operator+() [1/2]
Adder Tonic::RampedValue::operator+ (Generator b)
Definition at line 36 of file RampedValue.cpp.
References Tonic::Adder::input().
{
    Adder adder;
    adder.input(*this);
    adder.input(b);
    return adder;
  }
operator+() [2/2]
Adder Tonic::RampedValue::operator+ (float b)
Definition at line 43 of file RampedValue.cpp.
References Tonic::Adder::input().
{
    Adder adder;
    adder.input(*this);
    adder.input(FixedValue(b));
    return adder;
  }
operator-() [1/2]
Subtractor Tonic::RampedValue::operator- (Generator b)
Definition at line 50 of file RampedValue.cpp.
{
    Subtractor subtractor;
    subtractor.left(*this);
    subtractor.right(b);
    return subtractor;
  }
operator-() [2/2]
Subtractor Tonic::RampedValue::operator- (float b)
Definition at line 57 of file RampedValue.cpp.
{
    Subtractor subtractor;
    subtractor.left(*this);
    subtractor.right(FixedValue(b));
    return subtractor;
  }
operator/() [1/2]
Divider Tonic::RampedValue::operator/ (Generator b)
Definition at line 79 of file RampedValue.cpp.
{
    Divider divider;
    divider.left(*this);
    divider.right(b);
    return divider;
  }
operator/() [2/2]
Divider Tonic::RampedValue::operator/ (float b)
Definition at line 86 of file RampedValue.cpp.
{
    Divider divider;
    divider.left(*this);
    divider.right(FixedValue(b));
    return divider;
  }
TONIC_MAKE_CTRL_GEN_SETTERS() [1/3]
Tonic::RampedValue::TONIC_MAKE_CTRL_GEN_SETTERS (RampedValue , target , setTargetGen)
Set target value.
Changes to target gen input will create a new ramp from current value to target over the current length
TONIC_MAKE_CTRL_GEN_SETTERS() [2/3]
Tonic::RampedValue::TONIC_MAKE_CTRL_GEN_SETTERS (RampedValue , length , setLengthGen)
Set length before reaching target value, in ms.
Changes to length gen input will create a new ramp from current value to target over the provided length
TONIC_MAKE_CTRL_GEN_SETTERS() [3/3]
Tonic::RampedValue::TONIC_MAKE_CTRL_GEN_SETTERS (RampedValue , value , setValueGen)
Go to value immediately.
Changes to the value gen input will abort the current ramp and go immediately to the specified value. Output will remain steady until a new target or length is set.
The documentation for this class was generated from the following files:
RampedValue.h
RampedValue.cpp