YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::Effect_ Class Reference
Tonic::Tonic_::Effect_ Class Reference
#include <Effect.h>
Public Member Functions
Effect_ ()
void setBypassCtrlGen (ControlGenerator gen)
virtual void setInput (Generator input)
virtual void setIsStereoInput (bool stereo)
set stereo/mono - changes number of channels in dryFrames_
bool isStereoInput ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
virtual void tickThrough (TonicFrames &inFrames, TonicFrames &outFrames, const SynthesisContext_ &context)
Apply effect directly to passed in frames (output in-place)
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Attributes
Generator input_
TonicFrames dryFrames_
ControlGenerator bypassGen_
bool isStereoInput_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Additional Inherited Members
Protected Member Functions inherited from Tonic::Tonic_::Generator_
virtual void computeSynthesisBlock (const SynthesisContext_ &context)
Detailed Description
Definition at line 21 of file Effect.h.
Constructor & Destructor Documentation
Effect_()
Tonic::Tonic_::Effect_::Effect_ ()
Definition at line 20 of file Effect.cpp.
References bypassGen_, dryFrames_, Tonic::kSynthesisBlockSize, and Tonic::TonicFrames::resize().
                      : isStereoInput_(false)
     {
       dryFrames_.resize(kSynthesisBlockSize, 1, 0);
       bypassGen_ = ControlValue(0);
     }
Member Function Documentation
isStereoInput()
bool Tonic::Tonic_::Effect_::isStereoInput () inline
Definition at line 45 of file Effect.h.
References isStereoInput_.
 { return isStereoInput_; };
setBypassCtrlGen()
void Tonic::Tonic_::Effect_::setBypassCtrlGen (ControlGenerator gen) inline
Definition at line 35 of file Effect.h.
References bypassGen_.
 { bypassGen_ = gen; };
setInput()
virtual void Tonic::Tonic_::Effect_::setInput (Generator input) inline virtual
Reimplemented in Tonic::Tonic_::Filter_, Tonic::Tonic_::Compressor_, Tonic::Tonic_::BasicDelay_, and Tonic::Tonic_::BitCrusher_.
Definition at line 37 of file Effect.h.
References input_.
 { input_ = input; };
setIsStereoInput()
void Tonic::Tonic_::Effect_::setIsStereoInput (bool stereo) inline virtual
set stereo/mono - changes number of channels in dryFrames_
subclasses should call in constructor to determine input channel layout
Reimplemented in Tonic::Tonic_::BPF24_, Tonic::Tonic_::BPF12_, Tonic::Tonic_::HPF24_, Tonic::Tonic_::HPF12_, Tonic::Tonic_::LPF24_, Tonic::Tonic_::LPF12_, and Tonic::Tonic_::BitCrusher_.
Definition at line 60 of file Effect.h.
References dryFrames_, isStereoInput_, Tonic::kSynthesisBlockSize, and Tonic::TonicFrames::resize().
     {
       if (stereo != isStereoInput_){
         dryFrames_.resize(kSynthesisBlockSize, stereo ? 2 : 1, 0);
       }
       isStereoInput_ = stereo;
     }
tick()
void Tonic::Tonic_::Effect_::tick (TonicFrames & frames, const SynthesisContext_ & context) inline virtual
Reimplemented from Tonic::Tonic_::Generator_.
Reimplemented in Tonic::Tonic_::WetDryEffect_, and Tonic::Tonic_::Compressor_.
Definition at line 71 of file Effect.h.
References bypassGen_, Tonic::Tonic_::Generator_::computeSynthesisBlock(), Tonic::TonicFrames::copy(), dryFrames_, Tonic::Tonic_::SynthesisContext_::elapsedFrames, Tonic::error(), input_, Tonic::Tonic_::Generator_::lastFrameIndex_, Tonic::Tonic_::Generator_::outputFrames_, Tonic::Generator::tick(), Tonic::ControlGenerator::tick(), and Tonic::ControlGeneratorOutput::value.
{
       // check context to see if we need new frames
       if (context.elapsedFrames == 0 || lastFrameIndex_ != context.elapsedFrames){
         // get dry input frames
         input_.tick(dryFrames_, context);
         computeSynthesisBlock(context);
         // bypass processing - still need to compute block so all generators stay in sync
         bool bypass = bypassGen_.tick(context).value != 0.f;
         if (bypass){
           outputFrames_.copy(dryFrames_);
         }
         lastFrameIndex_ = context.elapsedFrames;
       }
       // copy synthesis block to frames passed in
       frames.copy(outputFrames_);
 #ifdef TONIC_DEBUG
       if(!isfinite(frames(0,0))){
         Tonic::error("Effect_::tick NaN or inf detected.");
       }
 #endif
     }
tickThrough()
void Tonic::Tonic_::Effect_::tickThrough (TonicFrames & inFrames, TonicFrames & outFrames, const SynthesisContext_ & context) inline virtual
Apply effect directly to passed in frames (output in-place)
DO NOT mix calls to tick() with calls to tickThrough().
Reimplemented in Tonic::Tonic_::WetDryEffect_, and Tonic::Tonic_::Compressor_.
Definition at line 101 of file Effect.h.
References bypassGen_, Tonic::Tonic_::Generator_::computeSynthesisBlock(), Tonic::TonicFrames::copy(), dryFrames_, Tonic::Tonic_::Generator_::outputFrames_, Tonic::ControlGenerator::tick(), and Tonic::ControlGeneratorOutput::value.
{
         // Do not check context here, assume each call should produce new output.
         dryFrames_.copy(inFrames);
         computeSynthesisBlock(context);
         // bypass processing - still need to compute block so all generators stay in sync
         bool bypass = bypassGen_.tick(context).value != 0.f;
         if (bypass){
           outFrames.copy(dryFrames_);
         }
         else{
           outFrames.copy(outputFrames_);
         }
     }
Member Data Documentation
bypassGen_
ControlGenerator Tonic::Tonic_::Effect_::bypassGen_ protected
Definition at line 28 of file Effect.h.
dryFrames_
TonicFrames Tonic::Tonic_::Effect_::dryFrames_ protected
Definition at line 26 of file Effect.h.
input_
Generator Tonic::Tonic_::Effect_::input_ protected
Definition at line 25 of file Effect.h.
isStereoInput_
bool Tonic::Tonic_::Effect_::isStereoInput_ protected
Definition at line 29 of file Effect.h.
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp