YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::BufferFiller_ Class Reference
Tonic::Tonic_::BufferFiller_ Class Reference
Base class for any generator expected to produce output for a buffer fill.
#include <BufferFiller.h>
Public Member Functions
BufferFiller_ ()
~BufferFiller_ ()
void lockMutex ()
void unlockMutex ()
void tick (TonicFrames &frames)
Process a single synthesis vector, output to frames.
void fillBufferOfFloats (float *outData, unsigned int numFrames, unsigned int numChannels)
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Attributes
Tonic_::SynthesisContext_ synthContext_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Private Attributes
unsigned long bufferReadPosition_
Additional Inherited Members
Protected Member Functions inherited from Tonic::Tonic_::Generator_
virtual void computeSynthesisBlock (const SynthesisContext_ &context)
Detailed Description
Base class for any generator expected to produce output for a buffer fill.
BufferFillers provide a high-level interface for combinations of generators, and can be used to fill arbitraryly large buffers.
Subclasses to include mixer, channel, synth, etc.
Definition at line 28 of file BufferFiller.h.
Constructor & Destructor Documentation
BufferFiller_()
Tonic::Tonic_::BufferFiller_::BufferFiller_ ()
Definition at line 18 of file BufferFiller.cpp.
References Tonic::Tonic_::Generator_::setIsStereoOutput().
                                  :  bufferReadPosition_(0) {
       setIsStereoOutput(true);
     }
~BufferFiller_()
Tonic::Tonic_::BufferFiller_::~BufferFiller_ ()
Definition at line 22 of file BufferFiller.cpp.
{
     }
Member Function Documentation
fillBufferOfFloats()
void Tonic::Tonic_::BufferFiller_::fillBufferOfFloats (float * outData, unsigned int numFrames, unsigned int numChannels) inline
Definition at line 63 of file BufferFiller.h.
References bufferReadPosition_, Tonic::TonicFrames::channels(), Tonic::error(), Tonic::Tonic_::Generator_::outputFrames_, Tonic::TonicFrames::size(), tick(), and TONIC_ENABLE_DENORMAL_ROUNDING.
     {
       // flush denormals on this thread
       TONIC_ENABLE_DENORMAL_ROUNDING();
 #ifdef TONIC_DEBUG
       if(numChannels > outputFrames_.channels()) error("Mismatch in channels sent to Synth::fillBufferOfFloats", true);
 #endif
       const unsigned long sampleCount = outputFrames_.size();
       const unsigned int channelsPerSample = (outputFrames_.channels() - numChannels) + 1;
       TonicFloat sample = 0.0f;
       TonicFloat *outputSamples = &outputFrames_[bufferReadPosition_];
       for(unsigned int i = 0; i<numFrames * numChannels; i++){
         sample = 0;
         for (unsigned int c = 0; c<channelsPerSample; c++){
           if(bufferReadPosition_ == 0){
             tick(outputFrames_);
           }
           sample += *outputSamples++;
           if(++bufferReadPosition_ == sampleCount){
             bufferReadPosition_ = 0;
             outputSamples = &outputFrames_[0];
           }
         }
         *outData++ = sample / (float)channelsPerSample;
       }
     }
lockMutex()
void Tonic::Tonic_::BufferFiller_::lockMutex ()
tick()
void Tonic::Tonic_::BufferFiller_::tick (TonicFrames & frames) inline
Process a single synthesis vector, output to frames.
tick method without context argument passes down this instance's SynthesisContext_
Definition at line 58 of file BufferFiller.h.
References synthContext_, Tonic::Tonic_::Generator_::tick(), and Tonic::Tonic_::SynthesisContext_::tick().
{
       Generator_::tick(frames, synthContext_);
       synthContext_.tick();
     }
unlockMutex()
void Tonic::Tonic_::BufferFiller_::unlockMutex ()
Member Data Documentation
bufferReadPosition_
unsigned long Tonic::Tonic_::BufferFiller_::bufferReadPosition_ private
Definition at line 32 of file BufferFiller.h.
synthContext_
Tonic_::SynthesisContext_ Tonic::Tonic_::BufferFiller_::synthContext_ protected
Definition at line 36 of file BufferFiller.h.
The documentation for this class was generated from the following files:
BufferFiller.h
BufferFiller.cpp