YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::BitCrusher_ Class Reference
Tonic::Tonic_::BitCrusher_ Class Reference
#include <BitCrusher.h>
Public Member Functions
BitCrusher_ ()
void setBitDepth (ControlGenerator)
void setInput (Generator input)
void setIsStereoInput (bool stereo)
set stereo/mono - changes number of channels in dryFrames_
Public Member Functions inherited from Tonic::Tonic_::Effect_
Effect_ ()
void setBypassCtrlGen (ControlGenerator gen)
bool isStereoInput ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
virtual void tickThrough (TonicFrames &inFrames, TonicFrames &outFrames, const SynthesisContext_ &context)
Apply effect directly to passed in frames (output in-place)
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
ControlGenerator bitDepth
Protected Attributes inherited from Tonic::Tonic_::Effect_
Generator input_
TonicFrames dryFrames_
ControlGenerator bypassGen_
bool isStereoInput_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 21 of file BitCrusher.h.
Constructor & Destructor Documentation
BitCrusher_()
Tonic::Tonic_::BitCrusher_::BitCrusher_ ()
Definition at line 14 of file BitCrusher.cpp.
References setBitDepth().
{
         setBitDepth(ControlValue(16));
       }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::BitCrusher_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 36 of file BitCrusher.h.
References bitDepth, Tonic::clamp(), Tonic::Tonic_::Effect_::dryFrames_, Tonic::Tonic_::Generator_::outputFrames_, Tonic::TonicFrames::size(), Tonic::ControlGenerator::tick(), and Tonic::ControlGeneratorOutput::value.
{
       TonicFloat *synthBlockWriteHead = &outputFrames_[0];
       TonicFloat *dryFramesReadHead = &dryFrames_[0];
       unsigned int nSamples = (unsigned int)outputFrames_.size();
       float bitDepthValue = clamp(bitDepth.tick(context).value, 0, 16) ;
       float bitDepthMax = pow(2, bitDepthValue);
       while (nSamples--){
         TonicFloat dry = *(dryFramesReadHead++);
         TonicInt32 snapped = bitDepthMax * dry;
         TonicFloat snappedFloat = (float)snapped/(float)bitDepthMax;
         *(synthBlockWriteHead++) =  snappedFloat;
       }
     }
setBitDepth()
void Tonic::Tonic_::BitCrusher_::setBitDepth (ControlGenerator bitDepthArg)
Definition at line 32 of file BitCrusher.cpp.
References bitDepth.
{
         bitDepth = bitDepthArg;
       }
setInput()
void Tonic::Tonic_::BitCrusher_::setInput (Generator input) virtual
Reimplemented from Tonic::Tonic_::Effect_.
Definition at line 18 of file BitCrusher.cpp.
References Tonic::Tonic_::Effect_::input_, Tonic::Generator::isStereoOutput(), and setIsStereoInput().
{
         input_ = input;
         setIsStereoInput(input_.isStereoOutput());
       };
setIsStereoInput()
void Tonic::Tonic_::BitCrusher_::setIsStereoInput (bool stereo) virtual
set stereo/mono - changes number of channels in dryFrames_
subclasses should call in constructor to determine input channel layout
Reimplemented from Tonic::Tonic_::Effect_.
Definition at line 23 of file BitCrusher.cpp.
References Tonic::Tonic_::Effect_::dryFrames_, Tonic::Tonic_::Effect_::isStereoInput_, Tonic::Tonic_::Generator_::isStereoOutput_, Tonic::kSynthesisBlockSize, Tonic::Tonic_::Generator_::outputFrames_, and Tonic::TonicFrames::resize().
{
         if (stereo != isStereoInput_){
           dryFrames_.resize(kSynthesisBlockSize, stereo ? 2 : 1, 0);
           outputFrames_.resize(kSynthesisBlockSize, stereo ? 2 : 1, 0);
         }
         isStereoInput_ = stereo;
         isStereoOutput_ = stereo;
       };
Member Data Documentation
bitDepth
ControlGenerator Tonic::Tonic_::BitCrusher_::bitDepth protected
Definition at line 24 of file BitCrusher.h.
The documentation for this class was generated from the following files:
BitCrusher.h
BitCrusher.cpp