YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::FBCombFilter_ Class Reference
Tonic::Tonic_::FBCombFilter_ Class Reference
Basic mono feedback comb filter with hook for aditional processing pre-feedback.
#include <CombFilter.h>
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Additional Inherited Members
Public Member Functions inherited from Tonic::Tonic_::CombFilter_
CombFilter_ ()
void initialize (float initialDelayTime, float maxDelayTime)
void setDelayTimeGen (Generator gen)
void setScaleFactorGen (ControlGenerator gen)
Public Member Functions inherited from Tonic::Tonic_::Effect_
Effect_ ()
void setBypassCtrlGen (ControlGenerator gen)
virtual void setInput (Generator input)
virtual void setIsStereoInput (bool stereo)
set stereo/mono - changes number of channels in dryFrames_
bool isStereoInput ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
virtual void tickThrough (TonicFrames &inFrames, TonicFrames &outFrames, const SynthesisContext_ &context)
Apply effect directly to passed in frames (output in-place)
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Attributes inherited from Tonic::Tonic_::CombFilter_
DelayLine delayLine_
Generator delayTimeGen_
ControlGenerator scaleFactorCtrlGen_
TonicFrames delayTimeFrames_
Protected Attributes inherited from Tonic::Tonic_::Effect_
Generator input_
TonicFrames dryFrames_
ControlGenerator bypassGen_
bool isStereoInput_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Basic mono feedback comb filter with hook for aditional processing pre-feedback.
Definition at line 72 of file CombFilter.h.
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::FBCombFilter_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 76 of file CombFilter.h.
References Tonic::DelayLine::advance(), Tonic::Tonic_::CombFilter_::delayLine_, Tonic::Tonic_::CombFilter_::delayTimeFrames_, Tonic::Tonic_::CombFilter_::delayTimeGen_, Tonic::Tonic_::Effect_::dryFrames_, Tonic::kSynthesisBlockSize, Tonic::Tonic_::Generator_::outputFrames_, Tonic::Tonic_::CombFilter_::scaleFactorCtrlGen_, Tonic::Generator::tick(), Tonic::ControlGenerator::tick(), Tonic::DelayLine::tickIn(), Tonic::DelayLine::tickOut(), and Tonic::ControlGeneratorOutput::value.
{
         // tick modulations
         delayTimeGen_.tick(delayTimeFrames_, context);
         TonicFloat y = 0;
         TonicFloat * inptr = &dryFrames_[0];
         TonicFloat * outptr = &outputFrames_[0];
         TonicFloat * dtptr = &delayTimeFrames_[0];
         TonicFloat sf = scaleFactorCtrlGen_.tick(context).value;
         TonicFloat norm = (1.0f/(1.0f + sf));
         for (unsigned int i=0; i<kSynthesisBlockSize; i++){
           y = ((delayLine_.tickOut(*dtptr++) * sf) + *inptr++) * norm;
           delayLine_.tickIn(y);
           *outptr++ = y;
           delayLine_.advance();
         }
       }
The documentation for this class was generated from the following file:
CombFilter.h