YOURPROJECTNAMEGOESHERE: Tonic::Multiplier Class Reference
Tonic::Multiplier Class Reference
#include <Arithmetic.h>
Public Member Functions
Multiplier input (Generator inputSource)
Generator operator[] (unsigned int index)
unsigned long numInputs ()
Public Member Functions inherited from Tonic::TemplatedGenerator< Tonic_::Multiplier_ >
TemplatedGenerator ()
Public Member Functions inherited from Tonic::Generator
Generator (Tonic_::Generator_ *gen=new Tonic_::Generator_)
bool isStereoOutput ()
virtual void tick (TonicFrames &frames, const Tonic_::SynthesisContext_ &context)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::Generator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Public Types inherited from Tonic::TemplatedGenerator< Tonic_::Multiplier_ >
typedef Tonic_::Multiplier_ gen_t
Protected Member Functions inherited from Tonic::TemplatedGenerator< Tonic_::Multiplier_ >
Tonic_::Multiplier_ * gen ()
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
Tonic_::Generator_ * obj
int * pcount
Detailed Description
Definition at line 243 of file Arithmetic.h.
Member Function Documentation
input()
Multiplier Tonic::Multiplier::input (Generator inputSource) inline
Definition at line 245 of file Arithmetic.h.
References Tonic::TemplatedGenerator< Tonic_::Multiplier_ >::gen(), and Tonic::Tonic_::Multiplier_::input().
{
       gen()->input(inputSource);
       return *this;
     }
numInputs()
unsigned long Tonic::Multiplier::numInputs () inline
Definition at line 254 of file Arithmetic.h.
References Tonic::TemplatedGenerator< Tonic_::Multiplier_ >::gen(), and Tonic::Tonic_::Multiplier_::numInputs().
{
       return gen()->numInputs();
     }
operator[]()
Generator Tonic::Multiplier::operator[] (unsigned int index) inline
Definition at line 250 of file Arithmetic.h.
References Tonic::TemplatedGenerator< Tonic_::Multiplier_ >::gen(), and Tonic::Tonic_::Multiplier_::getInput().
{
       return gen()->getInput(index);
     }
The documentation for this class was generated from the following file:
Arithmetic.h