YOURPROJECTNAMEGOESHERE: Tonic::ControlAdder Class Reference
Tonic::ControlAdder Class Reference
#include <ControlArithmetic.h>
Public Member Functions
void input (ControlGenerator input)
ControlGenerator operator[] (unsigned int index)
unsigned long numInputs ()
Public Member Functions inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlAdder_ >
TemplatedControlGenerator ()
Public Member Functions inherited from Tonic::ControlGenerator
ControlGenerator (Tonic_::ControlGenerator_ *cGen=new Tonic_::ControlGenerator_)
ControlGeneratorOutput tick (const Tonic_::SynthesisContext_ &context)
RampedValue smoothed (float length=0.05)
ControlAdder operator+ (ControlGenerator b)
ControlAdder operator+ (float b)
ControlSubtractor operator- (ControlGenerator b)
ControlSubtractor operator- (float b)
ControlMultiplier operator* (ControlGenerator b)
ControlMultiplier operator* (float b)
ControlDivider operator/ (ControlGenerator b)
ControlDivider operator/ (float b)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::ControlGenerator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Public Types inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlAdder_ >
typedef Tonic_::ControlAdder_ gen_t
Protected Member Functions inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlAdder_ >
Tonic_::ControlAdder_ * gen ()
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >
Tonic_::ControlGenerator_ * obj
int * pcount
Detailed Description
Definition at line 65 of file ControlArithmetic.h.
Member Function Documentation
input()
void Tonic::ControlAdder::input (ControlGenerator input) inline
Definition at line 69 of file ControlArithmetic.h.
References Tonic::TemplatedControlGenerator< Tonic_::ControlAdder_ >::gen(), and Tonic::Tonic_::ControlAdder_::input().
{
       gen()->input( input );
     }
numInputs()
unsigned long Tonic::ControlAdder::numInputs () inline
Definition at line 77 of file ControlArithmetic.h.
References Tonic::TemplatedControlGenerator< Tonic_::ControlAdder_ >::gen(), and Tonic::Tonic_::ControlAdder_::numInputs().
{
       return gen()->numInputs();
     }
operator[]()
ControlGenerator Tonic::ControlAdder::operator[] (unsigned int index) inline
Definition at line 73 of file ControlArithmetic.h.
References Tonic::TemplatedControlGenerator< Tonic_::ControlAdder_ >::gen(), and Tonic::Tonic_::ControlAdder_::getInput().
{
       return gen()->getInput(index);
     }
The documentation for this class was generated from the following file:
ControlArithmetic.h