YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::MonoToStereoPanner_ Class Reference
Tonic::Tonic_::MonoToStereoPanner_ Class Reference
#include <MonoToStereoPanner.h>
Public Member Functions
MonoToStereoPanner_ ()
~MonoToStereoPanner_ ()
void setPan (ControlGenerator)
Public Member Functions inherited from Tonic::Tonic_::Effect_
Effect_ ()
void setBypassCtrlGen (ControlGenerator gen)
virtual void setInput (Generator input)
virtual void setIsStereoInput (bool stereo)
set stereo/mono - changes number of channels in dryFrames_
bool isStereoInput ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
virtual void tickThrough (TonicFrames &inFrames, TonicFrames &outFrames, const SynthesisContext_ &context)
Apply effect directly to passed in frames (output in-place)
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Attributes
ControlGenerator panControlGen
TonicFrames panFrames
Protected Attributes inherited from Tonic::Tonic_::Effect_
Generator input_
TonicFrames dryFrames_
ControlGenerator bypassGen_
bool isStereoInput_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 23 of file MonoToStereoPanner.h.
Constructor & Destructor Documentation
MonoToStereoPanner_()
Tonic::Tonic_::MonoToStereoPanner_::MonoToStereoPanner_ ()
Definition at line 15 of file MonoToStereoPanner.cpp.
References Tonic::kSynthesisBlockSize, panFrames, Tonic::TonicFrames::resize(), Tonic::Tonic_::Generator_::setIsStereoOutput(), and setPan().
{
       setIsStereoOutput(true);
       panFrames.resize(kSynthesisBlockSize, 1);
       setPan(ControlValue(0));
     }
~MonoToStereoPanner_()
Tonic::Tonic_::MonoToStereoPanner_::~MonoToStereoPanner_ ()
Definition at line 20 of file MonoToStereoPanner.cpp.
 {}
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::MonoToStereoPanner_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 38 of file MonoToStereoPanner.h.
References Tonic::Tonic_::Effect_::dryFrames_, Tonic::kSynthesisBlockSize, Tonic::max(), Tonic::min(), Tonic::Tonic_::Generator_::outputFrames_, panControlGen, Tonic::ControlGenerator::tick(), and Tonic::ControlGeneratorOutput::value.
{
       TonicFloat *synthBlockWriteHead = &outputFrames_[0];
       TonicFloat *dryFramesReadHead = &dryFrames_[0];
       unsigned int nSamples = kSynthesisBlockSize;
       float panValue = panControlGen.tick(context).value;
       float leftVol = 1. - max(0., panValue);
       float rightVol = 1 + min(0., panValue);
       while (nSamples--){
           *(synthBlockWriteHead++) = *dryFramesReadHead * leftVol;
           *(synthBlockWriteHead++) = *dryFramesReadHead++ * rightVol;
       }
     }
setPan()
void Tonic::Tonic_::MonoToStereoPanner_::setPan (ControlGenerator panArg)
Definition at line 22 of file MonoToStereoPanner.cpp.
References panControlGen.
{
       panControlGen = panArg;
     }
Member Data Documentation
panControlGen
ControlGenerator Tonic::Tonic_::MonoToStereoPanner_::panControlGen protected
Definition at line 26 of file MonoToStereoPanner.h.
panFrames
TonicFrames Tonic::Tonic_::MonoToStereoPanner_::panFrames protected
Definition at line 27 of file MonoToStereoPanner.h.
The documentation for this class was generated from the following files:
MonoToStereoPanner.h
MonoToStereoPanner.cpp