YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::ControlParameter_ Class Reference
Tonic::Tonic_::ControlParameter_ Class Reference
Parameter for controlling a Synth instance.
#include <ControlParameter.h>
Public Member Functions
ControlParameter_ ()
void setName (string name)
string getName ()
void setDisplayName (string displayName)
string getDisplayName ()
void setMin (TonicFloat min)
TonicFloat getMin ()
void setMax (TonicFloat max)
TonicFloat getMax ()
void setType (ControlParameterType type)
ControlParameterType getType ()
void setIsLogarithmic (bool isLogarithmic)
bool getIsLogarithmic ()
void setNormalizedValue (TonicFloat normVal)
TonicFloat getNormalizedValue ()
Public Member Functions inherited from Tonic::Tonic_::ControlValue_
ControlValue_ ()
void setValue (float value)
TonicFloat getValue ()
Public Member Functions inherited from Tonic::Tonic_::ControlGenerator_
ControlGenerator_ ()
virtual ~ControlGenerator_ ()
void lockMutex ()
void unlockMutex ()
virtual ControlGeneratorOutput tick (const SynthesisContext_ &context)
virtual ControlGeneratorOutput initialOutput ()
Protected Attributes
string name_
string displayName_
TonicFloat min_
TonicFloat max_
ControlParameterType type_
bool isLogarithmic_
Protected Attributes inherited from Tonic::Tonic_::ControlValue_
TonicFloat value_
bool changed_
Protected Attributes inherited from Tonic::Tonic_::ControlGenerator_
ControlGeneratorOutput output_
unsigned long lastFrameIndex_
Additional Inherited Members
Protected Member Functions inherited from Tonic::Tonic_::ControlValue_
void computeOutput (const SynthesisContext_ &context)
Override this function to implement a new ControlGenerator.
Detailed Description
Parameter for controlling a Synth instance.
ControlParameter acts like a ControlValue but provides an interface for exposing itself to a synth, including min, max, type, etc
Definition at line 34 of file ControlParameter.h.
Constructor & Destructor Documentation
ControlParameter_()
Tonic::Tonic_::ControlParameter_::ControlParameter_ ()
Definition at line 12 of file ControlParameter.cpp.
                                        :
     name_(""),
     displayName_(""),
     min_(0),
     max_(1),
     type_(ControlParameterTypeContinuous),
     isLogarithmic_(false)
   {
   }
Member Function Documentation
getDisplayName()
string Tonic::Tonic_::ControlParameter_::getDisplayName () inline
Definition at line 54 of file ControlParameter.h.
References displayName_.
 { return displayName_; };
getIsLogarithmic()
bool Tonic::Tonic_::ControlParameter_::getIsLogarithmic () inline
Definition at line 66 of file ControlParameter.h.
References isLogarithmic_.
 { return isLogarithmic_; };
getMax()
TonicFloat Tonic::Tonic_::ControlParameter_::getMax () inline
Definition at line 60 of file ControlParameter.h.
References max_.
 { return max_; };
getMin()
TonicFloat Tonic::Tonic_::ControlParameter_::getMin () inline
Definition at line 57 of file ControlParameter.h.
References min_.
 { return min_; };
getName()
string Tonic::Tonic_::ControlParameter_::getName () inline
Definition at line 51 of file ControlParameter.h.
References name_.
 { return name_; };
getNormalizedValue()
TonicFloat Tonic::Tonic_::ControlParameter_::getNormalizedValue ()
Definition at line 32 of file ControlParameter.cpp.
References isLogarithmic_, Tonic::map(), Tonic::mapLogToLin(), max_, min_, and Tonic::Tonic_::ControlValue_::value_.
{
     if (isLogarithmic_){
       return mapLogToLin(value_, min_, max_);
     }
     else{
       return map(value_, min_, max_, 0.f, 1.f, true);
     }
   }
getType()
ControlParameterType Tonic::Tonic_::ControlParameter_::getType () inline
Definition at line 63 of file ControlParameter.h.
References type_.
 { return type_; };
setDisplayName()
void Tonic::Tonic_::ControlParameter_::setDisplayName (string displayName) inline
Definition at line 53 of file ControlParameter.h.
References displayName_.
 { displayName_ = displayName; };
setIsLogarithmic()
void Tonic::Tonic_::ControlParameter_::setIsLogarithmic (bool isLogarithmic) inline
Definition at line 65 of file ControlParameter.h.
References isLogarithmic_.
 { isLogarithmic_ = isLogarithmic; };
setMax()
void Tonic::Tonic_::ControlParameter_::setMax (TonicFloat max) inline
Definition at line 59 of file ControlParameter.h.
References Tonic::max(), and max_.
 { max_ = max; };
setMin()
void Tonic::Tonic_::ControlParameter_::setMin (TonicFloat min) inline
Definition at line 56 of file ControlParameter.h.
References Tonic::min(), and min_.
 { min_ = min; };
setName()
void Tonic::Tonic_::ControlParameter_::setName (string name) inline
Definition at line 50 of file ControlParameter.h.
References name_.
 { name_ = name; };
setNormalizedValue()
void Tonic::Tonic_::ControlParameter_::setNormalizedValue (TonicFloat normVal)
Definition at line 23 of file ControlParameter.cpp.
References isLogarithmic_, Tonic::map(), Tonic::mapLinToLog(), max_, min_, and Tonic::Tonic_::ControlValue_::setValue().
{
     if (isLogarithmic_){
       setValue(mapLinToLog(normVal, min_, max_));
     }
     else{
       setValue(map(normVal, 0.f, 1.f, min_, max_, true));
     }
   }
setType()
void Tonic::Tonic_::ControlParameter_::setType (ControlParameterType type) inline
Definition at line 62 of file ControlParameter.h.
References type_.
 { type_ = type; };
Member Data Documentation
displayName_
string Tonic::Tonic_::ControlParameter_::displayName_ protected
Definition at line 39 of file ControlParameter.h.
isLogarithmic_
bool Tonic::Tonic_::ControlParameter_::isLogarithmic_ protected
Definition at line 44 of file ControlParameter.h.
max_
TonicFloat Tonic::Tonic_::ControlParameter_::max_ protected
Definition at line 41 of file ControlParameter.h.
min_
TonicFloat Tonic::Tonic_::ControlParameter_::min_ protected
Definition at line 40 of file ControlParameter.h.
name_
string Tonic::Tonic_::ControlParameter_::name_ protected
Definition at line 38 of file ControlParameter.h.
type_
ControlParameterType Tonic::Tonic_::ControlParameter_::type_ protected
Definition at line 42 of file ControlParameter.h.
The documentation for this class was generated from the following files:
ControlParameter.h
ControlParameter.cpp