YOURPROJECTNAMEGOESHERE: Tonic::ControlParameter Class Reference
Tonic::ControlParameter Class Reference
#include <ControlParameter.h>
Public Member Functions
string getName ()
ControlParameter & name (string name)
string getDisplayName ()
ControlParameter & displayName (string displayName)
TonicFloat getValue ()
ControlParameter & value (TonicFloat value)
TonicFloat getMin ()
ControlParameter & min (TonicFloat min)
TonicFloat getMax ()
ControlParameter & max (TonicFloat max)
ControlParameterType getParameterType ()
ControlParameter & parameterType (ControlParameterType type)
bool getIsLogarithmic ()
ControlParameter & logarithmic (bool isLogarithmic)
TonicFloat getNormalizedValue ()
ControlParameter & setNormalizedValue (TonicFloat value)
Public Member Functions inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >
TemplatedControlGenerator ()
Public Member Functions inherited from Tonic::ControlGenerator
ControlGenerator (Tonic_::ControlGenerator_ *cGen=new Tonic_::ControlGenerator_)
ControlGeneratorOutput tick (const Tonic_::SynthesisContext_ &context)
RampedValue smoothed (float length=0.05)
ControlAdder operator+ (ControlGenerator b)
ControlAdder operator+ (float b)
ControlSubtractor operator- (ControlGenerator b)
ControlSubtractor operator- (float b)
ControlMultiplier operator* (ControlGenerator b)
ControlMultiplier operator* (float b)
ControlDivider operator/ (ControlGenerator b)
ControlDivider operator/ (float b)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::ControlGenerator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Public Types inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >
typedef Tonic_::ControlParameter_ gen_t
Protected Member Functions inherited from Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >
Tonic_::ControlParameter_ * gen ()
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::ControlGenerator_ >
Tonic_::ControlGenerator_ * obj
int * pcount
Detailed Description
Definition at line 75 of file ControlParameter.h.
Member Function Documentation
displayName()
ControlParameter & Tonic::ControlParameter::displayName (string displayName)
Definition at line 58 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), and Tonic::Tonic_::ControlParameter_::setDisplayName().
{
     gen()->setDisplayName(displayName);
     return *this;
   }
getDisplayName()
string Tonic::ControlParameter::getDisplayName ()
Definition at line 54 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), and Tonic::Tonic_::ControlParameter_::getDisplayName().
{
     return gen()->getDisplayName();
   }
getIsLogarithmic()
bool Tonic::ControlParameter::getIsLogarithmic ()
Definition at line 104 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), and Tonic::Tonic_::ControlParameter_::getIsLogarithmic().
{
     return gen()->getIsLogarithmic();
   }
getMax()
TonicFloat Tonic::ControlParameter::getMax ()
Definition at line 86 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), and Tonic::Tonic_::ControlParameter_::getMax().
{
     return gen()->getMax();
   }
getMin()
TonicFloat Tonic::ControlParameter::getMin ()
Definition at line 72 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), and Tonic::Tonic_::ControlParameter_::getMin().
{
     return gen()->getMin();
   }
getName()
string Tonic::ControlParameter::getName ()
Definition at line 45 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), and Tonic::Tonic_::ControlParameter_::getName().
{
     return gen()->getName();
   }
getNormalizedValue()
TonicFloat Tonic::ControlParameter::getNormalizedValue ()
Definition at line 113 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), and Tonic::Tonic_::ControlParameter_::getNormalizedValue().
{
     return gen()->getNormalizedValue();
   }
getParameterType()
ControlParameterType Tonic::ControlParameter::getParameterType ()
Definition at line 95 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), and Tonic::Tonic_::ControlParameter_::getType().
{
     return gen()->getType();
   }
getValue()
TonicFloat Tonic::ControlParameter::getValue ()
Definition at line 63 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), and Tonic::Tonic_::ControlValue_::getValue().
{
     return gen()->getValue();
   }
logarithmic()
ControlParameter & Tonic::ControlParameter::logarithmic (bool isLogarithmic)
Definition at line 99 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), and Tonic::Tonic_::ControlParameter_::setIsLogarithmic().
{
     gen()->setIsLogarithmic(isLogarithmic);
     return *this;
   }
max()
ControlParameter & Tonic::ControlParameter::max (TonicFloat max)
Definition at line 81 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), and Tonic::Tonic_::ControlParameter_::setMax().
{
     gen()->setMax(max);
     return *this;
   }
min()
ControlParameter & Tonic::ControlParameter::min (TonicFloat min)
Definition at line 76 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), and Tonic::Tonic_::ControlParameter_::setMin().
{
     gen()->setMin(min);
     return *this;
   }
name()
ControlParameter & Tonic::ControlParameter::name (string name)
Definition at line 49 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), and Tonic::Tonic_::ControlParameter_::setName().
{
     gen()->setName(name);
     return *this;
   }
parameterType()
ControlParameter & Tonic::ControlParameter::parameterType (ControlParameterType type)
Definition at line 90 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), and Tonic::Tonic_::ControlParameter_::setType().
{
     gen()->setType(type);
     return *this;
   }
setNormalizedValue()
ControlParameter & Tonic::ControlParameter::setNormalizedValue (TonicFloat value)
Definition at line 108 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), Tonic::Tonic_::ControlParameter_::setNormalizedValue(), and value().
{
     gen()->setNormalizedValue(value);
     return *this;
   }
value()
ControlParameter & Tonic::ControlParameter::value (TonicFloat value)
Definition at line 67 of file ControlParameter.cpp.
References Tonic::TemplatedControlGenerator< Tonic_::ControlParameter_ >::gen(), and Tonic::Tonic_::ControlValue_::setValue().
{
     gen()->setValue(value);
     return *this;
   }
The documentation for this class was generated from the following files:
ControlParameter.h
ControlParameter.cpp