YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::BufferPlayer_ Class Reference
Tonic::Tonic_::BufferPlayer_ Class Reference
#include <BufferPlayer.h>
Public Member Functions
BufferPlayer_ ()
~BufferPlayer_ ()
void computeSynthesisBlock (const SynthesisContext_ &context)
void setBuffer (SampleTable sampleTable)
void setDoesLoop (ControlGenerator doesLoop)
void setTrigger (ControlGenerator trigger)
void setStartPosition (ControlGenerator startPosition)
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Member Functions
void copySamplesToOutputBuffer (int startSample, int numSamples)
Protected Attributes
SampleTable buffer_
int testVar
int currentSample
int samplesPerSynthesisBlock
ControlGenerator doesLoop_
ControlGenerator trigger_
ControlGenerator startPosition_
bool isFinished_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Detailed Description
Definition at line 24 of file BufferPlayer.h.
Constructor & Destructor Documentation
BufferPlayer_()
Tonic::Tonic_::BufferPlayer_::BufferPlayer_ ()
Definition at line 14 of file BufferPlayer.cpp.
References doesLoop_, startPosition_, and trigger_.
                                : currentSample(0), isFinished_(true){
     doesLoop_ = ControlValue(false);
     trigger_ = ControlTrigger();
     startPosition_ = ControlValue(0);
   }
~BufferPlayer_()
Tonic::Tonic_::BufferPlayer_::~BufferPlayer_ ()
Definition at line 20 of file BufferPlayer.cpp.
{
   }
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::BufferPlayer_::computeSynthesisBlock (const SynthesisContext_ & context) inline virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 30 of file BufferPlayer.cpp.
References buffer_, Tonic::SampleTable::channels(), Tonic::TonicFrames::clear(), copySamplesToOutputBuffer(), currentSample, doesLoop_, isFinished_, Tonic::min(), Tonic::Tonic_::Generator_::outputFrames_, Tonic::sampleRate(), samplesPerSynthesisBlock, Tonic::SampleTable::size(), startPosition_, Tonic::ControlGenerator::tick(), trigger_, Tonic::ControlGeneratorOutput::triggered, and Tonic::ControlGeneratorOutput::value.
{
     bool doesLoop = doesLoop_.tick(context).value;
     bool trigger = trigger_.tick(context).triggered;
     float startPosition = startPosition_.tick(context).value;
     if(trigger){
       isFinished_ = false;
       currentSample = startPosition * sampleRate() * buffer_.channels();
     }
     if(isFinished_){
       outputFrames_.clear();
     }else{
       int samplesLeftInBuf = (int)buffer_.size() - currentSample;
       int samplesToCopy = min(samplesPerSynthesisBlock, samplesLeftInBuf);
       copySamplesToOutputBuffer(currentSample, samplesToCopy);
       if (samplesToCopy < samplesPerSynthesisBlock) {
         if(doesLoop){
           currentSample = 0;
         }else{
           isFinished_ = true;
         }
       }else{
         currentSample += samplesPerSynthesisBlock;
       }
     }
   }
copySamplesToOutputBuffer()
void Tonic::Tonic_::BufferPlayer_::copySamplesToOutputBuffer (int startSample, int numSamples) inline protected
Definition at line 51 of file BufferPlayer.h.
References buffer_, Tonic::SampleTable::dataPointer(), and Tonic::Tonic_::Generator_::outputFrames_.
{
       memcpy(&outputFrames_[0], &buffer_.dataPointer()[startSample], numSamples * sizeof(TonicFloat));
     }
setBuffer()
void Tonic::Tonic_::BufferPlayer_::setBuffer (SampleTable sampleTable)
Definition at line 24 of file BufferPlayer.cpp.
References buffer_, Tonic::SampleTable::channels(), Tonic::kSynthesisBlockSize, samplesPerSynthesisBlock, and Tonic::Tonic_::Generator_::setIsStereoOutput().
{
     buffer_ = buffer;
     setIsStereoOutput(buffer.channels() == 2);
     samplesPerSynthesisBlock = kSynthesisBlockSize * buffer_.channels();
   }
setDoesLoop()
void Tonic::Tonic_::BufferPlayer_::setDoesLoop (ControlGenerator doesLoop) inline
Definition at line 45 of file BufferPlayer.h.
References doesLoop_.
 {doesLoop_ = doesLoop;}
setStartPosition()
void Tonic::Tonic_::BufferPlayer_::setStartPosition (ControlGenerator startPosition) inline
Definition at line 47 of file BufferPlayer.h.
References startPosition_.
 {startPosition_ = startPosition;}
setTrigger()
void Tonic::Tonic_::BufferPlayer_::setTrigger (ControlGenerator trigger) inline
Definition at line 46 of file BufferPlayer.h.
References trigger_.
 {trigger_ = trigger;}
Member Data Documentation
buffer_
SampleTable Tonic::Tonic_::BufferPlayer_::buffer_ protected
Definition at line 28 of file BufferPlayer.h.
currentSample
int Tonic::Tonic_::BufferPlayer_::currentSample protected
Definition at line 30 of file BufferPlayer.h.
doesLoop_
ControlGenerator Tonic::Tonic_::BufferPlayer_::doesLoop_ protected
Definition at line 32 of file BufferPlayer.h.
isFinished_
bool Tonic::Tonic_::BufferPlayer_::isFinished_ protected
Definition at line 35 of file BufferPlayer.h.
samplesPerSynthesisBlock
int Tonic::Tonic_::BufferPlayer_::samplesPerSynthesisBlock protected
Definition at line 31 of file BufferPlayer.h.
startPosition_
ControlGenerator Tonic::Tonic_::BufferPlayer_::startPosition_ protected
Definition at line 34 of file BufferPlayer.h.
testVar
int Tonic::Tonic_::BufferPlayer_::testVar protected
Definition at line 29 of file BufferPlayer.h.
trigger_
ControlGenerator Tonic::Tonic_::BufferPlayer_::trigger_ protected
Definition at line 33 of file BufferPlayer.h.
The documentation for this class was generated from the following files:
BufferPlayer.h
BufferPlayer.cpp