YOURPROJECTNAMEGOESHERE: Tonic::Mixer Class Reference
Tonic::Mixer Class Reference
#include <Mixer.h>
Public Member Functions
void addInput (BufferFiller input)
void removeInput (BufferFiller input)
Public Member Functions inherited from Tonic::TemplatedBufferFiller< Tonic_::Mixer_ >
TemplatedBufferFiller ()
Public Member Functions inherited from Tonic::BufferFiller
BufferFiller (Tonic_::BufferFiller_ *newBf)
void fillBufferOfFloats (float *outData, unsigned int numFrames, unsigned int numChannels)
Fill an arbitrarily-sized, interleaved buffer of audio samples as floats.
Public Member Functions inherited from Tonic::Generator
Generator (Tonic_::Generator_ *gen=new Tonic_::Generator_)
bool isStereoOutput ()
virtual void tick (TonicFrames &frames, const Tonic_::SynthesisContext_ &context)
Public Member Functions inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
TonicSmartPointer ()
TonicSmartPointer (Tonic_::Generator_ *initObj)
TonicSmartPointer (const TonicSmartPointer &r)
TonicSmartPointer & operator= (const TonicSmartPointer &r)
~TonicSmartPointer ()
void retain ()
void release ()
bool operator== (const TonicSmartPointer &r)
Additional Inherited Members
Protected Member Functions inherited from Tonic::TemplatedBufferFiller< Tonic_::Mixer_ >
Tonic_::Mixer_ * gen ()
Protected Attributes inherited from Tonic::TonicSmartPointer< Tonic_::Generator_ >
Tonic_::Generator_ * obj
int * pcount
Detailed Description
Definition at line 59 of file Mixer.h.
Member Function Documentation
addInput()
void Tonic::Mixer::addInput (BufferFiller input) inline
Definition at line 63 of file Mixer.h.
References Tonic::Tonic_::Mixer_::addInput(), and Tonic::TemplatedBufferFiller< Tonic_::Mixer_ >::gen().
{
       gen()->addInput(input);
     }
removeInput()
void Tonic::Mixer::removeInput (BufferFiller input) inline
Definition at line 67 of file Mixer.h.
References Tonic::TemplatedBufferFiller< Tonic_::Mixer_ >::gen(), and Tonic::Tonic_::Mixer_::removeInput().
{
       gen()->removeInput(input);
     }
The documentation for this class was generated from the following file:
Mixer.h