YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::SawtoothWaveBL_ Class Reference
Tonic::Tonic_::SawtoothWaveBL_ Class Reference
Anti-aliased BLEP sawtooth.
#include <SawtoothWave.h>
Protected Member Functions
void computeSynthesisBlock (const SynthesisContext_ &context)
Protected Member Functions inherited from Tonic::Tonic_::BLEPOscillator_
void addBLEP (TonicFloat offset, TonicFloat scale)
Additional Inherited Members
Public Member Functions inherited from Tonic::Tonic_::BLEPOscillator_
BLEPOscillator_ ()
~BLEPOscillator_ ()
void setFreqGen (Generator gen)
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Attributes inherited from Tonic::Tonic_::BLEPOscillator_
Generator freqGen_
TonicFrames freqFrames_
float phase_
TonicFloat * ringBuf_
TonicFloat accum_
int lBuffer_
int iBuffer_
int nInit_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Static Protected Attributes inherited from Tonic::Tonic_::BLEPOscillator_
static const TonicFloat minBLEP_ []
static const int minBLEPlength_ = TONIC_MINBLEP_ZEROCROSSINGS * TONIC_MINBLEP_OVERSAMPLING * 2
static const int minBLEPOversampling_ = TONIC_MINBLEP_OVERSAMPLING
Detailed Description
Anti-aliased BLEP sawtooth.
Definition at line 120 of file SawtoothWave.h.
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::SawtoothWaveBL_::computeSynthesisBlock (const SynthesisContext_ & context) inline protected virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 129 of file SawtoothWave.h.
References Tonic::Tonic_::BLEPOscillator_::accum_, Tonic::Tonic_::BLEPOscillator_::addBLEP(), Tonic::Tonic_::BLEPOscillator_::freqFrames_, Tonic::Tonic_::BLEPOscillator_::freqGen_, Tonic::Tonic_::BLEPOscillator_::iBuffer_, Tonic::kSynthesisBlockSize, Tonic::Tonic_::BLEPOscillator_::lBuffer_, Tonic::Tonic_::BLEPOscillator_::nInit_, Tonic::Tonic_::Generator_::outputFrames_, Tonic::Tonic_::BLEPOscillator_::phase_, Tonic::Tonic_::BLEPOscillator_::ringBuf_, Tonic::sampleRate(), and Tonic::Generator::tick().
     {
       static const TonicFloat rateConstant =  1.0f / Tonic::sampleRate();
       // tick freq and pwm
       freqGen_.tick(freqFrames_, context);
       TonicFloat *outptr = &outputFrames_[0];
       TonicFloat *freqptr = &freqFrames_[0];
       // pre-multiply rate constant for speed
 #ifdef USE_APPLE_ACCELERATE
       vDSP_vsmul(freqptr, 1, &rateConstant, freqptr, 1, kSynthesisBlockSize);
 #else
       for (unsigned int i=0; i<kSynthesisBlockSize; i++){
         *freqptr++ *= rateConstant;
       }
       freqptr = &freqFrames_[0];
 #endif
       // TODO: Maybe do this using a fast phasor for wraparound speed
       for (unsigned int i=0; i<kSynthesisBlockSize; i++, freqptr++, outptr++){
         phase_ += *freqptr;
         // add BLEP at end
         if (phase_ >= 1.0)
         {
           phase_ -= 1.0;
           accum_ = 0.0f;
           addBLEP(phase_/(*freqptr), 1.0f);
         }
         *outptr = (TonicFloat)phase_;
         // add BLEP buffer contents
         if (nInit_ > 0)
         {
           *outptr += ringBuf_[iBuffer_];
           nInit_--;
           if (++iBuffer_ >= lBuffer_) iBuffer_ = 0;
         }
         // remove DC offset
         *outptr = (*outptr * 2.f) - 1.f;
       }
     }
The documentation for this class was generated from the following file:
SawtoothWave.h