YOURPROJECTNAMEGOESHERE: Tonic::Tonic_::RingBufferReader_ Class Reference
Tonic::Tonic_::RingBufferReader_ Class Reference
#include <RingBuffer.h>
Public Member Functions
void setRingBuffer (RingBuffer buffer)
void computeSynthesisBlock (const SynthesisContext_ &context)
Public Member Functions inherited from Tonic::Tonic_::Generator_
Generator_ ()
virtual ~Generator_ ()
virtual void tick (TonicFrames &frames, const SynthesisContext_ &context)
bool isStereoOutput ()
virtual void setIsStereoOutput (bool stereo)
Protected Attributes
RingBuffer ringBuffer_
Protected Attributes inherited from Tonic::Tonic_::Generator_
bool isStereoOutput_
TonicFrames outputFrames_
unsigned long lastFrameIndex_
Additional Inherited Members
Detailed Description
Definition at line 193 of file RingBuffer.h.
Member Function Documentation
computeSynthesisBlock()
void Tonic::Tonic_::RingBufferReader_::computeSynthesisBlock (const SynthesisContext_ & context) inline virtual
Reimplemented from Tonic::Tonic_::Generator_.
Definition at line 210 of file RingBuffer.h.
References Tonic::Tonic_::Generator_::outputFrames_, Tonic::RingBuffer::read(), and ringBuffer_.
{
       // get some output from the table
       ringBuffer_.read(outputFrames_);
     };
setRingBuffer()
void Tonic::Tonic_::RingBufferReader_::setRingBuffer (RingBuffer buffer) inline
Definition at line 201 of file RingBuffer.h.
References Tonic::SampleTable::channels(), ringBuffer_, and Tonic::Tonic_::Generator_::setIsStereoOutput().
{
         setIsStereoOutput(buffer.channels() == 2);
         ringBuffer_ = buffer;
       }
Member Data Documentation
ringBuffer_
RingBuffer Tonic::Tonic_::RingBufferReader_::ringBuffer_ protected
Definition at line 197 of file RingBuffer.h.
The documentation for this class was generated from the following file:
RingBuffer.h