YOURPROJECTNAMEGOESHERE: Tonic Namespace Reference
Tonic Namespace Reference
Top-level namespace.
Namespaces
Tonic_
DSP-level namespace.
Classes
class Adder
class ADSR
class BasicDelay
class Biquad
Biquad_ is an IIR biquad filter which provides a base object on which to build more advanced filters.
class BitCrusher
class BPF12
class BPF24
class BufferFiller
class BufferPlayer
class Compressor
class ControlAdder
class ControlChangeNotifier
class ControlChangeSubscriber
Abstract class to be extended by any class that wants to be notified of control events.
class ControlCounter
class ControlDbToLinear
class ControlDelay
class ControlDivider
class ControlEquals
class ControlFloor
class ControlGenerator
struct ControlGeneratorOutput
class ControlGreaterOrEqual
class ControlGreaterThan
class ControlLessOrEqual
class ControlLessThan
class ControlMetro
Ouputs a "changed" status at a regular BPM interval.
class ControlMetroDivider
class ControlMidiToFreq
class ControlMultiplier
class ControlNotEquals
class ControlParameter
class ControlPrinter
class ControlPulse
class ControlRandom
class ControlRecorder
class ControlSnapToScale
class ControlStepper
On trigger, outputs a value beginning at start, and incrementing by step toward end, then back again.
class ControlSubtractor
class ControlSwitcher
class ControlTrigger
class ControlTriggerFilter
class ControlValue
class ControlXYSpeed
class DelayLine
Tonicframes subclass with ability to tick in and out. Allows random-access/multi-tap/etc.
class Divider
union FastPhasor
For fast computation of int/fract using some bit-twiddlery.
class FBCombFilter
class FFCombFilter
class FilteredFBCombFilter6
class FixedValue
class Generator
class HPF12
class HPF24
class HPF6
class LFNoise
class Limiter
Special case of compressor where ratio is fixed to infinite and attack time is fixed to 0.1 ms.
class LPF12
class LPF24
class LPF6
class Mixer
class MonoToStereoPanner
class Multiplier
class Noise
class PinkNoise
class RampedValue
class RectWave
Quick-and-dirty rectangular wave.
class RectWaveBL
Bandlimited rectangular wave.
class Reverb
class RingBuffer
Like a SampleTable_, but with counters for over/underrun detection and easy synchronous read/write.
class RingBufferReader
class RingBufferWriter
class SampleTable
Access to a persistent TonicFrames instance, so the same audio data can be read from multiple places.
class SawtoothWave
Quick-and-dirty sawtooth oscillator.
class SawtoothWaveBL
Bandlimited sawtooth generator.
class SineWave
struct SourceRegister
class SquareWave
Quck-and-dirty square wave.
class SquareWaveBL
Bandlimited square wave.
class StereoDelay
class Subtractor
class Synth
struct SynthFactory
class TableLookupOsc
class TemplatedBufferFiller
class TemplatedControlComparisonOperator
class TemplatedControlConditioner
class TemplatedControlGenerator
class TemplatedEffect
class TemplatedFilter
class TemplatedGenerator
class TemplatedWetDryEffect
class TonicDictionary
Dictionary helper class for registering objects by name. For correct usage, objects should be Smart Pointers.
class TonicException
Tonic exception class.
class TonicFrames
class TonicSmartPointer
Reference counting smart pointer class template.
class TriangleWave
Quick-and-dirty triangle wave.
Enumerations
enum ControlParameterType { ControlParameterTypeContinuous = 0, ControlParameterTypeToggle, ControlParameterTypeMomentary }
Functions
static Adder operator+ (Generator a, Generator b)
static Adder operator+ (float a, Generator b)
static Adder operator+ (Generator a, float b)
static Adder operator+ (Generator a, ControlGenerator b)
static Adder operator+ (ControlGenerator a, Generator b)
static Adder operator+ (Adder a, ControlGenerator b)
static Adder operator+ (ControlGenerator a, Adder b)
static Subtractor operator- (Generator a, Generator b)
static Subtractor operator- (float a, Generator b)
static Subtractor operator- (Generator a, float b)
static Subtractor operator- (Generator a, ControlGenerator b)
static Subtractor operator- (ControlGenerator a, Generator b)
static Multiplier operator* (Generator a, Generator b)
static Multiplier operator* (float a, Generator b)
static Multiplier operator* (Generator a, float b)
static Multiplier operator* (Generator a, ControlGenerator b)
static Multiplier operator* (ControlGenerator a, Generator b)
static Multiplier operator* (Multiplier a, ControlGenerator b)
static Multiplier operator* (ControlGenerator a, Multiplier b)
static Divider operator/ (Generator a, Generator b)
static Divider operator/ (float a, Generator b)
static Divider operator/ (Generator a, float b)
static Divider operator/ (Generator a, ControlGenerator b)
static Divider operator/ (ControlGenerator a, Generator b)
SampleTable loadAudioFile (string path, int numChannels)
static ControlAdder operator+ (ControlGenerator a, ControlGenerator b)
static ControlAdder operator+ (ControlGenerator a, float b)
static ControlAdder operator+ (float a, ControlGenerator b)
static ControlSubtractor operator- (ControlGenerator a, ControlGenerator b)
static ControlSubtractor operator- (ControlGenerator a, float b)
static ControlSubtractor operator- (float a, ControlGenerator b)
static ControlMultiplier operator* (ControlGenerator a, ControlGenerator b)
static ControlMultiplier operator* (ControlGenerator a, float b)
static ControlMultiplier operator* (float a, ControlGenerator b)
static ControlDivider operator/ (ControlGenerator a, ControlGenerator b)
static ControlDivider operator/ (ControlGenerator a, float b)
static ControlDivider operator/ (float a, ControlGenerator b)
static ControlEquals operator== (ControlGenerator lhs, ControlGenerator rhs)
static ControlEquals operator== (ControlGenerator lhs, TonicFloat right)
static ControlNotEquals operator!= (ControlGenerator lhs, ControlGenerator rhs)
static ControlNotEquals operator!= (ControlGenerator lhs, TonicFloat right)
static ControlGreaterThan operator> (ControlGenerator lhs, ControlGenerator rhs)
static ControlGreaterThan operator> (ControlGenerator lhs, TonicFloat right)
static ControlGreaterOrEqual operator>= (ControlGenerator lhs, ControlGenerator rhs)
static ControlGreaterOrEqual operator>= (ControlGenerator lhs, TonicFloat right)
static ControlLessThan operator< (ControlGenerator lhs, ControlGenerator rhs)
static ControlLessThan operator< (ControlGenerator lhs, TonicFloat right)
static ControlLessOrEqual operator<= (ControlGenerator lhs, ControlGenerator rhs)
static ControlLessOrEqual operator<= (ControlGenerator lhs, TonicFloat right)
template<class ControlConditionerType , class ControlConditionerType_ >
static ControlConditionerType operator>> (ControlGenerator lhs, TemplatedControlConditioner< ControlConditionerType, ControlConditionerType_ > rhs)
void DFT (int length, float *realTimeIn, float *imagTimeIn, float *realFreqOut, float *imagFreqOut)
Discrete Fourier Transform.
void InverseDFT (int length, float *realFreqIn, float *imagFreqIn, float *realTimeOut, float *imagTimeOut)
Inverse Discrete Fourier Transform.
void RealCepstrum (int length, float *signalIn, float *realCepstrumOut)
Real Cepstrum.
void MinimumPhase (int n, float *realCepstrum, float *minimumPhase)
Compute Minimum Phase Reconstruction of singal from its real cepstrum.
float * GenerateMinBLEP (int zeroCrossings, int overSampling)
Generate MinBLEP And Return It In An Array Of Floating Point Values.
float cabs (float x, float y)
Complex Absolute Value.
void cexp (float x, float y, float *zx, float *zy)
Complex Exponential.
void GenerateHannWindow (int length, float *output)
Hann Window generation.
void GenerateHammingWindow (int length, float *output)
Hamming Window generation.
void GenerateBlackmanWindow (int length, float *output)
Blackman Window generation.
template<class EffectType , class EffectType_ >
static EffectType operator>> (Generator lhs, TemplatedEffect< EffectType, EffectType_ > rhs)
template<class EffectType , class EffectType_ >
static EffectType operator>> (Generator lhs, TemplatedWetDryEffect< EffectType, EffectType_ > rhs)
static TonicFloat t60ToOnePoleCoef (TonicFloat t60s)
Calculate coefficient for a pole with given time constant to reach -60dB delta in t60s seconds.
static TonicFloat cutoffToOnePoleCoef (TonicFloat cutoffHz)
Calculate coefficient for a pole with a given desired cutoff in hz.
void onePoleLPFTick (TonicFloat input, TonicFloat &output, TonicFloat coef)
Tick one sample through one-pole lowpass filter.
void onePoleHPFTick (TonicFloat input, TonicFloat &output, TonicFloat coef)
Tick one sample through one-pole highpass filter.
static void bltCoef (TonicFloat b2, TonicFloat b1, TonicFloat b0, TonicFloat a1, TonicFloat a0, TonicFloat fc, TonicFloat *coef_out)
Compute coefficients from analog prototype using bilinear transform.
template<typename T >
Synth createSynth ()
static void setSampleRate (TonicFloat sampleRate)
Set the operational sample rate.
static TonicFloat sampleRate ()
Return sample rate.
static void vcopy (TonicFloat *dst, unsigned int dst_str, const TonicFloat *src, unsigned int src_str, unsigned int length)
static TonicFloat max (TonicFloat a, TonicFloat b)
static TonicFloat min (TonicFloat a, TonicFloat b)
static TonicFloat clamp (TonicFloat val, TonicFloat min, TonicFloat max)
static TonicFloat map (TonicFloat val, TonicFloat inMin, TonicFloat inMax, TonicFloat outMin, TonicFloat outMax, bool clamp=true)
static TonicFloat lerp (TonicFloat x1, TonicFloat x2, TonicFloat f)
TonicFloat sinc (float x)
bool isPowerOf2 (unsigned int input, unsigned int *prevPo2)
static TonicFloat mapLinToLog (float linValue, float min, float max)
Takes linear value 0-1, maps to logarithmic value (base logBase) scaled to min-max. Useful for making faders.
static TonicFloat mapLogToLin (float logValue, float min, float max)
Takes logarithmic value between min-max, maps to linear value 0-1. Useful for making faders.
static TonicFloat mtof (TonicFloat nn)
Midi note number to frequency in Hz.
static TonicFloat ftom (TonicFloat f)
Frequency in Hz to midi note number.
static TonicFloat linTodB (TonicFloat lv)
static TonicFloat dBToLin (TonicFloat dBFS)
static TonicFloat randomSample ()
static float randomFloat (float a, float b)
static void error (string message, bool fatal=false)
static void warning (string message)
static void debug (string message)
Variables
TonicDictionary< RingBuffer > s_RingBuffers_
Registry of ring buffers.
static const unsigned int kSynthesisBlockSize = 64
"Vector" size for audio processing. ControlGenerators update at this rate.
static const Tonic_::SynthesisContext_ DummyContext
Dummy context for ticking things in-place.
Detailed Description
Top-level namespace.
Objects under the Tonic namespace are used to bulid synths and generator chains
Enumeration Type Documentation
ControlParameterType
enum Tonic::ControlParameterType
Enumerator
ControlParameterTypeContinuous
ControlParameterTypeToggle
ControlParameterTypeMomentary
Definition at line 18 of file ControlParameter.h.
               {
     ControlParameterTypeContinuous = 0,
     ControlParameterTypeToggle,
     ControlParameterTypeMomentary
   } ControlParameterType;
Function Documentation
bltCoef()
static void Tonic::bltCoef (TonicFloat b2, TonicFloat b1, TonicFloat b0, TonicFloat a1, TonicFloat a0, TonicFloat fc, TonicFloat * coef_out) inline static
Compute coefficients from analog prototype using bilinear transform.
Analog transfer function (laplace domain) should look like:
    b2 s^2 + b1 s + b0
H(s) = -----------------— s^2 + a1 s + a0
And be normalized for a cutoff of 1 rad/s.
fc is the desired frequency cutoff in Hz.
coef_out is a pointer to a TonicFloat array of length 5. No bounds checking is performed.
Definition at line 53 of file FilterUtils.h.
References PI, and sampleRate().
   {
       TonicFloat sf = 1.0f/tanf(PI*fc/Tonic::sampleRate());
       TonicFloat sfsq = sf*sf;
       TonicFloat norm = a0 + a1*sf + sfsq;
       coef_out[0] = (b0 + b1*sf + b2*sfsq)/norm;
       coef_out[1] = 2.0f * (b0 - b2*sfsq)/norm;
       coef_out[2] = (b0 - b1*sf + b2*sfsq)/norm;
       coef_out[3] = 2.0f * (a0 - sfsq)/norm;
       coef_out[4] = (a0 - a1*sf + sfsq)/norm;
   }
cabs()
float Tonic::cabs (float x, float y) inline
Complex Absolute Value.
Definition at line 25 of file DSPUtils.h.
   {
     return sqrtf((x * x) + (y * y));
   }
cexp()
void Tonic::cexp (float x, float y, float * zx, float * zy) inline
Complex Exponential.
Definition at line 31 of file DSPUtils.h.
   {
     float expx;
     expx = expf(x);
     *zx = expx * cosf(y);
     *zy = expx * sinf(y);
   }
clamp()
static TonicFloat Tonic::clamp (TonicFloat val, TonicFloat min, TonicFloat max) inline static
Definition at line 208 of file TonicCore.h.
References max(), and min().
{
     return (val < min ? min : (val > max ? max : val));
   }
createSynth()
template<typename T > Synth Tonic::createSynth ()
Definition at line 210 of file Synth.h.
{
     return T();
   }
cutoffToOnePoleCoef()
static TonicFloat Tonic::cutoffToOnePoleCoef (TonicFloat cutoffHz) inline static
Calculate coefficient for a pole with a given desired cutoff in hz.
Definition at line 24 of file FilterUtils.h.
References clamp(), sampleRate(), and TWO_PI.
{
     return clamp(expf(-TWO_PI*cutoffHz/sampleRate()), 0.f, 1.f);
   }
dBToLin()
static TonicFloat Tonic::dBToLin (TonicFloat dBFS) inline static
Definition at line 290 of file TonicCore.h.
{
     return powf(10.f,(dBFS/20.0f));
   }
debug()
static void Tonic::debug (string message) static
Definition at line 330 of file TonicCore.h.
{
 #ifdef TONIC_DEBUG
     printf("Tonic::debug: %s\n", message.c_str());
 #endif
   }
DFT()
void Tonic::DFT (int length, float * realTimeIn, float * imagTimeIn, float * realFreqOut, float * imagFreqOut)
Discrete Fourier Transform.
Non-FFT, brute force approach intended for wavetable generation. Do not use for real-time processing.
Definition at line 18 of file DSPUtils.cpp.
References PI.
   {
     int k, i;
     float sr, si, p;
     memset(realFreqOut, 0, sizeof(float) * length);
     memset(imagFreqOut, 0, sizeof(float) * length);
     for(k = 0; k < length; k++)
       for(i = 0; i < length; i++)
       {
         p = (2.0f * PI * (float)(k * i)) / length;
         sr = cosf(p);
         si = -sinf(p);
         realFreqOut[k] += (realTimeIn[i] * sr) - (imagTimeIn[i] * si);
         imagFreqOut[k] += (realTimeIn[i] * si) + (imagTimeIn[i] * sr);
       }
   }
error()
static void Tonic::error (string message, bool fatal = false) static
Definition at line 318 of file TonicCore.h.
{
     // maybe also log to console?
     printf("Tonic::error: %s\n", message.c_str() );
     if (fatal){
       Serial.println(message.c_str());
     }
   }
ftom()
static TonicFloat Tonic::ftom (TonicFloat f) inline static
Frequency in Hz to midi note number.
Definition at line 278 of file TonicCore.h.
{
     return 12.0f * (logf(f/440.0f)/logf(2.0f)) + 69.0f;
   }
GenerateBlackmanWindow()
void Tonic::GenerateBlackmanWindow (int length, float * output) inline
Blackman Window generation.
Definition at line 67 of file DSPUtils.h.
References PI.
   {
     int m = length - 1;
     int i;
     float f1, f2, fm;
     fm = (float)m;
     for(i = 0; i <= m; i++)
     {
       f1 = (2.0f * PI * (float)i) / fm;
       f2 = 2.0f * f1;
       output[i] = 0.42f - (0.5f * cosf(f1)) + (0.08f * cosf(f2));
     }
   }
GenerateHammingWindow()
void Tonic::GenerateHammingWindow (int length, float * output) inline
Hamming Window generation.
Definition at line 55 of file DSPUtils.h.
References PI.
   {
     int m = length - 1;
     int i;
     for (i=0; i <= m; i++)
     {
       output[i] = 0.54f - 0.46f * cosf((2 * PI * i)/m);
     }
   }
GenerateHannWindow()
void Tonic::GenerateHannWindow (int length, float * output) inline
Hann Window generation.
Definition at line 43 of file DSPUtils.h.
References PI.
   {
     int m = length - 1;
     int i;
     for (i=0; i <= m; i++)
     {
       output[i] = 0.5f*(1.f - cosf((2 * PI * i)/m));
     }
   }
GenerateMinBLEP()
float * Tonic::GenerateMinBLEP (int zeroCrossings, int overSampling)
Generate MinBLEP And Return It In An Array Of Floating Point Values.
Generate minBlep.
This can be used to create a new minimum phase bandlimited step function to store for later use as a lookup table.
Note that BLEPOscillator.cpp already has a runtime constant version of a BLEP for use with the BLEP-based oscillators.
Returns pointer to buffer of length *lengthOut. Caller is responsible for freeing heap-allocated buffer.
Definition at line 167 of file DSPUtils.cpp.
References GenerateBlackmanWindow(), MinimumPhase(), RealCepstrum(), and sinc().
   {
     int i, n, m;
     float r, a, b;
     float *buffer1, *buffer2, *minBLEP;
     // use power-of-two for DFT/Cepstrum for potential future
     // speed boost
     n = (zeroCrossings * 2 * overSampling) + 1;
     m = n-1;
     buffer1 = new float[m];
     buffer2 = new float[m];
     // Generate Sinc
     a = (float)-zeroCrossings;
     b = (float)zeroCrossings;
     for(i = 0; i < m; i++)
     {
       r = ((float)i) / ((float)m);
       buffer1[i] = sinc(a + (r * (b - a)));
     }
     GenerateBlackmanWindow(m, buffer2);
     for(i = 0; i < m; i++)
     {
       buffer1[i] *= buffer2[i];
     }
     // Minimum Phase Reconstruction
     RealCepstrum(m, buffer1, buffer2);
     MinimumPhase(m, buffer2, buffer1);
     // Integrate Into MinBLEP
     minBLEP = new float[n];
     a = 0.0f;
     for(i = 0; i < m; i++)
     {
         a += buffer1[i];
         minBLEP[i] = a;
     }
     // copy next-to-last sample
     minBLEP[m] = minBLEP[m-1];
     // Normalize
     a = minBLEP[m];
     a = 1.0f / a;
     for(i = 0; i < n; i++)
     {
       minBLEP[i] *= a;
     }
     delete buffer1;
     delete buffer2;
     return minBLEP;
   }
InverseDFT()
void Tonic::InverseDFT (int length, float * realFreqIn, float * imagFreqIn, float * realTimeOut, float * imagTimeOut)
Inverse Discrete Fourier Transform.
Non-FFT, brute force approach intended for wavetable generation. Do not use for real-time processing.
Definition at line 39 of file DSPUtils.cpp.
References PI.
   {
     int k, i;
     float sr, si, p;
     memset(realTimeOut, 0, sizeof(float) * length);
     memset(imagTimeOut, 0, sizeof(float) * length);
     for(k = 0; k < length; k++)
     {
       for(i = 0; i < length; i++)
       {
         p = (2.0f * PI * (float)(k * i)) / length;
         sr = cosf(p);
         si = -sinf(p);
         realTimeOut[k] += (realFreqIn[i] * sr) + (imagFreqIn[i] * si);
         imagTimeOut[k] += (realFreqIn[i] * si) - (imagFreqIn[i] * sr);
       }
       realTimeOut[k] /= (float)length;
       imagTimeOut[k] /= (float)length;
     }
   }
isPowerOf2()
bool Tonic::isPowerOf2 (unsigned int input, unsigned int * prevPo2) inline
Definition at line 239 of file TonicCore.h.
{
     if (input == 0) return true;
     unsigned int po2 = 2;
     while (po2 < input){
       po2 *= 2;
     }
     if (prevPo2){
       unsigned int nextPo2 = po2 * 2;
       *prevPo2 = abs((int)input - (int)po2) < abs((int)input - (int)nextPo2) ? po2 : nextPo2;
     }
     return input == po2;
   }
lerp()
static TonicFloat Tonic::lerp (TonicFloat x1, TonicFloat x2, TonicFloat f) inline static
Definition at line 221 of file TonicCore.h.
{
     return (x1 + f*(x2-x1));
   }
linTodB()
static TonicFloat Tonic::linTodB (TonicFloat lv) inline static
Definition at line 286 of file TonicCore.h.
References max().
{
     return 20.0f*log10f(max(0, lv));
   }
loadAudioFile()
SampleTable Tonic::loadAudioFile (string path, int numChannels)
Definition at line 92 of file AudioFileUtils.cpp.
References error().
{
     Tonic::error("loadAudioFile is currently only implemented for Apple platforms.");
     return NULL;
   }
map()
static TonicFloat Tonic::map (TonicFloat val, TonicFloat inMin, TonicFloat inMax, TonicFloat outMin, TonicFloat outMax, bool clamp = true) inline static
Definition at line 212 of file TonicCore.h.
References clamp(), max(), and min().
{
     TonicFloat result = ((val - inMin)/(inMax - inMin)) * (outMax - outMin) + outMin;
     if (clamp){
       result = Tonic::clamp(result, min(outMin,outMax), max(outMin,outMax));
     }
     return result;
   }
mapLinToLog()
static TonicFloat Tonic::mapLinToLog (float linValue, float min, float max) inline static
Takes linear value 0-1, maps to logarithmic value (base logBase) scaled to min-max. Useful for making faders.
Definition at line 260 of file TonicCore.h.
References map(), max(), min(), and TONIC_LOG_MAP_BASEVAL.
{
     float expValue = map(linValue, 0.f, 1.f, TONIC_LOG_MAP_BASEVAL, 0.f, true);
     return map(powf(10.f,expValue), 0.0001f, 1.0f, min, max, true);
   }
mapLogToLin()
static TonicFloat Tonic::mapLogToLin (float logValue, float min, float max) inline static
Takes logarithmic value between min-max, maps to linear value 0-1. Useful for making faders.
Definition at line 266 of file TonicCore.h.
References map(), max(), min(), and TONIC_LOG_MAP_BASEVAL.
{
     return map(log10f(map(logValue, min, max, 0.0001f, 1.f,true)), TONIC_LOG_MAP_BASEVAL, 0.f, 0.f, 1.f, true);
   }
max()
static TonicFloat Tonic::max (TonicFloat a, TonicFloat b) inline static
Definition at line 200 of file TonicCore.h.
{
     return (a > b ? a : b);
   }
min()
static TonicFloat Tonic::min (TonicFloat a, TonicFloat b) inline static
Definition at line 204 of file TonicCore.h.
{
     return (a < b ? a : b);
   }
MinimumPhase()
void Tonic::MinimumPhase (int length, float * realCepstrum, float * minimumPhase)
Compute Minimum Phase Reconstruction of singal from its real cepstrum.
Definition at line 108 of file DSPUtils.cpp.
References cexp(), DFT(), and InverseDFT().
   {
     int i, nd2;
     float *realTime, *imagTime, *realFreq, *imagFreq;
     nd2 = length / 2;
     realTime = new float[length];
     imagTime = new float[length];
     realFreq = new float[length];
     imagFreq = new float[length];
     if((length % 2) == 1)
     {
       realTime[0] = realCepstrum[0];
       for(i = 1; i < nd2; i++)
         realTime[i] = 2.0f * realCepstrum[i];
       for(i = nd2; i < length; i++)
         realTime[i] = 0.0f;
     }
     else
     {
       realTime[0] = realCepstrum[0];
       for(i = 1; i < nd2; i++)
         realTime[i] = 2.0f * realCepstrum[i];
       realTime[nd2] = realCepstrum[nd2];
       for(i = nd2 + 1; i < length; i++)
         realTime[i] = 0.0f;
     }
     for(i = 0; i < length; i++)
       imagTime[i] = 0.0f;
     DFT(length, realTime, imagTime, realFreq, imagFreq);
     for(i = 0; i < length; i++)
       cexp(realFreq[i], imagFreq[i], &realFreq[i], &imagFreq[i]);
     InverseDFT(length, realFreq, imagFreq, realTime, imagTime);
     for(i = 0; i < length; i++)
       minimumPhase[i] = realTime[i];
     delete realTime;
     delete imagTime;
     delete realFreq;
     delete imagFreq;
   }
mtof()
static TonicFloat Tonic::mtof (TonicFloat nn) inline static
Midi note number to frequency in Hz.
Definition at line 273 of file TonicCore.h.
{
     return 440.0f * powf(2.0f, (nn-69.0f)/12.0f);
   }
onePoleHPFTick()
void Tonic::onePoleHPFTick (TonicFloat input, TonicFloat & output, TonicFloat coef) inline
Tick one sample through one-pole highpass filter.
Definition at line 34 of file FilterUtils.h.
{
     output = ((1.0-coef) * input) - (coef * output);
   }
onePoleLPFTick()
void Tonic::onePoleLPFTick (TonicFloat input, TonicFloat & output, TonicFloat coef) inline
Tick one sample through one-pole lowpass filter.
Definition at line 29 of file FilterUtils.h.
{
     output = ((1.0f-coef) * input) + (coef * output);
   }
operator!=() [1/2]
static ControlNotEquals Tonic::operator!= (ControlGenerator lhs, ControlGenerator rhs) static
Definition at line 141 of file ControlComparison.h.
References Tonic::TemplatedControlComparisonOperator< OperatorType >::setLeft(), and Tonic::TemplatedControlComparisonOperator< OperatorType >::setRight().
{
     ControlNotEquals c;
     c.setLeft(lhs);
     c.setRight(rhs);
     return c;
   }
operator!=() [2/2]
static ControlNotEquals Tonic::operator!= (ControlGenerator lhs, TonicFloat right) static
Definition at line 148 of file ControlComparison.h.
References Tonic::TemplatedControlComparisonOperator< OperatorType >::setLeft(), and Tonic::TemplatedControlComparisonOperator< OperatorType >::setRight().
{
     ControlNotEquals c;
     c.setLeft(lhs);
     c.setRight(ControlValue(right));
     return c;
   }
operator*() [1/10]
static ControlMultiplier Tonic::operator* (ControlGenerator a, ControlGenerator b) static
Definition at line 230 of file ControlArithmetic.h.
References Tonic::ControlMultiplier::input().
{
     ControlMultiplier mult;
     mult.input(a);
     mult.input(b);
     return mult;
   }
operator*() [2/10]
static ControlMultiplier Tonic::operator* (ControlGenerator a, float b) static
Definition at line 237 of file ControlArithmetic.h.
References Tonic::ControlMultiplier::input().
{
     ControlMultiplier mult;
     mult.input(a);
     mult.input(ControlValue(b));
     return mult;
   }
operator*() [3/10]
static ControlMultiplier Tonic::operator* (float a, ControlGenerator b) static
Definition at line 244 of file ControlArithmetic.h.
References Tonic::ControlMultiplier::input().
{
     ControlMultiplier mult;
     mult.input(ControlValue(a));
     mult.input(ControlGenerator(b));
     return mult;
   }
operator*() [4/10]
static Multiplier Tonic::operator* (Generator a, Generator b) static
Definition at line 260 of file Arithmetic.h.
References Tonic::Multiplier::input().
{
     Multiplier mult;
     mult.input(a);
     mult.input(b);
     return mult;
   }
operator*() [5/10]
static Multiplier Tonic::operator* (float a, Generator b) static
Definition at line 267 of file Arithmetic.h.
{
     return FixedValue(a) * b;
   }
operator*() [6/10]
static Multiplier Tonic::operator* (Generator a, float b) static
Definition at line 271 of file Arithmetic.h.
{
     return a * FixedValue(b);
   }
operator*() [7/10]
static Multiplier Tonic::operator* (Generator a, ControlGenerator b) static
Definition at line 278 of file Arithmetic.h.
References Tonic::FixedValue::setValue().
{
     return a * FixedValue().setValue(b);
   }
operator*() [8/10]
static Multiplier Tonic::operator* (ControlGenerator a, Generator b) static
Definition at line 282 of file Arithmetic.h.
References Tonic::FixedValue::setValue().
{
     return FixedValue().setValue(a) * b;
   }
operator*() [9/10]
static Multiplier Tonic::operator* (Multiplier a, ControlGenerator b) static
Definition at line 288 of file Arithmetic.h.
References Tonic::FixedValue::setValue().
{
     return a * FixedValue().setValue(b);
   }
operator*() [10/10]
static Multiplier Tonic::operator* (ControlGenerator a, Multiplier b) static
Definition at line 292 of file Arithmetic.h.
References Tonic::FixedValue::setValue().
{
     return FixedValue().setValue(a) * b;
   }
operator+() [1/10]
static Adder Tonic::operator+ (Generator a, Generator b) static
Definition at line 80 of file Arithmetic.h.
References Tonic::Adder::input().
{
     Adder add;
     add.input(a);
     add.input(b);
     return add;
   }
operator+() [2/10]
static ControlAdder Tonic::operator+ (ControlGenerator a, ControlGenerator b) static
Definition at line 82 of file ControlArithmetic.h.
References Tonic::ControlAdder::input().
{
     ControlAdder adder;
     adder.input(a);
     adder.input(b);
     return adder;
   }
operator+() [3/10]
static Adder Tonic::operator+ (float a, Generator b) static
Definition at line 88 of file Arithmetic.h.
References Tonic::Adder::input().
{
     Adder add;
     add.input(FixedValue(a));
     add.input(b);
     return add;
   }
operator+() [4/10]
static ControlAdder Tonic::operator+ (ControlGenerator a, float b) static
Definition at line 89 of file ControlArithmetic.h.
References Tonic::ControlAdder::input().
{
     ControlAdder adder;
     adder.input(a);
     adder.input(ControlValue(b));
     return adder;
   }
operator+() [5/10]
static Adder Tonic::operator+ (Generator a, float b) static
Definition at line 96 of file Arithmetic.h.
References Tonic::Adder::input().
{
     Adder add;
     add.input(a);
     add.input(FixedValue(b));
     return add;
   }
operator+() [6/10]
static ControlAdder Tonic::operator+ (float a, ControlGenerator b) static
Definition at line 96 of file ControlArithmetic.h.
References Tonic::ControlAdder::input().
{
     ControlAdder adder;
     adder.input(ControlValue(a));
     adder.input(ControlGenerator(b));
     return adder;
   }
operator+() [7/10]
static Adder Tonic::operator+ (Generator a, ControlGenerator b) static
Definition at line 106 of file Arithmetic.h.
References Tonic::FixedValue::setValue().
{
     return a + FixedValue().setValue(b);
   }
operator+() [8/10]
static Adder Tonic::operator+ (ControlGenerator a, Generator b) static
Definition at line 110 of file Arithmetic.h.
References Tonic::FixedValue::setValue().
{
     return FixedValue().setValue(a) + b;
   }
operator+() [9/10]
static Adder Tonic::operator+ (Adder a, ControlGenerator b) static
Definition at line 116 of file Arithmetic.h.
References Tonic::FixedValue::setValue().
{
     return a + FixedValue().setValue(b);
   }
operator+() [10/10]
static Adder Tonic::operator+ (ControlGenerator a, Adder b) static
Definition at line 120 of file Arithmetic.h.
References Tonic::FixedValue::setValue().
{
     return FixedValue().setValue(a) + b;
   }
operator-() [1/8]
static ControlSubtractor Tonic::operator- (ControlGenerator a, ControlGenerator b) static
Definition at line 148 of file ControlArithmetic.h.
{
     ControlSubtractor subtractor;
     subtractor.left(a);
     subtractor.right(b);
     return subtractor;
   }
operator-() [2/8]
static ControlSubtractor Tonic::operator- (ControlGenerator a, float b) static
Definition at line 155 of file ControlArithmetic.h.
{
     ControlSubtractor subtractor;
     subtractor.left(a);
     subtractor.right(ControlValue(b));
     return subtractor;
   }
operator-() [3/8]
static ControlSubtractor Tonic::operator- (float a, ControlGenerator b) static
Definition at line 162 of file ControlArithmetic.h.
{
     ControlSubtractor subtractor;
     subtractor.left(ControlValue(a));
     subtractor.right(ControlGenerator(b));
     return subtractor;
   }
operator-() [4/8]
static Subtractor Tonic::operator- (Generator a, Generator b) static
Definition at line 168 of file Arithmetic.h.
{
     Subtractor sub;
     sub.left(a);
     sub.right(b);
     return sub;
   }
operator-() [5/8]
static Subtractor Tonic::operator- (float a, Generator b) static
Definition at line 175 of file Arithmetic.h.
{
     Subtractor sub;
     sub.left(FixedValue(a));
     sub.right(b);
     return sub;
   }
operator-() [6/8]
static Subtractor Tonic::operator- (Generator a, float b) static
Definition at line 182 of file Arithmetic.h.
{
     Subtractor sub;
     sub.left(a);
     sub.right(FixedValue(b));
     return sub;
   }
operator-() [7/8]
static Subtractor Tonic::operator- (Generator a, ControlGenerator b) static
Definition at line 191 of file Arithmetic.h.
References Tonic::FixedValue::setValue().
{
     return a - FixedValue().setValue(b);
   }
operator-() [8/8]
static Subtractor Tonic::operator- (ControlGenerator a, Generator b) static
Definition at line 195 of file Arithmetic.h.
References Tonic::FixedValue::setValue().
{
     return FixedValue().setValue(a) - b;
   }
operator/() [1/8]
static ControlDivider Tonic::operator/ (ControlGenerator a, ControlGenerator b) static
Definition at line 303 of file ControlArithmetic.h.
{
     ControlDivider divider;
     divider.left(a);
     divider.right(b);
     return divider;
   }
operator/() [2/8]
static ControlDivider Tonic::operator/ (ControlGenerator a, float b) static
Definition at line 310 of file ControlArithmetic.h.
{
     ControlDivider divider;
     divider.left(a);
     divider.right(ControlValue(b));
     return divider;
   }
operator/() [3/8]
static ControlDivider Tonic::operator/ (float a, ControlGenerator b) static
Definition at line 317 of file ControlArithmetic.h.
{
     ControlDivider divider;
     divider.left(ControlValue(a));
     divider.right(ControlGenerator(b));
     return divider;
   }
operator/() [4/8]
static Divider Tonic::operator/ (Generator a, Generator b) static
Definition at line 340 of file Arithmetic.h.
{
     Divider div;
     div.left(a);
     div.right(b);
     return div;
   }
operator/() [5/8]
static Divider Tonic::operator/ (float a, Generator b) static
Definition at line 347 of file Arithmetic.h.
{
     Divider div;
     div.left(FixedValue(a));
     div.right(b);
     return div;
   }
operator/() [6/8]
static Divider Tonic::operator/ (Generator a, float b) static
Definition at line 354 of file Arithmetic.h.
{
     Divider div;
     div.left(a);
     div.right(FixedValue(b));
     return div;
   }
operator/() [7/8]
static Divider Tonic::operator/ (Generator a, ControlGenerator b) static
Definition at line 363 of file Arithmetic.h.
References Tonic::FixedValue::setValue().
{
     return a / FixedValue().setValue(b);
   }
operator/() [8/8]
static Divider Tonic::operator/ (ControlGenerator a, Generator b) static
Definition at line 367 of file Arithmetic.h.
References Tonic::FixedValue::setValue().
{
     return FixedValue().setValue(a) / b;
   }
operator<() [1/2]
static ControlLessThan Tonic::operator< (ControlGenerator lhs, ControlGenerator rhs) static
Definition at line 246 of file ControlComparison.h.
References Tonic::TemplatedControlComparisonOperator< OperatorType >::setLeft(), and Tonic::TemplatedControlComparisonOperator< OperatorType >::setRight().
{
     ControlLessThan c;
     c.setLeft(lhs);
     c.setRight(rhs);
     return c;
   }
operator<() [2/2]
static ControlLessThan Tonic::operator< (ControlGenerator lhs, TonicFloat right) static
Definition at line 253 of file ControlComparison.h.
References Tonic::TemplatedControlComparisonOperator< OperatorType >::setLeft(), and Tonic::TemplatedControlComparisonOperator< OperatorType >::setRight().
{
     ControlLessThan c;
     c.setLeft(lhs);
     c.setRight(ControlValue(right));
     return c;
   }
operator<=() [1/2]
static ControlLessOrEqual Tonic::operator<= (ControlGenerator lhs, ControlGenerator rhs) static
Definition at line 281 of file ControlComparison.h.
References Tonic::TemplatedControlComparisonOperator< OperatorType >::setLeft(), and Tonic::TemplatedControlComparisonOperator< OperatorType >::setRight().
{
     ControlLessOrEqual c;
     c.setLeft(lhs);
     c.setRight(rhs);
     return c;
   }
operator<=() [2/2]
static ControlLessOrEqual Tonic::operator<= (ControlGenerator lhs, TonicFloat right) static
Definition at line 288 of file ControlComparison.h.
References Tonic::TemplatedControlComparisonOperator< OperatorType >::setLeft(), and Tonic::TemplatedControlComparisonOperator< OperatorType >::setRight().
{
     ControlLessOrEqual c;
     c.setLeft(lhs);
     c.setRight(ControlValue(right));
     return c;
   }
operator==() [1/2]
static ControlEquals Tonic::operator== (ControlGenerator lhs, ControlGenerator rhs) static
Definition at line 107 of file ControlComparison.h.
References Tonic::TemplatedControlComparisonOperator< OperatorType >::setLeft(), and Tonic::TemplatedControlComparisonOperator< OperatorType >::setRight().
{
     ControlEquals c;
     c.setLeft(lhs);
     c.setRight(rhs);
     return c;
   }
operator==() [2/2]
static ControlEquals Tonic::operator== (ControlGenerator lhs, TonicFloat right) static
Definition at line 114 of file ControlComparison.h.
References Tonic::TemplatedControlComparisonOperator< OperatorType >::setLeft(), and Tonic::TemplatedControlComparisonOperator< OperatorType >::setRight().
{
     ControlEquals c;
     c.setLeft(lhs);
     c.setRight(ControlValue(right));
     return c;
   }
operator>() [1/2]
static ControlGreaterThan Tonic::operator> (ControlGenerator lhs, ControlGenerator rhs) static
Definition at line 176 of file ControlComparison.h.
References Tonic::TemplatedControlComparisonOperator< OperatorType >::setLeft(), and Tonic::TemplatedControlComparisonOperator< OperatorType >::setRight().
{
     ControlGreaterThan c;
     c.setLeft(lhs);
     c.setRight(rhs);
     return c;
   }
operator>() [2/2]
static ControlGreaterThan Tonic::operator> (ControlGenerator lhs, TonicFloat right) static
Definition at line 183 of file ControlComparison.h.
References Tonic::TemplatedControlComparisonOperator< OperatorType >::setLeft(), and Tonic::TemplatedControlComparisonOperator< OperatorType >::setRight().
{
     ControlGreaterThan c;
     c.setLeft(lhs);
     c.setRight(ControlValue(right));
     return c;
   }
operator>=() [1/2]
static ControlGreaterOrEqual Tonic::operator>= (ControlGenerator lhs, ControlGenerator rhs) static
Definition at line 211 of file ControlComparison.h.
References Tonic::TemplatedControlComparisonOperator< OperatorType >::setLeft(), and Tonic::TemplatedControlComparisonOperator< OperatorType >::setRight().
{
     ControlGreaterOrEqual c;
     c.setLeft(lhs);
     c.setRight(rhs);
     return c;
   }
operator>=() [2/2]
static ControlGreaterOrEqual Tonic::operator>= (ControlGenerator lhs, TonicFloat right) static
Definition at line 218 of file ControlComparison.h.
References Tonic::TemplatedControlComparisonOperator< OperatorType >::setLeft(), and Tonic::TemplatedControlComparisonOperator< OperatorType >::setRight().
{
     ControlGreaterOrEqual c;
     c.setLeft(lhs);
     c.setRight(ControlValue(right));
     return c;
   }
operator>>() [1/3]
template<class ControlConditionerType , class ControlConditionerType_ > static ControlConditionerType Tonic::operator>> (ControlGenerator lhs, TemplatedControlConditioner< ControlConditionerType, ControlConditionerType_ > rhs) static
Definition at line 61 of file ControlConditioner.h.
References Tonic::TemplatedControlConditioner< ControlConditionerType, ControlConditionerType_ >::input().
{
     return rhs.input( lhs );
   }
operator>>() [2/3]
template<class EffectType , class EffectType_ > static EffectType Tonic::operator>> (Generator lhs, TemplatedEffect< EffectType, EffectType_ > rhs) static
Definition at line 150 of file Effect.h.
References Tonic::TemplatedEffect< EffectType, EffectType_ >::input().
{
     return rhs.input( lhs );
   }
operator>>() [3/3]
template<class EffectType , class EffectType_ > static EffectType Tonic::operator>> (Generator lhs, TemplatedWetDryEffect< EffectType, EffectType_ > rhs) static
Definition at line 292 of file Effect.h.
References Tonic::TemplatedWetDryEffect< EffectType, EffectType_ >::input().
{
     return rhs.input( lhs );
   }
randomFloat()
static float Tonic::randomFloat (float a, float b) static
Definition at line 300 of file TonicCore.h.
{
     float random = ((float) rand()) / (float) RAND_MAX;
     float diff = b - a;
     float r = random * diff;
     return a + r;
 }
randomSample()
static TonicFloat Tonic::randomSample () inline static
Definition at line 296 of file TonicCore.h.
{
     return ((TonicFloat)rand()/RAND_MAX) * 2.0f - 1.0f;
   }
RealCepstrum()
void Tonic::RealCepstrum (int length, float * signalIn, float * realCepstrumOut)
Real Cepstrum.
Definition at line 63 of file DSPUtils.cpp.
References cabs(), DFT(), and InverseDFT().
   {
     float *realTime, *imagTime, *realFreq, *imagFreq;
     int i;
     realTime = new float[length];
     imagTime = new float[length];
     realFreq = new float[length];
     imagFreq = new float[length];
     // Compose Complex FFT Input
     for(i = 0; i < length; i++)
     {
       realTime[i] = signalIn[i];
       imagTime[i] = 0.0f;
     }
     // Perform DFT
     DFT(length, realTime, imagTime, realFreq, imagFreq);
     // Calculate Log Of Absolute Value
     for(i = 0; i < length; i++)
     {
       realFreq[i] = logf(cabs(realFreq[i], imagFreq[i]));
       imagFreq[i] = 0.0f;
     }
     // Perform Inverse FFT
     InverseDFT(length, realFreq, imagFreq, realTime, imagTime);
     // Output Real Part Of FFT
     for(i = 0; i < length; i++)
       realCepstrumOut[i] = realTime[i];
     delete realTime;
     delete imagTime;
     delete realFreq;
     delete imagFreq;
   }
sampleRate()
static TonicFloat Tonic::sampleRate () static
Return sample rate.
Definition at line 134 of file TonicCore.h.
References Tonic::Tonic_::sampleRate_.
{
     return Tonic_::sampleRate_;
   };
setSampleRate()
static void Tonic::setSampleRate (TonicFloat sampleRate) static
Set the operational sample rate.
!!!: CHANGING WHILE RUNNING WILL RESULT IN UNDEFINED BEHAVIOR. MUST BE SET PRIOR TO OBJECT ALLOCATION.
Definition at line 129 of file TonicCore.h.
References sampleRate(), and Tonic::Tonic_::sampleRate_.
{
     Tonic_::sampleRate_ = sampleRate;
   }
sinc()
TonicFloat Tonic::sinc (float x) inline
Definition at line 225 of file TonicCore.h.
References PI.
   {
     TonicFloat pi_x;
     if(x == 0.0f)
       return 1.0f;
     else
     {
       pi_x = PI * x;
       return sinf(pi_x) / pi_x;
     }
   }
t60ToOnePoleCoef()
static TonicFloat Tonic::t60ToOnePoleCoef (TonicFloat t60s) inline static
Calculate coefficient for a pole with given time constant to reach -60dB delta in t60s seconds.
Definition at line 18 of file FilterUtils.h.
References sampleRate().
{
     float coef = expf(-1.0f/((t60s/6.91f) * sampleRate()));
     return (coef == coef) ? coef : 0.f; // catch NaN
   }
vcopy()
static void Tonic::vcopy (TonicFloat * dst, unsigned int dst_str, const TonicFloat * src, unsigned int src_str, unsigned int length) inline static
Definition at line 192 of file TonicCore.h.
{
     for (unsigned int i=0; i<length; i++, dst += dst_str, src += src_str){
       *dst = *src;
     }
   }
warning()
static void Tonic::warning (string message) static
Definition at line 326 of file TonicCore.h.
{
     printf("Tonic::warning: %s\n", message.c_str());
   }
Variable Documentation
DummyContext
const Tonic_::SynthesisContext_ Tonic::DummyContext static
Dummy context for ticking things in-place.
Definition at line 187 of file TonicCore.h.
kSynthesisBlockSize
const unsigned int Tonic::kSynthesisBlockSize = 64 static
"Vector" size for audio processing. ControlGenerators update at this rate.
!!!: THIS VALUE SHOULD BE A POWER-OF-TWO WHICH IS LESS THAN THE HARDWARE BUFFER SIZE
Definition at line 140 of file TonicCore.h.
s_RingBuffers_
TonicDictionary<RingBuffer> Tonic::s_RingBuffers_
Registry of ring buffers.
Definition at line 13 of file RingBuffer.cpp.